# Generated by Django 6.0.1 on 2026-04-06 10:20
import uuid
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('chat', '0004_chatpushsubscription'),
 ]
 operations = [
 migrations.CreateModel(
 name='OrchestrationRun',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
 ('thread_id', models.CharField(db_index=True, help_text='LangGraph thread_id，等于 str(conversation.id)', max_length=255)),
 ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('waiting', '等待中'), ('completed', '已完成'), ('error', '错误')], db_index=True, default='pending', max_length=20)),
 ('phase', models.CharField(choices=[('planning', '规划'), ('executing', '执行'), ('waiting', '等待'), ('finalizing', '收尾'), ('completed', '完成'), ('error', '错误')], default='planning', max_length=20)),
 ('checkpoint_id', models.CharField(blank=True, default='', help_text='最新 LangGraph checkpoint ID', max_length=255)),
 ('metadata', models.JSONField(blank=True, default=dict)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_runs', to='chat.conversation')),
 ],
 options={
 'verbose_name': '编排运行',
 'verbose_name_plural': '编排运行',
 'ordering': ['-created_at'],
 'indexes': [models.Index(fields=['conversation', '-created_at'], name='orchestrati_convers_e4f655_idx'), models.Index(fields=['thread_id', 'status'], name='orchestrati_thread__964fef_idx')],
 },
 ),
 ]
