# Generated by Django 6.0.1 on 2026-04-06 13:37
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('orchestration', '0001_initial'),
 ]
 operations = [
 migrations.AlterField(
 model_name='orchestrationrun',
 name='status',
 field=models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('waiting', '等待中'), ('interrupted', '已中断'), ('completed', '已完成'), ('error', '错误')], db_index=True, default='pending', max_length=20),
 ),
 ]
