# Generated by Django 6.0.1 on 2026-05-27 07:54
#
# review review round Fix #1（commit history reference）：
# 修复 Phase（commit 83218e04）在 graph 加 WAITING_CLARIFICATION
# 状态但未同步登记到 OrchestrationRun.Phase 枚举的对接漏洞。详见
# project-docs/phases/work-item/work-item item-error.md。
#
# 改动：
# - Phase enum 新增 WAITING_CLARIFICATION = "waiting_clarification"
# - phase 字段 max_length 20 → 32（容纳 21 字符 + 未来扩展空间）
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('orchestration', '0002_add_interrupted_status'),
 ]
 operations = [
 migrations.AlterField(
 model_name='orchestrationrun',
 name='phase',
 field=models.CharField(choices=[('planning', '规划'), ('executing', '执行'), ('waiting', '等待'), ('waiting_clarification', '等待澄清'), ('finalizing', '收尾'), ('completed', '完成'), ('error', '错误')], default='planning', max_length=32),
 ),
 ]
