# Generated by Django 6.0.1 on 2026-02-08 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('work_item_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('error', 'Error'), ('max_iterations', 'Max Iterations Reached')], db_index=True, default='running', max_length=20)),
                ('messages', models.JSONField(default=list)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.CharField(blank=True, choices=[('', 'None'), ('user_question', 'Waiting for user response'), ('human_approval', 'Waiting for human approval'), ('external_action', 'Waiting for external action')], default='', max_length=50)),
                ('pending_tool_call', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(default=list)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('tool_call_id', models.CharField(max_length=64)),
                ('arguments', models.JSONField(default=dict)),
                ('result_success', models.BooleanField(default=False)),
                ('result_output', models.JSONField(blank=True, null=True)),
                ('result_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('duration_ms', models.IntegerField(default=0)),
                ('iteration', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='agents.agentsession')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['project', 'status'], name='agents_agen_project_8a78f4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['user', '-created_at'], name='agents_agen_user_id_2c2897_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['session', 'iteration'], name='agents_tool_session_712195_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['tool_name', '-started_at'], name='agents_tool_tool_na_e0358a_idx'),
        ),
    ]
