# Generated by Django 6.0.1 on 2026-02-08 18:05
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('agents', '0001_initial'),
 ]
 operations = [
 migrations.AddField(
 model_name='agentsession',
 name='temp_data',
 field=models.JSONField(blank=True, default=dict),
 ),
 ]
