# Generated by Django 6.0.1 on 2026-03-10 19:08
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('agents', '0002_agentsession_temp_data'),
 ('projects', '0004_project_default_model_project_default_provider_type'),
 migrations.swappable_dependency(settings.AUTH_USER_MODEL),
 ]
 operations = [
 migrations.AlterField(
 model_name='agentsession',
 name='project',
 field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='projects.project'),
 ),
 migrations.AlterField(
 model_name='agentsession',
 name='user',
 field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL),
 ),
 ]
