# Generated by Django 6.0.1 on 2026-06-17 07:59

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("actor_repr", models.CharField(blank=True, default="", max_length=255)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("target_type", models.CharField(blank=True, default="", max_length=64)),
                ("target_id", models.CharField(blank=True, default="", max_length=128)),
                ("target_repr", models.CharField(blank=True, default="", max_length=255)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, default="", max_length=32)),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "审计事件",
                "verbose_name_plural": "审计事件",
                "db_table": "audit_event",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["action"], name="audit_event_action_21cdc5_idx"),
                    models.Index(
                        fields=["target_type", "target_id"], name="audit_event_target__92b051_idx"
                    ),
                    models.Index(fields=["actor_id"], name="audit_event_actor_i_24e8b4_idx"),
                    models.Index(fields=["occurred_at"], name="audit_event_occurre_bdc3f5_idx"),
                    models.Index(
                        fields=["action", "occurred_at"], name="audit_event_action_01e02e_idx"
                    ),
                ],
            },
        ),
    ]
