# Generated by Django 6.0.1 on 2026-05-14 04:44

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0021_add_indexed_files_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_chunk_id', models.UUIDField()),
                ('target_chunk_id', models.UUIDField()),
                ('edge_type', models.CharField(choices=[('CALL', 'Call'), ('IMPORT', 'Import'), ('SAME_FILE', 'Same File'), ('TEST_OF', 'Test Of'), ('CO_CHANGED', 'Co-Changed'), ('SEMANTIC', 'Semantic')], max_length=20)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_edges', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Chunk 边',
                'verbose_name_plural': 'Chunk 边',
                'indexes': [models.Index(fields=['target_chunk_id'], name='idx_chunkedge_target'), models.Index(fields=['repository', 'source_chunk_id'], name='idx_chunkedge_fanout'), models.Index(fields=['repository', 'edge_type', '-weight'], name='idx_chunkedge_topk')],
                'constraints': [models.UniqueConstraint(fields=('source_chunk_id', 'target_chunk_id', 'edge_type'), name='uniq_chunkedge_triple'), models.CheckConstraint(condition=models.Q(('weight__gte', 0.0), ('weight__lte', 1.0)), name='chunkedge_weight_range')],
            },
        ),
        migrations.CreateModel(
            name='ChunkRegistry',
            fields=[
                ('chunk_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(help_text='sha256 hex of chunk content', max_length=64)),
                ('file_path', models.CharField(max_length=512)),
                ('chunk_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_registry_entries', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Chunk 注册表',
                'verbose_name_plural': 'Chunk 注册表',
                'indexes': [models.Index(fields=['repository', 'file_path'], name='idx_chunk_reg_repo_file')],
            },
        ),
    ]
