# Generated by Django 6.0.1 on 2026-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_relations', '0001_initial'),
        ('repositories', '0021_add_indexed_files_progress'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chunkedge',
            constraint=models.CheckConstraint(condition=models.Q(('edge_type__in', ['CALL', 'IMPORT', 'SAME_FILE', 'TEST_OF', 'CO_CHANGED', 'SEMANTIC'])), name='chunkedge_edge_type_valid'),
        ),
    ]
