# Generated by Django 6.0.1 on 2026-05-14 07:19
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('code_relations', '0002_add_edge_type_check'),
 ]
 operations = [
 migrations.AddField(
 model_name='chunkregistry',
 name='line_end',
 field=models.PositiveIntegerField(blank=True, null=True),
 ),
 migrations.AddField(
 model_name='chunkregistry',
 name='line_start',
 field=models.PositiveIntegerField(blank=True, null=True),
 ),
 ]
