# Generated by Django 6.0.1 on 2026-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_relations', '0003_chunkregistry_line_fields'),
        ('repositories', '0021_add_indexed_files_progress'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chunkregistry',
            constraint=models.CheckConstraint(condition=models.Q(('line_start__isnull', True), ('line_end__isnull', True), ('line_end__gte', models.F('line_start')), _connector='OR'), name='chunkreg_line_range_valid'),
        ),
    ]
