# Generated by Django 6.0.1 on 2026-05-14 11:25
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('code_relations', '0004_chunkregistry_chunkreg_line_range_valid'),
 ]
 operations = [
 migrations.AddField(
 model_name='chunkregistry',
 name='last_built_at',
 field=models.DateTimeField(blank=True, db_index=True, help_text='最近一次 rebuild_chunk_edges 完成时间；NULL 表示未 backfill（Phase）', null=True),
 ),
 ]
