# Generated by Django 6.0.1 on 2026-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_relations', '0008_add_api_calls_edge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedge',
            name='target_repository_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='跨仓边的 target chunk 所在仓库 ID（initial implementation）。单仓边（v24 既有 6 类边）为 NULL——backward compatible。不做 ForeignKey（per contract 柔性引用原则）；与 Repository.id UUID 类型对齐。', null=True),
        ),
    ]
