# Generated by Django 6.0.1 on 2026-05-31 14:26
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('code_relations', '0009_alter_chunkedge_target_repository_id'),
 ]
 operations = [
 migrations.AddField(
 model_name='chunkedge',
 name='branch_name',
 field=models.CharField(blank=True, default='', max_length=200),
 ),
 migrations.AddField(
 model_name='chunkregistry',
 name='branch_name',
 field=models.CharField(blank=True, default='', max_length=200),
 ),
 ]
