# Generated by Django 6.0.1 on 2026-05-31 16:12
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('code_relations', '0010_add_branch_name'),
 ('repositories', '0026_repository_graph_build_progress'),
 ]
 operations = [
 migrations.RemoveConstraint(
 model_name='chunkedge',
 name='uniq_chunkedge_triple',
 ),
 migrations.AddIndex(
 model_name='chunkedge',
 index=models.Index(fields=['repository', 'branch_name', 'source_chunk_id'], name='idx_chunkedge_branch_fanout'),
 ),
 migrations.AddIndex(
 model_name='chunkregistry',
 index=models.Index(fields=['repository', 'branch_name', 'file_path'], name='idx_chunkreg_repo_branch_file'),
 ),
 migrations.AddConstraint(
 model_name='chunkedge',
 constraint=models.UniqueConstraint(fields=('source_chunk_id', 'target_chunk_id', 'edge_type', 'branch_name'), name='uniq_chunkedge_triple'),
 ),
 ]
