# Generated by Django 6.0.1 on 2026-06-17 17:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumableTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('index', '索引构建'), ('graph', '图谱构建'), ('workflow', '工作流执行'), ('chat', 'AI 对话')], max_length=20)),
                ('target_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=200)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '可恢复任务',
                'verbose_name_plural': '可恢复任务',
                'db_table': 'resumable_tasks',
                'indexes': [models.Index(fields=['status', 'lease_expires_at'], name='idx_resumable_status_lease')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'target_id'), name='uq_resumable_kind_target')],
            },
        ),
    ]
