# Generated by Django 6.0.1 on 2026-06-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumabletask',
            name='legacy_durable_job_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumabletask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('migrated', '已迁移至 durable')], default='pending', max_length=20),
        ),
    ]
