# Generated by Django 6.0.1 on 2026-01-21 07:44
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('projects', '0001_initial'),
 ('repositories', '0001_initial'),
 ]
 operations = [
 migrations.CreateModel(
 name='Task',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('work_item_id', models.CharField(max_length=100, unique=True)),
 ('feature_id', models.CharField(blank=True, max_length=100, null=True)),
 ('title', models.CharField(max_length=500)),
 ('description', models.TextField(blank=True, null=True)),
 ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
 ('commit_sha', models.CharField(blank=True, max_length=40, null=True)),
 ('pr_url', models.CharField(blank=True, max_length=500, null=True)),
 ('session_id', models.CharField(blank=True, max_length=100, null=True)),
 ('plan_output', models.TextField(blank=True, null=True)),
 ('status', models.CharField(choices=[('pending', '待处理'), ('planning', '规划中'), ('plan_review', '方案评审'), ('executing', '执行中'), ('code_review', '代码评审'), ('merged', '已合并'), ('failed', '失败')], default='pending', max_length=20)),
 ('human_feedback', models.TextField(blank=True, null=True)),
 ('error_message', models.TextField(blank=True, null=True)),
 ('retry_count', models.IntegerField(default=0)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('plan_started_at', models.DateTimeField(blank=True, null=True)),
 ('plan_completed_at', models.DateTimeField(blank=True, null=True)),
 ('execute_started_at', models.DateTimeField(blank=True, null=True)),
 ('execute_completed_at', models.DateTimeField(blank=True, null=True)),
 ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
 ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='repositories.repository')),
 ],
 options={
 'verbose_name': '任务',
 'verbose_name_plural': '任务',
 'db_table': 'tasks',
 'ordering': ['-created_at'],
 },
 ),
 ]
