# Generated by Django 6.0.1 on 2026-01-21 07:44
import uuid
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ("projects", "0001_initial"),
 ]
 operations = [
 migrations.CreateModel(
 name="TriggerLog",
 fields=[
 (
 "id",
 models.UUIDField(
 default=uuid.uuid4, editable=False, primary_key=True, serialize=False
 ),
 ),
 ("project_key", models.CharField(blank=True, max_length=100, null=True)),
 (
 "event_uuid",
 models.CharField(blank=True, max_length=100, null=True, unique=True),
 ),
 ("event_type", models.CharField(blank=True, default="", max_length=100)),
 ("webhook_raw_request", models.TextField(blank=True, default="")),
 ("work_item_id", models.CharField(blank=True, max_length=50, null=True)),
 ("work_item_type", models.CharField(blank=True, default="", max_length=50)),
 ("work_item_name", models.CharField(blank=True, default="", max_length=500)),
 ("work_item_raw_response", models.TextField(blank=True, default="")),
 ("prd_url", models.URLField(blank=True, default="", max_length=1000)),
 ("description", models.TextField(blank=True, default="")),
 ("tech_doc_url", models.URLField(blank=True, default="", max_length=1000)),
 (
 "status",
 models.CharField(
 choices=[
 ("accepted", "已接受"),
 ("ignored", "已忽略"),
 ("error", "错误"),
 ("duplicate", "重复"),
 ],
 default="accepted",
 max_length=20,
 ),
 ),
 ("error_message", models.TextField(blank=True, null=True)),
 ("created_at", models.DateTimeField(auto_now_add=True)),
 (
 "project",
 models.ForeignKey(
 blank=True,
 null=True,
 on_delete=django.db.models.deletion.SET_NULL,
 related_name="trigger_logs",
 to="projects.project",
 ),
 ),
 ],
 options={
 "verbose_name": "触发日志",
 "verbose_name_plural": "触发日志",
 "db_table": "trigger_logs",
 "ordering": ["-created_at"],
 },
 ),
 ]
