# Generated by Django 6.0.1 on 2026-03-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_model'),
        ('feishu', '0001_initial'),
        ('projects', '0003_add_claude_default_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuBotThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('active', '进行中'), ('awaiting_project_clarification', '待澄清项目'), ('awaiting_topic_clarification', '待澄清话题'), ('closed', '已关闭')], default='active', max_length=40)),
                ('root_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_user_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_bot_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_processing_card_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_bot_threads', to='chat.conversation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_bot_threads', to='projects.project')),
            ],
            options={
                'db_table': 'feishu_bot_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeishuBotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('chat_id', models.CharField(db_index=True, max_length=128)),
                ('sender_open_id', models.CharField(blank=True, default='', max_length=128)),
                ('message_type', models.CharField(max_length=32)),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('quote_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('mentioned_bot', models.BooleanField(default=False)),
                ('processing_card_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='feishu.feishubotthread')),
            ],
            options={
                'db_table': 'feishu_bot_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feishubotthread',
            index=models.Index(fields=['chat_id', '-updated_at'], name='feishu_bot__chat_id_e5af0e_idx'),
        ),
        migrations.AddIndex(
            model_name='feishubotmessage',
            index=models.Index(fields=['chat_id', '-created_at'], name='feishu_bot__chat_id_5bc0af_idx'),
        ),
    ]
