# Generated by Django 6.0.1 on 2026-03-16 10:37
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('feishu', '0002_feishubotthread_feishubotmessage_and_more'),
 ]
 operations = [
 migrations.CreateModel(
 name='ProcessedEvent',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ],
 options={
 'verbose_name': '已处理事件',
 'verbose_name_plural': '已处理事件',
 'db_table': 'feishu_processed_events',
 },
 ),
 ]
