# Generated by Django 6.0.1 on 2026-04-10 03:20
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('feishu', '0003_processedevent'),
 ]
 operations = [
 migrations.AddField(
 model_name='feishubotmessage',
 name='chat_type',
 field=models.CharField(blank=True, default='group', max_length=16),
 ),
 ]
