# Generated by Django 6.0.1 on 2026-06-25 15:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0006_alter_feishubotthread_space_alter_triggerlog_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuUserBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feishu_user_key', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='飞书 user_key')),
                ('open_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='飞书 open_id')),
                ('source', models.CharField(choices=[('manual', '手动绑定'), ('jit', '飞书事件自动绑定')], default='manual', max_length=20, verbose_name='绑定来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_bindings', to=settings.AUTH_USER_MODEL, verbose_name='Friday 用户')),
            ],
            options={
                'verbose_name': '飞书人员绑定',
                'verbose_name_plural': '飞书人员绑定',
                'db_table': 'feishu_user_bindings',
                'indexes': [models.Index(fields=['feishu_user_key'], name='feishu_user_feishu__e6260a_idx'), models.Index(fields=['open_id'], name='feishu_user_open_id_fc2ca0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('feishu_user_key', ''), _negated=True), fields=('feishu_user_key', 'user'), name='uniq_feishu_user_key_binding'), models.UniqueConstraint(condition=models.Q(('open_id', ''), _negated=True), fields=('open_id', 'user'), name='uniq_feishu_open_id_binding')],
            },
        ),
    ]
