# Generated by Django 6.0.1 on 2026-06-04 13:07
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('interactions', '0002_retrievaltrace'),
 ('repositories', '0028_indexhistory_per_run_delta'),
 ]
 operations = [
 migrations.CreateModel(
 name='McpRepositoryAnalysis',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('branch', models.CharField(blank=True, default='', max_length=200)),
 ('focus', models.TextField(blank=True, default='')),
 ('status', models.CharField(choices=[('completed', '已完成'), ('error', '错误')], db_index=True, default='completed', max_length=20)),
 ('summary', models.JSONField(blank=True, default=dict)),
 ('evidence', models.JSONField(blank=True, default=list)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_repository_analyses', to='repositories.repository')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_repository_analyses', to='interactions.interactionrun')),
 ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
 ],
 options={
 'db_table': 'mcp_repository_analyses',
 'ordering': ['-created_at'],
 },
 ),
 migrations.CreateModel(
 name='McpCodingPlan',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('branch', models.CharField(blank=True, default='', max_length=200)),
 ('requirement', models.TextField),
 ('title', models.CharField(max_length=240)),
 ('current_version', models.PositiveIntegerField(default=1)),
 ('status', models.CharField(choices=[('draft', '草稿'), ('superseded', '已替换'), ('executing', '执行中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='draft', max_length=20)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_coding_plans', to='repositories.repository')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_coding_plans', to='interactions.interactionrun')),
 ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_plans', to='mcp_tools.mcprepositoryanalysis')),
 ],
 options={
 'db_table': 'mcp_coding_plans',
 'ordering': ['-created_at'],
 },
 ),
 migrations.CreateModel(
 name='McpCodingPlanVersion',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('version', models.PositiveIntegerField),
 ('plan_body', models.JSONField(blank=True, default=dict)),
 ('affected_files', models.JSONField(blank=True, default=list)),
 ('steps', models.JSONField(blank=True, default=list)),
 ('test_plan', models.JSONField(blank=True, default=list)),
 ('risks', models.JSONField(blank=True, default=list)),
 ('evidence', models.JSONField(blank=True, default=list)),
 ('change_summary', models.TextField(blank=True, default='')),
 ('risk_delta', models.JSONField(blank=True, default=dict)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mcp_tools.mcpcodingplan')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_coding_plan_versions', to='interactions.interactionrun')),
 ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
 ],
 options={
 'db_table': 'mcp_coding_plan_versions',
 'ordering': ['plan', '-version'],
 'indexes': [models.Index(fields=['plan', '-version'], name='mcp_coding__plan_id_cbda19_idx'), models.Index(fields=['run'], name='mcp_coding__run_id_6d98b0_idx')],
 'constraints': [models.UniqueConstraint(fields=('plan', 'version'), name='uniq_mcp_plan_version')],
 },
 ),
 migrations.AddIndex(
 model_name='mcprepositoryanalysis',
 index=models.Index(fields=['repository', '-created_at'], name='mcp_reposit_reposit_47bf4b_idx'),
 ),
 migrations.AddIndex(
 model_name='mcprepositoryanalysis',
 index=models.Index(fields=['run'], name='mcp_reposit_run_id_e0d50d_idx'),
 ),
 migrations.AddIndex(
 model_name='mcpcodingplan',
 index=models.Index(fields=['repository', '-created_at'], name='mcp_coding__reposit_c91bde_idx'),
 ),
 migrations.AddIndex(
 model_name='mcpcodingplan',
 index=models.Index(fields=['run'], name='mcp_coding__run_id_8805c8_idx'),
 ),
 migrations.AddIndex(
 model_name='mcpcodingplan',
 index=models.Index(fields=['status'], name='mcp_coding__status_6b7ff8_idx'),
 ),
 ]
