# Generated by Django 6.0.1 on 2026-06-04 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_message_parts'),
        ('interactions', '0002_retrievaltrace'),
        ('mcp_tools', '0001_initial'),
        ('repositories', '0028_indexhistory_per_run_delta'),
        ('subagent', '0013_alter_tokenusage_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpCodingExecutionTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', '已排队'), ('dispatching', '分发中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='queued', max_length=20)),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('target_branch', models.CharField(blank=True, default='', max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=3600)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('dispatch_payload', models.JSONField(blank=True, default=dict)),
                ('runner_logs', models.JSONField(blank=True, default=list)),
                ('file_changes', models.JSONField(blank=True, default=list)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('push_result', models.JSONField(blank=True, default=dict)),
                ('last_diff', models.JSONField(blank=True, default=dict)),
                ('recovery_state', models.JSONField(blank=True, default=dict)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coding_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.codingsession')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_traces', to='mcp_tools.mcpcodingplan')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_traces', to='mcp_tools.mcpcodingplanversion')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_coding_execution_traces', to='repositories.repository')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='mcp_tools.mcpcodingexecutiontrace')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_coding_execution_traces', to='interactions.interactionrun')),
                ('subagent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subagent.subagentsession')),
                ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
            ],
            options={
                'db_table': 'mcp_coding_execution_traces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan', '-created_at'], name='mcp_coding__plan_id_0ccd38_idx'), models.Index(fields=['repository', '-created_at'], name='mcp_coding__reposit_f3accc_idx'), models.Index(fields=['run'], name='mcp_coding__run_id_f5ae7e_idx'), models.Index(fields=['status'], name='mcp_coding__status_b29316_idx')],
            },
        ),
    ]
