# Generated by Django 6.0.1 on 2026-06-04 13:18
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('mcp_tools', '0002_mcpcodingexecutiontrace'),
 ]
 operations = [
 migrations.AddField(
 model_name='mcpcodingexecutiontrace',
 name='branch_summary',
 field=models.JSONField(blank=True, default=dict),
 ),
 migrations.AddField(
 model_name='mcpcodingexecutiontrace',
 name='mr_result',
 field=models.JSONField(blank=True, default=dict),
 ),
 migrations.AlterField(
 model_name='mcpcodingexecutiontrace',
 name='status',
 field=models.CharField(choices=[('queued', '已排队'), ('dispatching', '分发中'), ('running', '执行中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败')], db_index=True, default='queued', max_length=20),
 ),
 ]
