# Generated by Django 6.0.1 on 2026-06-04 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_retrievaltrace'),
        ('mcp_tools', '0003_mcpcodingexecutiontrace_branch_summary_and_more'),
        ('projects', '0009_remove_v81_legacy_claude_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpWorkItemContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feishu_project_key', models.CharField(db_index=True, max_length=128)),
                ('work_item_type', models.CharField(db_index=True, max_length=80)),
                ('work_item_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('completed', '已完成'), ('partial', '部分完成'), ('error', '错误')], db_index=True, default='completed', max_length=20)),
                ('work_item_status', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('owners', models.JSONField(blank=True, default=list)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('relations', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_work_item_contexts', to='projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_work_item_contexts', to='interactions.interactionrun')),
                ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
            ],
            options={
                'db_table': 'mcp_work_item_contexts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feishu_project_key', 'work_item_type', 'work_item_id'], name='mcp_work_it_feishu__c4c067_idx'), models.Index(fields=['run'], name='mcp_work_it_run_id_56c381_idx'), models.Index(fields=['status'], name='mcp_work_it_status_ca2c2c_idx'), models.Index(fields=['project', '-created_at'], name='mcp_work_it_project_372e56_idx')],
            },
        ),
    ]
