# Generated by Django 6.0.1 on 2026-06-04 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_retrievaltrace'),
        ('mcp_tools', '0004_mcpworkitemcontext'),
        ('projects', '0009_remove_v81_legacy_claude_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpWorkItemTechnicalPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feishu_project_key', models.CharField(db_index=True, max_length=128)),
                ('work_item_type', models.CharField(db_index=True, max_length=80)),
                ('work_item_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败')], db_index=True, default='completed', max_length=20)),
                ('plan_body', models.JSONField(blank=True, default=dict)),
                ('markdown', models.TextField(blank=True, default='')),
                ('repository_tasks', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('similar_cases', models.JSONField(blank=True, default=list)),
                ('feishu_document_id', models.CharField(blank=True, default='', max_length=128)),
                ('feishu_document_url', models.CharField(blank=True, default='', max_length=500)),
                ('comment_result', models.JSONField(blank=True, default=dict)),
                ('retry_state', models.JSONField(blank=True, default=dict)),
                ('error_stage', models.CharField(blank=True, default='', max_length=80)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_plans', to='mcp_tools.mcpworkitemcontext')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_work_item_technical_plans', to='projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_work_item_technical_plans', to='interactions.interactionrun')),
                ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
            ],
            options={
                'db_table': 'mcp_work_item_technical_plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['context', '-created_at'], name='mcp_work_it_context_833f87_idx'), models.Index(fields=['feishu_project_key', 'work_item_type', 'work_item_id'], name='mcp_work_it_feishu__87fa65_idx'), models.Index(fields=['run'], name='mcp_work_it_run_id_f0f8f3_idx'), models.Index(fields=['status'], name='mcp_work_it_status_1f777e_idx'), models.Index(fields=['project', '-created_at'], name='mcp_work_it_project_59ee4c_idx')],
            },
        ),
    ]
