# Generated by Django 6.0.1 on 2026-06-04 15:08
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('interactions', '0002_retrievaltrace'),
 ('mcp_tools', '0005_mcpworkitemtechnicalplan'),
 ('repositories', '0028_indexhistory_per_run_delta'),
 ]
 operations = [
 migrations.CreateModel(
 name='McpWorkItemRepoTask',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('order', models.PositiveIntegerField(default=1)),
 ('status', models.CharField(choices=[('pending', '待执行'), ('planned', '已生成编码方案'), ('running', '执行中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
 ('branch_name', models.CharField(blank=True, default='', max_length=255)),
 ('target_branch', models.CharField(blank=True, default='', max_length=255)),
 ('task_body', models.JSONField(blank=True, default=dict)),
 ('result', models.JSONField(blank=True, default=dict)),
 ('recovery_state', models.JSONField(blank=True, default=dict)),
 ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
 ('mr_url', models.CharField(blank=True, default='', max_length=500)),
 ('error', models.TextField(blank=True, default='')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('coding_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_repo_tasks', to='mcp_tools.mcpcodingplan')),
 ('execution_trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_repo_tasks', to='mcp_tools.mcpcodingexecutiontrace')),
 ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_repo_tasks', to='mcp_tools.mcpcodingplanversion')),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_work_item_repo_tasks', to='repositories.repository')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_work_item_repo_tasks', to='interactions.interactionrun')),
 ('technical_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_tasks', to='mcp_tools.mcpworkitemtechnicalplan')),
 ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
 ],
 options={
 'db_table': 'mcp_work_item_repo_tasks',
 'ordering': ['technical_plan', 'order'],
 'indexes': [models.Index(fields=['technical_plan', 'order'], name='mcp_work_it_technic_ff769e_idx'), models.Index(fields=['repository', '-created_at'], name='mcp_work_it_reposit_7f8a47_idx'), models.Index(fields=['run'], name='mcp_work_it_run_id_90acb4_idx'), models.Index(fields=['status'], name='mcp_work_it_status_573db1_idx')],
 'constraints': [models.UniqueConstraint(fields=('technical_plan', 'order'), name='uniq_work_item_repo_task_order')],
 },
 ),
 ]
