# Generated by Django 6.0.1 on 2026-06-04 15:11
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('interactions', '0002_retrievaltrace'),
 ('mcp_tools', '0006_mcpworkitemrepotask'),
 ]
 operations = [
 migrations.CreateModel(
 name='McpLearningCase',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('work_item_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
 ('work_item_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
 ('title', models.CharField(max_length=240)),
 ('problem', models.TextField(blank=True, default='')),
 ('root_cause', models.TextField(blank=True, default='')),
 ('solution', models.TextField(blank=True, default='')),
 ('outcome', models.CharField(blank=True, db_index=True, default='', max_length=80)),
 ('repositories', models.JSONField(blank=True, default=list)),
 ('files', models.JSONField(blank=True, default=list)),
 ('symbols', models.JSONField(blank=True, default=list)),
 ('branches', models.JSONField(blank=True, default=list)),
 ('mr_urls', models.JSONField(blank=True, default=list)),
 ('tests', models.JSONField(blank=True, default=list)),
 ('source_links', models.JSONField(blank=True, default=dict)),
 ('case_body', models.JSONField(blank=True, default=dict)),
 ('embedding_text', models.TextField(blank=True, default='')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_cases', to='mcp_tools.mcpworkitemcontext')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_learning_cases', to='interactions.interactionrun')),
 ('technical_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_cases', to='mcp_tools.mcpworkitemtechnicalplan')),
 ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
 ],
 options={
 'db_table': 'mcp_learning_cases',
 'ordering': ['-created_at'],
 'indexes': [models.Index(fields=['work_item_type', '-created_at'], name='mcp_learnin_work_it_fb904b_idx'), models.Index(fields=['outcome', '-created_at'], name='mcp_learnin_outcome_d87b69_idx'), models.Index(fields=['run'], name='mcp_learnin_run_id_214b88_idx')],
 },
 ),
 ]
