# Generated by Django 6.0.1 on 2026-06-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_tools', '0007_mcplearningcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpworkitemtechnicalplan',
            name='canonical_plan_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='canonical delivery.TechnicalPlan.id 软链，非 FK（DOMAIN §5.2）', null=True, verbose_name='canonical 方案软链'),
        ),
    ]
