# Generated by Django 6.0.1 on 2026-06-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_tools', '0009_rename_project_to_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcpworkitemtechnicalplan',
            name='canonical_plan_id',
        ),
    ]
