# Generated by Django 6.0.1 on 2026-07-15 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_modelusage_retrievaltrace_metrics'),
        ('mcp_tools', '0010_remove_mcpworkitemtechnicalplan_canonical_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcplearningcase',
            name='source_session_id',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mcplearningcase',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_learning_cases', to='interactions.interactionrun'),
        ),
    ]
