# Generated by Django 6.0.1 on 2026-01-21 07:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("git_url", models.CharField(max_length=500)),
                (
                    "git_platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("gitea", "Gitea"),
                            ("bitbucket", "Bitbucket"),
                        ],
                        default="github",
                        max_length=20,
                    ),
                ),
                ("default_branch", models.CharField(default="main", max_length=100)),
                ("claude_md_path", models.CharField(default="project instructions", max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
                "db_table": "repositories",
            },
        ),
        migrations.CreateModel(
            name="GitCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("ssh_key", "SSH Key"),
                            ("access_token", "Access Token"),
                            ("deploy_key", "Deploy Key"),
                        ],
                        default="access_token",
                        max_length=20,
                    ),
                ),
                ("ssh_key_encrypted", models.TextField(blank=True, null=True)),
                ("encrypted_token", models.TextField(blank=True, null=True)),
                (
                    "git_user_name",
                    models.CharField(default="Friday Codes AI Agent", max_length=200),
                ),
                ("git_user_email", models.CharField(default="ai@friday.codes", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Git 凭证",
                "verbose_name_plural": "Git 凭证",
                "db_table": "git_credentials",
            },
        ),
    ]
