# Generated by Django 6.0.1 on 2026-01-21 16:47
from django.db import migrations
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0001_initial'),
 ]
 operations = [
 migrations.RemoveField(
 model_name='repository',
 name='claude_md_path',
 ),
 ]
