# Generated by Django 6.0.1 on 2026-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repositories", "0004_repository_proxy_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="index_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="index_status",
            field=models.CharField(
                choices=[
                    ("not_indexed", "未索引"),
                    ("indexing", "索引中"),
                    ("indexed", "已索引"),
                    ("failed", "索引失败"),
                ],
                default="not_indexed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
