# Generated by Django 6.0.1 on 2026-02-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_repository_deleted_at_repository_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='index_write_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='index_write_total',
            field=models.IntegerField(default=0),
        ),
    ]
