# Generated by Django 6.0.1 on 2026-03-13 03:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0008_repository_index_write_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='auto_index_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_indexed_commit_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='IndexHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('webhook', 'Webhook 触发'), ('scheduled', '定时触发')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('from_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('to_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('files_added', models.IntegerField(default=0)),
                ('files_modified', models.IntegerField(default=0)),
                ('files_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_history', to='repositories.repository')),
            ],
            options={
                'verbose_name': '索引历史',
                'verbose_name_plural': '索引历史',
                'db_table': 'index_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
