# Generated by Django 6.0.1 on 2026-03-13 05:29
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0009_repository_new_fields_and_index_history'),
 ]
 operations = [
 migrations.AddField(
 model_name='indexhistory',
 name='summary_text',
 field=models.TextField(blank=True, help_text='人可读的差异摘要文本', null=True),
 ),
 ]
