# Generated by Django 6.0.1 on 2026-03-17 06:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0010_indexhistory_summary_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_hash', models.CharField(max_length=64)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_indexes', to='repositories.repository')),
            ],
            options={
                'verbose_name': '文件索引记录',
                'verbose_name_plural': '文件索引记录',
                'db_table': 'file_indexes',
                'constraints': [models.UniqueConstraint(fields=('repository', 'file_path'), name='uq_repo_file_path')],
            },
        ),
    ]
