# Generated by Django 6.0.1 on 2026-04-12 08:06
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0011_add_file_index_model'),
 ]
 operations = [
 migrations.AddField(
 model_name='repository',
 name='ai_summary',
 field=models.TextField(blank=True, null=True),
 ),
 migrations.AddField(
 model_name='repository',
 name='ai_summary_error',
 field=models.TextField(blank=True, default=''),
 ),
 migrations.AddField(
 model_name='repository',
 name='ai_summary_generated_at',
 field=models.DateTimeField(blank=True, null=True),
 ),
 migrations.AddField(
 model_name='repository',
 name='ai_summary_status',
 field=models.CharField(choices=[('not_started', '未生成'), ('pending', '等待中'), ('running', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='not_started', max_length=20),
 ),
 ]
