# Generated by Django 6.0.1 on 2026-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0012_repository_ai_summary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='base_branch',
            field=models.CharField(blank=True, help_text='索引基础分支，为空时回退到 default_branch', max_length=100, null=True),
        ),
    ]
