# Generated by Django 6.0.1 on 2026-04-13 08:32
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0013_repository_base_branch'),
 ]
 operations = [
 migrations.CreateModel(
 name='RepositoryBranchIndex',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('branch_name', models.CharField(max_length=200)),
 ('is_base_branch', models.BooleanField(default=False)),
 ('head_sha', models.CharField(blank=True, max_length=40, null=True)),
 ('merge_base_sha', models.CharField(blank=True, max_length=40, null=True)),
 ('last_indexed_commit_sha', models.CharField(blank=True, max_length=40, null=True)),
 ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
 ('is_stale', models.BooleanField(default=False)),
 ('status', models.CharField(choices=[('not_indexed', '未索引'), ('indexing', '索引中'), ('indexed', '已索引'), ('inherited', '继承自基础分支'), ('failed', '索引失败')], default='not_indexed', max_length=20)),
 ('effective_chunks_count', models.IntegerField(default=0)),
 ('collection_name', models.CharField(blank=True, max_length=300, null=True)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_indexes', to='repositories.repository')),
 ],
 options={
 'verbose_name': '分支索引',
 'verbose_name_plural': '分支索引',
 'db_table': 'repository_branch_indexes',
 },
 ),
 migrations.CreateModel(
 name='BranchFileIndex',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('file_path', models.CharField(max_length=1000)),
 ('change_type', models.CharField(max_length=20)),
 ('indexed_at', models.DateTimeField(auto_now=True)),
 ('branch_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_indexes', to='repositories.repositorybranchindex')),
 ],
 options={
 'verbose_name': '分支文件索引',
 'verbose_name_plural': '分支文件索引',
 'db_table': 'branch_file_indexes',
 },
 ),
 migrations.AddConstraint(
 model_name='repositorybranchindex',
 constraint=models.UniqueConstraint(fields=('repository', 'branch_name'), name='uq_repo_branch'),
 ),
 migrations.AddConstraint(
 model_name='branchfileindex',
 constraint=models.UniqueConstraint(fields=('branch_index', 'file_path'), name='uq_branch_file'),
 ),
 ]
