# Generated by Django 6.0.1 on 2026-04-14 03:32
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0014_branch_index_models'),
 ]
 operations = [
 migrations.AlterField(
 model_name='repositorybranchindex',
 name='status',
 field=models.CharField(choices=[('not_indexed', '未索引'), ('indexing', '索引中'), ('indexed', '已索引'), ('inherited', '继承自基础分支'), ('failed', '索引失败'), ('upgrading', '升级中')], default='not_indexed', max_length=20),
 ),
 ]
