# Generated by Django 6.0.1 on 2026-05-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0018_repository_behind_commits_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='index_stage',
            field=models.CharField(blank=True, default='', help_text='索引当前阶段，由 indexer 各阶段开始时 update', max_length=64),
        ),
    ]
