# Generated by Django 6.0.1 on 2026-05-12 16:46
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0020_add_cancelled_index_status'),
 ]
 operations = [
 migrations.AddField(
 model_name='fileindex',
 name='last_commit_authored_at',
 field=models.DateTimeField(blank=True, null=True),
 ),
 migrations.AddField(
 model_name='fileindex',
 name='last_commit_sha',
 field=models.CharField(blank=True, default='', max_length=40),
 ),
 migrations.AddField(
 model_name='repository',
 name='current_indexing_file',
 field=models.CharField(blank=True, default='', help_text='当前正在索引的文件相对路径，空字符串表示无活动文件', max_length=1000),
 ),
 migrations.AddField(
 model_name='repository',
 name='indexed_files_processed',
 field=models.IntegerField(default=0, help_text='本次索引已处理的文件数（accumulated counter）'),
 ),
 migrations.AddField(
 model_name='repository',
 name='indexed_files_total',
 field=models.IntegerField(default=0, help_text='本次索引预计要处理的文件总数（解析阶段确定后写入）'),
 ),
 migrations.AddIndex(
 model_name='fileindex',
 index=models.Index(fields=['repository', 'file_path'], name='idx_repo_file_path'),
 ),
 ]
