# Generated by Django 6.0.1 on 2026-05-14 09:19
# initial implementation plan：IndexHistory 增加 GraphRAG 构建三件套字段。
# - graph_build_status: GraphBuildStatus TextChoices（pending/running/completed/failed/skipped）
# - edge_count: 累计快照 ChunkEdge 行数
# - payload_synced_at: 最近一次 batch_set_payload 完成时间

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0021_add_indexed_files_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexhistory',
            name='edge_count',
            field=models.PositiveIntegerField(default=0, help_text='累计快照：当前 ChunkEdge.objects.filter(repository=repo).count()'),
        ),
        migrations.AddField(
            model_name='indexhistory',
            name='graph_build_status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', help_text='GraphRAG 增量构建状态（pending/running/completed/failed/skipped）', max_length=20),
        ),
        migrations.AddField(
            model_name='indexhistory',
            name='payload_synced_at',
            field=models.DateTimeField(blank=True, help_text='最近一次 payload.related_chunks 同步完成时间', null=True),
        ),
    ]
