# Generated by Django 6.0.1 on 2026-05-18 05:59
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0023_indexhistory_cross_repo_fields'),
 ]
 operations = [
 migrations.AddField(
 model_name='repository',
 name='auto_build_graph_enabled',
 field=models.BooleanField(default=True, help_text='是否自动构建图谱（per-repo 开关，AND settings.ENABLE_CODEGRAPH 决定是否跳过）'),
 ),
 ]
