# Generated by Django 6.0.1 on 2026-05-18 07:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0024_repository_auto_build_graph_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphBuildHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('auto_after_index', '索引完成自动触发'), ('webhook', 'Webhook 触发')], max_length=20)),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已停止')], default='running', help_text='创建即 RUNNING——CONTEXT 决议不引入 pending 态', max_length=20)),
                ('files_total', models.IntegerField(default=0)),
                ('files_processed', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('symbols_count', models.IntegerField(default=0)),
                ('imports_count', models.IntegerField(default=0)),
                ('calls_count', models.IntegerField(default=0)),
                ('endpoints_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_build_histories', to='repositories.repository')),
            ],
            options={
                'verbose_name': '图谱构建历史',
                'verbose_name_plural': '图谱构建历史',
                'db_table': 'graph_build_history',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['repository', '-started_at'], name='idx_gbh_repo_started')],
            },
        ),
    ]
