# Generated by Django 6.0.1 on 2026-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0025_graph_build_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='current_graph_file',
            field=models.CharField(blank=True, default='', help_text='当前正在抽取的文件相对路径，空字符串表示无活动文件', max_length=1000),
        ),
        migrations.AddField(
            model_name='repository',
            name='graph_build_status',
            field=models.CharField(choices=[('idle', '未构建'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已停止')], default='idle', help_text='图谱当前态（initial implementation-01）', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='graph_files_processed',
            field=models.IntegerField(default=0, help_text='本次图谱构建已处理的文件数'),
        ),
        migrations.AddField(
            model_name='repository',
            name='graph_files_total',
            field=models.IntegerField(default=0, help_text='本次图谱构建预计处理的文件总数'),
        ),
        migrations.AddField(
            model_name='repository',
            name='graph_last_built_at',
            field=models.DateTimeField(blank=True, help_text='最近一次终态（COMPLETED/FAILED/CANCELLED）时间戳', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='graph_stage',
            field=models.CharField(blank=True, default='', help_text='图谱构建当前阶段，由 update_graph_progress 实时刷新', max_length=64),
        ),
    ]
