# Generated by Django 6.0.1 on 2026-06-01 04:57
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0026_repository_graph_build_progress'),
 ]
 operations = [
 migrations.AddField(
 model_name='graphbuildhistory',
 name='branch_name',
 field=models.CharField(blank=True, default='', max_length=200),
 ),
 ]
