# Generated by Django 6.0.1 on 2026-06-01 06:51
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('repositories', '0027_graphbuildhistory_branch_name'),
 ]
 operations = [
 migrations.AddField(
 model_name='indexhistory',
 name='calls_added',
 field=models.IntegerField(default=0, help_text='本次索引写入/重建的 CallEdge 数（per-run，非累计）'),
 ),
 migrations.AddField(
 model_name='indexhistory',
 name='chunk_edges_added',
 field=models.IntegerField(default=0, help_text='本次索引净新增 ChunkEdge 数（per-run，去重后 inserted；区别于累计 edge_count）'),
 ),
 migrations.AddField(
 model_name='indexhistory',
 name='endpoints_added',
 field=models.IntegerField(default=0, help_text='本次索引写入/重建的 Endpoint 数（per-run，非累计）'),
 ),
 migrations.AddField(
 model_name='indexhistory',
 name='imports_added',
 field=models.IntegerField(default=0, help_text='本次索引写入/重建的 ImportEdge 数（per-run，非累计）'),
 ),
 migrations.AddField(
 model_name='indexhistory',
 name='lines_added',
 field=models.IntegerField(blank=True, default=None, help_text='本次增量 +行数；null=不可计算（全量索引/shallow 加深失败），0=无新增或二进制文件', null=True),
 ),
 migrations.AddField(
 model_name='indexhistory',
 name='lines_deleted',
 field=models.IntegerField(blank=True, default=None, help_text='本次增量 -行数；null=不可计算（全量索引/shallow 加深失败），0=无删除或二进制文件', null=True),
 ),
 migrations.AddField(
 model_name='indexhistory',
 name='symbols_added',
 field=models.IntegerField(default=0, help_text='本次索引写入/重建的 Symbol 数（per-run，非累计；增量重建文件含其既有符号，非去重净增）'),
 ),
 ]
