# Generated by Django 6.0.1 on 2026-06-12 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0028_indexhistory_per_run_delta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusTreeSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('tree', models.JSONField(default=list)),
                ('manual_overrides', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('built_by', models.CharField(default='llm_full', help_text='构建方式：llm_full（全量聚类）/ incremental（增量归类）/ manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '全局知识树快照',
                'verbose_name_plural': '全局知识树快照',
                'db_table': 'corpus_tree_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacetVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(help_text='分面维度标识，如 业务线 / 服务对象 / 技术形态', max_length=64, unique=True)),
                ('values', models.JSONField(default=list, help_text='该维度的合法取值列表（字符串数组）')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '分面词表',
                'verbose_name_plural': '分面词表',
                'db_table': 'facet_vocabularies',
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='ai_summary_tree',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='facets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_monorepo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='tree_stale_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
