# Generated by Django 6.0.1 on 2026-06-17 17:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0036_git_instance_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphFileIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_hash', models.CharField(max_length=64)),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_file_indexes', to='repositories.repository')),
            ],
            options={
                'verbose_name': '图谱文件断点',
                'verbose_name_plural': '图谱文件断点',
                'db_table': 'graph_file_indexes',
                'indexes': [models.Index(fields=['repository', 'branch_name'], name='idx_graph_repo_branch')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'branch_name', 'file_path'), name='uq_graph_repo_branch_file')],
            },
        ),
    ]
