# Generated by Django 6.0.1 on 2026-06-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0038_corpustreesnapshot_source_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='git_instance_credential',
            field=models.ForeignKey(blank=True, help_text='可选密钥提供方（实例池凭证）。无 per-repo token 时优先用本 FK 解析 token。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='repositories.gitinstancecredential'),
        ),
    ]
