# Generated by Django 6.0.1 on 2026-07-29 11:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repositories", "0039_repository_git_instance_credential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepoCharter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[("ai_draft", "AI 草案"), ("human_confirmed", "人工确认")],
                        default="ai_draft",
                        max_length=16,
                    ),
                ),
                ("positioning", models.TextField(blank=True, default="")),
                ("owned_domains", models.JSONField(blank=True, default=list)),
                ("boundaries", models.JSONField(blank=True, default=list)),
                ("placement_preferences", models.JSONField(blank=True, default=list)),
                ("audience", models.CharField(blank=True, default="", max_length=64)),
                ("form", models.CharField(blank=True, default="", max_length=64)),
                (
                    "evolution",
                    models.CharField(
                        choices=[
                            ("active", "活跃演进"),
                            ("maintenance_only", "仅维护"),
                            ("deprecated", "已废弃"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("draft_content", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charter",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库章程",
                "verbose_name_plural": "仓库章程",
                "db_table": "repo_charters",
            },
        ),
    ]
