# Generated by Django 6.0.1 on 2026-07-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0039_repository_git_instance_credential'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileindex',
            index=models.Index(fields=['repository', 'last_commit_authored_at'], name='idx_repo_last_commit_at'),
        ),
    ]
