# Generated by Django 6.0.1 on 2026-08-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0040_file_index_last_commit_index'),
        ('repositories', '0040_repo_charter'),
    ]

    operations = [
    ]
