# Generated by Django 6.0.1 on 2026-01-20 11:18
import django.db.models.deletion
import projects.models
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies =
 operations = [
 migrations.CreateModel(
 name='Project',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('name', models.CharField(max_length=200)),
 ('description', models.TextField(blank=True, null=True)),
 ('feishu_project_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
 ('feishu_plugin_id', models.CharField(blank=True, max_length=100, null=True)),
 ('feishu_plugin_secret_encrypted', models.TextField(blank=True, null=True)),
 ('feishu_webhook_token', models.CharField(default=projects.models.generate_webhook_token, max_length=32)),
 ('feishu_user_key', models.CharField(blank=True, max_length=100, null=True)),
 ('claude_api_key_encrypted', models.TextField(blank=True, null=True)),
 ('claude_base_url', models.CharField(blank=True, max_length=500, null=True)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ],
 options={
 'verbose_name': '项目',
 'verbose_name_plural': '项目',
 'db_table': 'projects',
 },
 ),
 migrations.CreateModel(
 name='Repository',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('name', models.CharField(max_length=200)),
 ('git_url', models.CharField(max_length=500)),
 ('git_platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('bitbucket', 'Bitbucket')], default='github', max_length=20)),
 ('default_branch', models.CharField(default='main', max_length=100)),
 ('claude_md_path', models.CharField(default='developer-notes.md', max_length=500)),
 ('description', models.TextField(blank=True, null=True)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ],
 options={
 'verbose_name': '仓库',
 'verbose_name_plural': '仓库',
 'db_table': 'repositories',
 },
 ),
 migrations.CreateModel(
 name='ProjectRepository',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.repository')),
 ],
 options={
 'db_table': 'project_repositories',
 'unique_together': {('project', 'repository')},
 },
 ),
 migrations.AddField(
 model_name='project',
 name='repositories',
 field=models.ManyToManyField(related_name='projects', through='projects.ProjectRepository', to='projects.repository'),
 ),
 migrations.CreateModel(
 name='GitCredential',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('auth_type', models.CharField(choices=[('ssh_key', 'SSH Key'), ('access_token', 'Access Token'), ('deploy_key', 'Deploy Key')], default='access_token', max_length=20)),
 ('ssh_key_encrypted', models.TextField(blank=True, null=True)),
 ('encrypted_token', models.TextField(blank=True, null=True)),
 ('git_user_name', models.CharField(default='Friday AI Agent', max_length=200)),
 ('git_user_email', models.CharField(default='ai-agent@friday.dev', max_length=200)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='projects.repository')),
 ],
 options={
 'verbose_name': 'Git 凭证',
 'verbose_name_plural': 'Git 凭证',
 'db_table': 'git_credentials',
 },
 ),
 ]
