# Generated by Django 6.0.1 on 2026-01-21 07:44
import django.db.models.deletion
import projects.models
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('repositories', '0001_initial'),
 ]
 operations = [
 migrations.CreateModel(
 name='Project',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('name', models.CharField(max_length=200)),
 ('description', models.TextField(blank=True, null=True)),
 ('feishu_project_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
 ('feishu_plugin_id', models.CharField(blank=True, max_length=100, null=True)),
 ('feishu_plugin_secret_encrypted', models.TextField(blank=True, null=True)),
 ('feishu_webhook_token', models.CharField(default=projects.models.generate_webhook_token, max_length=32)),
 ('feishu_user_key', models.CharField(blank=True, max_length=100, null=True)),
 ('claude_api_key_encrypted', models.TextField(blank=True, null=True)),
 ('claude_base_url', models.CharField(blank=True, max_length=500, null=True)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ],
 options={
 'verbose_name': '项目',
 'verbose_name_plural': '项目',
 'db_table': 'projects',
 },
 ),
 migrations.CreateModel(
 name='ProjectRepository',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repository')),
 ],
 options={
 'db_table': 'project_repositories',
 'unique_together': {('project', 'repository')},
 },
 ),
 migrations.AddField(
 model_name='project',
 name='repositories',
 field=models.ManyToManyField(related_name='projects', through='projects.ProjectRepository', to='repositories.repository'),
 ),
 ]
