# Generated by Django 6.0.1 on 2026-02-09 13:22
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('projects', '0001_initial'),
 ]
 operations = [
 migrations.AddField(
 model_name='project',
 name='feishu_app_id',
 field=models.CharField(blank=True, help_text='飞书自建应用 App ID (cli_xxx 格式)', max_length=100, null=True),
 ),
 migrations.AddField(
 model_name='project',
 name='feishu_app_secret_encrypted',
 field=models.TextField(blank=True, help_text='飞书自建应用 App Secret (加密存储)', null=True),
 ),
 ]
