# Generated by Django 6.0.1 on 2026-02-11 09:40
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('projects', '0002_add_feishu_im_app_fields'),
 ]
 operations = [
 migrations.AddField(
 model_name='project',
 name='claude_default_model',
 field=models.CharField(blank=True, max_length=200, null=True),
 ),
 ]
