# Generated by Django 6.0.1 on 2026-03-08 14:07
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('projects', '0003_add_claude_default_model'),
 ]
 operations = [
 migrations.AddField(
 model_name='project',
 name='default_model',
 field=models.CharField(blank=True, help_text='项目默认模型 ID，为空时使用 Provider 默认模型', max_length=200, null=True, verbose_name='默认模型'),
 ),
 migrations.AddField(
 model_name='project',
 name='default_provider_type',
 field=models.CharField(blank=True, help_text='项目默认 Provider，为空时使用系统级配置', max_length=50, null=True, verbose_name='默认 Provider 类型'),
 ),
 ]
