# Generated by Django 6.0.1 on 2026-03-15 03:52
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('projects', '0004_project_default_model_project_default_provider_type'),
 ]
 operations = [
 migrations.AddField(
 model_name='projectrepository',
 name='created_at',
 field=models.DateTimeField(auto_now_add=True, null=True),
 ),
 migrations.AddField(
 model_name='projectrepository',
 name='permission_level',
 field=models.CharField(choices=[('read_write', '读写'), ('read_only', '只读')], default='read_write', max_length=20, verbose_name='权限级别'),
 ),
 ]
