# Generated by Django 6.0.3 on 2026-04-07 16:29
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('projects', '0005_add_permission_level_to_project_repository'),
 ]
 operations = [
 migrations.AddField(
 model_name='project',
 name='feishu_doc_folder_token',
 field=models.CharField(blank=True, default='', help_text='飞书文档导出目标文件夹 token', max_length=200),
 ),
 ]
