# Generated by Django 6.0.1 on 2026-04-11 05:45
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('projects', '0006_add_feishu_doc_folder_token'),
 migrations.swappable_dependency(settings.AUTH_USER_MODEL),
 ]
 operations = [
 migrations.CreateModel(
 name='Prompt',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('slug', models.CharField(help_text="代码引用键，如 'chat.system.developer' / 'ai_node.code_review.system' / 'repo.summary_generator'", max_length=120)),
 ('category', models.CharField(choices=[('ai_node', 'AI 工作流节点'), ('chat_agent', '对话 Agent'), ('aux_model', '辅助小模型'), ('feishu_bot', '飞书群聊'), ('repo_summary', '仓库智能描述')], max_length=20)),
 ('scope', models.CharField(choices=[('system', '系统级'), ('project', '项目级')], max_length=10)),
 ('title', models.CharField(max_length=200)),
 ('description', models.TextField(blank=True, default='')),
 ('is_builtin', models.BooleanField(default=False, help_text='系统内置项（来自 data migration），禁止删除，只能编辑')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
 ('project', models.ForeignKey(blank=True, help_text='项目级覆盖时非空；系统级为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='projects.project')),
 ],
 options={
 'verbose_name': '提示词',
 'verbose_name_plural': '提示词',
 'db_table': 'prompts',
 },
 ),
 migrations.CreateModel(
 name='PromptVersion',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('version', models.PositiveIntegerField(help_text='自增版本号（每 prompt 从 1 开始）')),
 ('body', models.TextField(help_text='提示词正文，支持 {{variable}} 占位符（Jinja2 sandbox 渲染）')),
 ('variables_schema', models.JSONField(blank=True, default=dict, help_text="变量元数据：{'user_message': {'type':'str','required':True,'description':'...','default':''}}。注意这是元数据，与 body 实际 {{var}} 集合（运行时 regex 派生）可能不一致")),
 ('change_note', models.CharField(blank=True, default='', max_length=500)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
 ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompts.prompt')),
 ],
 options={
 'verbose_name': '提示词版本',
 'verbose_name_plural': '提示词版本',
 'db_table': 'prompt_versions',
 'ordering': ['-version'],
 },
 ),
 migrations.AddField(
 model_name='prompt',
 name='active_version',
 field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for', to='prompts.promptversion'),
 ),
 migrations.AddIndex(
 model_name='promptversion',
 index=models.Index(fields=['prompt', '-version'], name='prompt_vers_prompt__2c0766_idx'),
 ),
 migrations.AddConstraint(
 model_name='promptversion',
 constraint=models.UniqueConstraint(fields=('prompt', 'version'), name='uq_prompt_version'),
 ),
 migrations.AddIndex(
 model_name='prompt',
 index=models.Index(fields=['slug', 'scope'], name='prompts_slug_bf4ca6_idx'),
 ),
 migrations.AddIndex(
 model_name='prompt',
 index=models.Index(fields=['category', 'scope'], name='prompts_categor_beaf76_idx'),
 ),
 migrations.AddIndex(
 model_name='prompt',
 index=models.Index(fields=['project', 'scope'], name='prompts_project_caaa23_idx'),
 ),
 migrations.AddConstraint(
 model_name='prompt',
 constraint=models.UniqueConstraint(condition=models.Q(('scope', 'system')), fields=('slug', 'scope'), name='uq_prompt_system_slug'),
 ),
 migrations.AddConstraint(
 model_name='prompt',
 constraint=models.UniqueConstraint(condition=models.Q(('scope', 'project')), fields=('slug', 'scope', 'project'), name='uq_prompt_project_slug'),
 ),
 ]
