# Generated by Django 6.0.1 on 2026-03-14 15:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=accounts.models._generate_invitation_token, max_length=64, unique=True, verbose_name='邀请令牌')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='预填邮箱（可选）')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接受时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '邀请',
                'verbose_name_plural': '邀请',
                'db_table': 'invitations',
                'indexes': [models.Index(fields=['token'], name='invitations_token_5b330c_idx'), models.Index(fields=['created_by'], name='invitations_created_7e898b_idx')],
            },
        ),
    ]
