# Generated by Django 6.0.1 on 2026-02-17 16:45
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('projects', '0003_add_claude_default_model'),
 migrations.swappable_dependency(settings.AUTH_USER_MODEL),
 ]
 operations = [
 migrations.CreateModel(
 name='Runner',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('name', models.CharField(max_length=200)),
 ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
 ('token_prefix', models.CharField(default='', max_length=8)),
 ('scope', models.CharField(choices=[('global', '全局'), ('project', '项目')], default='global', max_length=20)),
 ('concurrent', models.PositiveIntegerField(default=1)),
 ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=20)),
 ('version', models.CharField(blank=True, default='', max_length=50)),
 ('is_active', models.BooleanField(default=True)),
 ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
 ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
 ('registered_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('projects', models.ManyToManyField(blank=True, to='projects.project')),
 ],
 options={
 'db_table': 'runners',
 },
 ),
 migrations.CreateModel(
 name='RegistrationToken',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
 ('description', models.CharField(blank=True, default='', max_length=200)),
 ('scope', models.CharField(choices=[('global', '全局'), ('project', '项目')], default='global', max_length=20)),
 ('is_used', models.BooleanField(default=False)),
 ('used_at', models.DateTimeField(blank=True, null=True)),
 ('expires_at', models.DateTimeField),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
 ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
 ('used_by_runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runners.runner')),
 ],
 options={
 'db_table': 'runner_registration_tokens',
 },
 ),
 ]
