# Generated by Django 6.0.1 on 2026-02-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
