# Generated by Django 6.0.1 on 2026-02-18 09:54
import runners.models
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('runners', '0002_runner_channel_name'),
 ]
 operations = [
 migrations.AddField(
 model_name='runner',
 name='current_tasks',
 field=models.PositiveIntegerField(default=0, help_text='Runner 当前正在执行的任务数量', verbose_name='当前任务数'),
 ),
 migrations.AddField(
 model_name='runner',
 name='tags',
 field=models.JSONField(blank=True, default=runners.models._default_tags, help_text='Runner 能力标签，如 ["coding", "plan"]', verbose_name='标签'),
 ),
 ]
