# Generated by Django 6.0.1 on 2026-02-19 18:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0003_add_runner_tags_and_current_tasks'),
        ('subagent', '0009_executioncontext_failure_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('connected', '连接'), ('disconnected', '断开'), ('heartbeat', '心跳'), ('task_assigned', '任务分发'), ('task_completed', '任务完成'), ('task_failed', '任务失败')], max_length=30)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runners.runner')),
            ],
            options={
                'db_table': 'runner_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['runner', '-created_at'], name='runner_even_runner__2b1ccc_idx'), models.Index(fields=['event_type'], name='runner_even_event_t_281447_idx')],
            },
        ),
        migrations.CreateModel(
            name='RunnerTaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', '已分发'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='assigned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='runners.runner')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_assignments', to='subagent.subagentsession')),
            ],
            options={
                'db_table': 'runner_task_assignments',
                'indexes': [models.Index(fields=['runner', 'status'], name='runner_task_runner__811120_idx'), models.Index(fields=['session'], name='runner_task_session_a48a91_idx'), models.Index(fields=['assigned_at'], name='runner_task_assigne_1b4ee1_idx')],
            },
        ),
    ]
