# Generated by Django 6.0.1 on 2026-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0004_runnerevent_runnertaskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='暂停接收新作业'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='仅受保护分支'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='max_timeout',
            field=models.PositiveIntegerField(blank=True, help_text='最大作业超时（秒），最小 600', null=True),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='run_untagged',
            field=models.BooleanField(default=True, help_text='运行未打标签的作业'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='预设标签'),
        ),
        migrations.AddField(
            model_name='runner',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='runner',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='暂停接收新作业'),
        ),
        migrations.AddField(
            model_name='runner',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='仅受保护分支'),
        ),
        migrations.AddField(
            model_name='runner',
            name='max_timeout',
            field=models.PositiveIntegerField(blank=True, help_text='最大作业超时（秒）', null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='run_untagged',
            field=models.BooleanField(default=True, help_text='运行未打标签的作业'),
        ),
    ]
