# Generated by Django 6.0.1 on 2026-03-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0005_registrationtoken_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnertaskassignment',
            name='feishu_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='触发此任务的飞书消息 ID，用于断连恢复时映射', max_length=128),
        ),
    ]
