// Code generated by protoc-gen-go-http. DO NOT EDIT.
// 模拟 Kratos / grpc-gateway 生成的 *_http.pb.go 路由注册：
// handler 实参是函数调用 _Xxx_HTTP_Handler(srv)（call_expression），
// 而非裸标识符/选择器。用于验证 endpoint 提取器对此模式的支持。

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
)

const _ = http.SupportPackageIsVersion1

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/helloworld/{name}", _Greeter_SayHello0_HTTP_Handler(srv))
	r.POST("/v1/greeter", _Greeter_CreateGreeter0_HTTP_Handler(srv))
	r.PUT("/v1/greeter/{id}", _Greeter_UpdateGreeter0_HTTP_Handler(srv))
	r.DELETE("/v1/greeter/{id}", _Greeter_DeleteGreeter0_HTTP_Handler(srv))
	r.PATCH("/v1/greeter/{id}/status", _Greeter_PatchGreeter0_HTTP_Handler(srv))
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		return nil
	}
}

func _Greeter_CreateGreeter0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		return nil
	}
}

type GreeterHTTPServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}
