# Generated by Django 6.0.1 on 2026-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('builtin', '内置'), ('mcp', 'MCP Server'), ('skill', 'Skill')], max_length=20)),
                ('input_schema', models.JSONField()),
                ('timeout', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remote_tools',
            },
        ),
    ]
