# Generated by Django 6.0.1 on 2026-06-09 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_tokens', '0002_accesstoken_note_accesstoken_token_suffix'),
        ('tools', '0002_seed_builtin_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolTokenBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_bindings', to='access_tokens.accesstoken')),
                ('remote_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_bindings', to='tools.remotetool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_token_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tool_token_bindings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'remote_tool')},
            },
        ),
    ]
