apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
 name: friday
 namespace: argocd
spec:
 commonUpdateSettings:
 updateStrategy: semver
 writeBackConfig:
 method: argocd
 applicationRefs:
 - namePattern: "friday-ai-*"
 images:
 - alias: server
 imageName: "ghcr.io/friday-ai-codes/friday-ai/server"
 manifestTargets:
 helm:
 name: server.image.repository
 tag: server.image.tag
 - alias: web
 imageName: "ghcr.io/friday-ai-codes/friday-ai/web"
 manifestTargets:
 helm:
 name: web.image.repository
 tag: web.image.tag
 - alias: runner
 imageName: "ghcr.io/friday-ai-codes/friday-ai/runner"
 manifestTargets:
 helm:
 name: runner.image.repository
 tag: runner.image.tag
