# Generated by Django 6.0.1 on 2026-02-09 07:01
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('agents', '0002_agentsession_temp_data'),
 ]
 operations = [
 migrations.CreateModel(
 name='SubAgentOutput',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('task_id', models.CharField(db_index=True, max_length=64)),
 ('full_output', models.JSONField),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagent_outputs', to='agents.agentsession')),
 ],
 options={
 'ordering': ['-created_at'],
 },
 ),
 migrations.CreateModel(
 name='SubAgentSession',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
 ('repo_url', models.URLField),
 ('task_type', models.CharField(choices=[('explore', 'Explore Repository'), ('ask', 'Ask Question'), ('plan', 'Generate Plan'), ('coding', 'Coding Task')], max_length=20)),
 ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='idle', max_length=20)),
 ('current_task_id', models.CharField(blank=True, default='', max_length=64)),
 ('last_output', models.JSONField(blank=True, null=True)),
 ('last_error', models.TextField(blank=True, default='')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('main_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagent_sessions', to='agents.agentsession')),
 ],
 options={
 'indexes': [models.Index(fields=['main_session', 'task_type'], name='subagent_su_main_se_09e865_idx')],
 },
 ),
 ]
