# Generated by Django 6.0.1 on 2026-02-11 16:17
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('agents', '0002_agentsession_temp_data'),
 ('subagent', '0001_initial'),
 ('workflows', '0007_migrate_ai_agent_to_ai_plan_generation'),
 ]
 operations = [
 migrations.AddField(
 model_name='subagentsession',
 name='completed_at',
 field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
 ),
 migrations.AddField(
 model_name='subagentsession',
 name='container_id',
 field=models.CharField(blank=True, default='', help_text='Docker 容器完整 ID，持久化以防服务重启后丢失映射', max_length=128, verbose_name='Docker 容器 ID'),
 ),
 migrations.AddField(
 model_name='subagentsession',
 name='container_name',
 field=models.CharField(blank=True, default='', help_text='格式: friday-exec-{uuid}', max_length=255, verbose_name='Docker 容器名'),
 ),
 migrations.AddField(
 model_name='subagentsession',
 name='node_execution',
 field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subagent_sessions', to='workflows.nodeexecution', verbose_name='关联节点执行'),
 ),
 migrations.AddField(
 model_name='subagentsession',
 name='started_at',
 field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
 ),
 migrations.AddField(
 model_name='subagentsession',
 name='target_branch',
 field=models.CharField(blank=True, default='', max_length=255, verbose_name='目标分支'),
 ),
 migrations.AddField(
 model_name='subagentsession',
 name='work_item_id',
 field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='工作项 ID'),
 ),
 migrations.AlterField(
 model_name='subagentsession',
 name='status',
 field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='idle', max_length=20),
 ),
 migrations.AddIndex(
 model_name='subagentsession',
 index=models.Index(fields=['work_item_id', 'task_type', 'target_branch', 'status'], name='subagent_su_work_it_67167a_idx'),
 ),
 ]
