# Generated by Django 6.0.1 on 2026-02-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subagent', '0002_subagentsession_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentsession',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间'),
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('text', 'Text Output'), ('git', 'Git Artifacts')], max_length=10, verbose_name='结果类型')),
                ('text_output', models.TextField(blank=True, default='', verbose_name='文本输出')),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('pr_url', models.URLField(blank=True, default='')),
                ('modified_files', models.JSONField(blank=True, default=list, verbose_name='修改文件列表')),
                ('raw_output', models.JSONField(blank=True, default=dict, verbose_name='原始输出')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='执行时长(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_result', to='subagent.subagentsession')),
            ],
            options={
                'indexes': [models.Index(fields=['result_type'], name='subagent_ta_result__f37992_idx')],
            },
        ),
    ]
