# Generated by Django 6.0.1 on 2026-02-12 05:44
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('subagent', '0003_taskresult_and_heartbeat'),
 ]
 operations = [
 migrations.AddField(
 model_name='subagentsession',
 name='health_status',
 field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='容器健康状态'),
 ),
 ]
