# Generated by Django 6.0.1 on 2026-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subagent', '0004_add_health_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagentsession',
            name='cpu_usage_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU 使用率%'),
        ),
        migrations.AddField(
            model_name='subagentsession',
            name='memory_usage_mb',
            field=models.FloatField(blank=True, null=True, verbose_name='内存使用MB'),
        ),
    ]
