# Generated by Django 6.0.1 on 2026-02-12 14:09
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('subagent', '0005_add_resource_consumption_fields'),
 ]
 operations = [
 migrations.CreateModel(
 name='InteractionLog',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('question_id', models.CharField(db_index=True, help_text='唯一标识，用于匹配回复', max_length=64, verbose_name='问题 ID')),
 ('question_text', models.TextField(verbose_name='问题描述')),
 ('question_context', models.TextField(blank=True, default='', help_text='任务名、文件路径等上下文信息', verbose_name='上下文说明')),
 ('code_snippet', models.TextField(blank=True, default='', help_text='相关代码或 diff', verbose_name='代码片段')),
 ('options', models.JSONField(default=list, help_text="选项列表 ['选项A', '选项B']", verbose_name='可选项')),
 ('answer_text', models.TextField(blank=True, default='', verbose_name='用户回复')),
 ('answer_source', models.CharField(blank=True, choices=[('button', '按钮选择'), ('text', '文字输入')], default='', max_length=20, verbose_name='回复来源')),
 ('feishu_message_id', models.CharField(blank=True, default='', max_length=128, verbose_name='飞书消息 ID')),
 ('asked_at', models.DateTimeField(auto_now_add=True, verbose_name='提问时间')),
 ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
 ('reminder_count', models.IntegerField(default=0, verbose_name='提醒次数')),
 ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='上次提醒时间')),
 ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='subagent.subagentsession')),
 ],
 options={
 'verbose_name': '交互记录',
 'verbose_name_plural': '交互记录',
 'ordering': ['-asked_at'],
 'indexes': [models.Index(fields=['session', 'asked_at'], name='subagent_in_session_0f8a9b_idx'), models.Index(fields=['answered_at'], name='subagent_in_answere_a602f8_idx')],
 },
 ),
 ]
