# Generated by Django 6.0.1 on 2026-02-13 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subagent', '0006_interactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('tool_call', '工具调用'), ('llm_request', 'LLM 请求'), ('llm_response', 'LLM 响应'), ('state_change', '状态变更'), ('decision', '决策点')], max_length=20, verbose_name='动作类型')),
                ('timestamp', models.DateTimeField(verbose_name='事件时间')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='序号')),
                ('payload', models.JSONField(default=dict, verbose_name='载荷')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='subagent.subagentsession', verbose_name='关联会话')),
            ],
            options={
                'verbose_name': '执行日志',
                'verbose_name_plural': '执行日志',
                'ordering': ['session', 'sequence'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='subagent_ac_session_4338e3_idx'), models.Index(fields=['action_type'], name='subagent_ac_action__be2856_idx'), models.Index(fields=['session', 'sequence'], name='subagent_ac_session_d5c4ea_idx')],
            },
        ),
    ]
