# Generated by Django 6.0.1 on 2026-02-13 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subagent', '0007_add_action_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tokens', models.IntegerField(verbose_name='输入 Token')),
                ('output_tokens', models.IntegerField(verbose_name='输出 Token')),
                ('cache_read_tokens', models.IntegerField(default=0, verbose_name='缓存读取 Token')),
                ('cache_write_tokens', models.IntegerField(default=0, verbose_name='缓存写入 Token')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='总成本(USD)')),
                ('model', models.CharField(max_length=50, verbose_name='模型')),
                ('source', models.CharField(choices=[('subagent', 'SubAgent 上报'), ('verified', '主服务校验')], default='subagent', max_length=20, verbose_name='数据来源')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='subagent.subagentsession', verbose_name='关联会话')),
            ],
            options={
                'verbose_name': 'Token 使用',
                'verbose_name_plural': 'Token 使用',
                'indexes': [models.Index(fields=['session'], name='subagent_to_session_cc2636_idx'), models.Index(fields=['model'], name='subagent_to_model_17e606_idx'), models.Index(fields=['recorded_at'], name='subagent_to_recorde_6af417_idx')],
            },
        ),
    ]
