# Generated by Django 6.0.1 on 2026-02-15 05:23
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('subagent', '0008_add_token_usage'),
 ]
 operations = [
 migrations.AddField(
 model_name='subagentsession',
 name='failure_reason',
 field=models.TextField(blank=True, default='', verbose_name='失败原因'),
 ),
 migrations.CreateModel(
 name='ExecutionContext',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('environment_vars', models.JSONField(default=dict, verbose_name='环境变量')),
 ('input_prompt', models.TextField(blank=True, default='', verbose_name='输入 Prompt')),
 ('container_logs', models.TextField(blank=True, default='', verbose_name='容器日志')),
 ('docker_stats', models.JSONField(default=dict, verbose_name='Docker Stats 快照')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_context', to='subagent.subagentsession')),
 ],
 options={
 'verbose_name': '执行上下文',
 'verbose_name_plural': '执行上下文',
 'indexes': [models.Index(fields=['session'], name='subagent_ex_session_67e8e7_idx')],
 },
 ),
 ]
