# Generated by Django 6.0.1 on 2026-02-22 15:42
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('runners', '0004_runnerevent_runnertaskassignment'),
 ('subagent', '0009_executioncontext_failure_reason'),
 ]
 operations = [
 migrations.AddField(
 model_name='subagentsession',
 name='runner',
 field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_sessions', to='runners.runner', verbose_name='执行 Runner'),
 ),
 ]
