# Generated by Django 6.0.1 on 2026-03-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subagent', '0010_subagentsession_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='provider_type',
            field=models.CharField(blank=True, help_text='LLM Provider 类型，用于按 Provider 分组统计成本', max_length=50, null=True, verbose_name='Provider 类型'),
        ),
    ]
