# Generated by Django 6.0.1 on 2026-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subagent', '0012_add_repo_summary_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='provider_type',
            field=models.CharField(blank=True, help_text='LLM Provider 类型，用于按 Provider 分组统计成本 [v21.0 deprecated, will be removed after implementation UI cuts over to ProviderCredential]', max_length=50, null=True, verbose_name='Provider 类型'),
        ),
    ]
