# Generated by Django 6.0.1 on 2026-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subagent', '0013_alter_tokenusage_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagentsession',
            name='task_type',
            field=models.CharField(choices=[('explore', 'Explore Repository'), ('ask', 'Ask Question'), ('plan', 'Generate Plan'), ('coding', 'Coding Task'), ('repo_summary', 'Repository Summary'), ('repo_verify', 'Repo Verify')], max_length=20),
        ),
    ]
