# Generated by Django 6.0.1 on 2026-08-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subagent", "0015_subagentsession_sdk_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubAgentRuntimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("log_type", models.CharField(max_length=32, verbose_name="日志类型")),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                ("ts", models.DateTimeField(auto_now_add=True, verbose_name="记录时间")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runtime_logs",
                        to="subagent.subagentsession",
                        verbose_name="关联会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "容器运行日志",
                "verbose_name_plural": "容器运行日志",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["session", "id"], name="subagent_su_session_92b0e2_idx")
                ],
            },
        ),
    ]
