# Generated by Django 6.0.1 on 2026-06-11 10:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0009_remove_v81_legacy_claude_fields"),
        ("repositories", "0028_indexhistory_per_run_delta"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeEntity",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("work_item", "需求/缺陷"),
                            ("tech_plan", "技术方案"),
                            ("code_change", "代码变更"),
                            ("document", "文档"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("feishu", "飞书"),
                            ("chat", "对话"),
                            ("mcp", "MCP"),
                            ("workflow", "工作流"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        help_text="稳定业务引用类型（见 generate_entity_id natural key 规则表）",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="业务对象稳定 ID（含飞书三元组拼接）", max_length=255
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("current_version", models.PositiveIntegerField(default=1)),
                ("event_time", models.DateTimeField(help_text="业务事件时间（最近一次）")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_entities",
                        to="projects.project",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_entities",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识实体",
                "verbose_name_plural": "知识实体",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target_chunk_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="MODIFIES_CHUNK 边弱引用 ChunkRegistry.chunk_id（Phase 14 写入）。不做 ForeignKey（柔性引用原则）；与 target_entity 二选一（XOR 约束）。",
                        null=True,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("HAS_PLAN", "需求→方案"),
                            ("IMPLEMENTED_BY", "方案→代码变更"),
                            ("REFERENCES", "引用文档"),
                            ("RELATES_TO", "相关"),
                            ("DUPLICATE_OF", "重复"),
                            ("MODIFIES_CHUNK", "修改代码块"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("valid_at", models.DateTimeField(help_text="业务时间线：关系成立")),
                (
                    "invalid_at",
                    models.DateTimeField(
                        blank=True, help_text="业务时间线：关系失效（置位不删除）", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expired_at",
                    models.DateTimeField(blank=True, help_text="系统时间线：记录作废", null=True),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="knowledge.knowledgeentity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="knowledge.knowledgeentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识边",
                "verbose_name_plural": "知识边",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEntityVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("content", models.TextField(help_text="该版本全文（Phase 13 embedding 输入）")),
                (
                    "content_hash",
                    models.CharField(help_text="sha256 hex；内容未变跳过重摄取", max_length=64),
                ),
                ("payload", models.JSONField(default=dict, help_text="结构化原文快照")),
                (
                    "qdrant_point_ids",
                    models.JSONField(
                        default=list, help_text="Phase 13 写入；版本下线按 point id 精确删除（P1）"
                    ),
                ),
                ("is_latest", models.BooleanField(default=True)),
                ("event_time", models.DateTimeField(help_text="该版本对应的业务事件时间")),
                ("valid_at", models.DateTimeField(help_text="业务时间线：版本生效")),
                (
                    "invalid_at",
                    models.DateTimeField(
                        blank=True, help_text="业务时间线：被取代（置位不删除）", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expired_at",
                    models.DateTimeField(blank=True, help_text="系统时间线：记录作废", null=True),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="knowledge.knowledgeentity",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        help_text="被本版本取代的旧版本（显式版本链；PROTECT 防止删除被引用旧版本）",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="knowledge.knowledgeentityversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识实体版本",
                "verbose_name_plural": "知识实体版本",
            },
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(fields=["project", "kind"], name="idx_kentity_proj_kind"),
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(fields=["source_kind", "source_id"], name="idx_kentity_source"),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentity",
            constraint=models.UniqueConstraint(
                fields=("kind", "source_kind", "source_id"), name="uniq_kentity_natural_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["work_item", "tech_plan", "code_change", "document"])
                ),
                name="kentity_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin__in", ["feishu", "chat", "mcp", "workflow"])),
                name="kentity_origin_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(fields=["source_entity", "relation"], name="idx_kedge_fanout"),
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(fields=["target_entity"], name="idx_kedge_reverse"),
        ),
        migrations.AddIndex(
            model_name="knowledgeedge",
            index=models.Index(
                condition=models.Q(("invalid_at__isnull", True), ("expired_at__isnull", True)),
                fields=["source_entity"],
                name="idx_kedge_active_fanout",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeedge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invalid_at__isnull", True), ("expired_at__isnull", True)),
                fields=("source_entity", "target_entity", "relation"),
                name="uniq_kedge_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeedge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_entity__isnull", False), ("target_chunk_id__isnull", True)),
                    models.Q(("target_entity__isnull", True), ("target_chunk_id__isnull", False)),
                    _connector="OR",
                ),
                name="kedge_target_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeedge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invalid_at__isnull", True),
                    ("invalid_at__gt", models.F("valid_at")),
                    _connector="OR",
                ),
                name="kedge_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeedge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "relation__in",
                        [
                            "HAS_PLAN",
                            "IMPLEMENTED_BY",
                            "REFERENCES",
                            "RELATES_TO",
                            "DUPLICATE_OF",
                            "MODIFIES_CHUNK",
                        ],
                    )
                ),
                name="kedge_relation_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentityversion",
            index=models.Index(fields=["entity", "-version"], name="idx_kversion_entity_ver"),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentityversion",
            constraint=models.UniqueConstraint(
                fields=("entity", "version"), name="uniq_kversion_entity_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentityversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("entity",),
                name="uniq_kversion_one_latest",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentityversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invalid_at__isnull", True),
                    ("invalid_at__gt", models.F("valid_at")),
                    _connector="OR",
                ),
                name="kversion_valid_range",
            ),
        ),
    ]
