# Generated by Django 6.0.1 on 2026-06-11 16:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_knowledgeentityversion_vector_synced"),
        ("repositories", "0028_indexhistory_per_run_delta"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeChangeArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(help_text='来源类型（如 "task_result"）', max_length=50),
                ),
                (
                    "source_id",
                    models.CharField(help_text="业务对象稳定 ID（如 session_id）", max_length=255),
                ),
                ("commit_sha", models.CharField(blank=True, default="", max_length=64)),
                ("branch_name", models.CharField(blank=True, default="", max_length=255)),
                ("base_branch", models.CharField(blank=True, default="", max_length=255)),
                ("mr_url", models.URLField(blank=True, default="")),
                ("mr_id", models.CharField(blank=True, default="", max_length=64)),
                ("diff_compressed", models.BinaryField()),
                ("diff_size", models.PositiveIntegerField(help_text="解压后字节数")),
                ("compressed_size", models.PositiveIntegerField(help_text="压缩后字节数")),
                (
                    "diff_sha256",
                    models.CharField(help_text="原文 sha256 hex（幂等/完整性校验）", max_length=64),
                ),
                (
                    "truncated",
                    models.BooleanField(default=False, help_text="平台 API / 上限截断标记"),
                ),
                ("files", models.JSONField(default=list)),
                ("file_count", models.PositiveIntegerField(default=0)),
                ("total_additions", models.PositiveIntegerField(default=0)),
                ("total_deletions", models.PositiveIntegerField(default=0)),
                ("event_time", models.DateTimeField(help_text="业务事件时间（编码产出完成）")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "代码变更归档",
                "verbose_name_plural": "代码变更归档",
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgeedge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invalid_at__isnull", True), ("expired_at__isnull", True)),
                fields=("source_entity", "target_chunk_id", "relation"),
                name="uniq_kedge_chunk_active",
            ),
        ),
        migrations.AddField(
            model_name="codechangearchive",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="code_change_archives",
                to="repositories.repository",
            ),
        ),
        migrations.AddIndex(
            model_name="codechangearchive",
            index=models.Index(fields=["repository", "commit_sha"], name="idx_cca_repo_commit"),
        ),
        migrations.AddIndex(
            model_name="codechangearchive",
            index=models.Index(fields=["source_kind", "source_id"], name="idx_cca_source"),
        ),
        migrations.AddConstraint(
            model_name="codechangearchive",
            constraint=models.UniqueConstraint(
                fields=("source_kind", "source_id", "commit_sha"),
                name="uniq_codechange_source_commit",
            ),
        ),
    ]
