# Generated by Django 6.0.1 on 2026-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_codechangearchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechangearchive',
            name='mr_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
