# Generated by Django 6.0.1 on 2026-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_codechangearchive_mr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentityversion',
            name='toc_tree',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
