# Generated by Django 6.0.1 on 2026-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_rename_project_to_space'),
        ('projects', '0010_rename_project_to_space'),
        ('repositories', '0039_repository_git_instance_credential'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgeentity',
            name='kentity_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='knowledgeentity',
            name='kentity_origin_valid',
        ),
        migrations.AlterField(
            model_name='knowledgeentity',
            name='kind',
            field=models.CharField(choices=[('work_item', '需求/缺陷'), ('tech_plan', '技术方案'), ('code_change', '代码变更'), ('document', '文档'), ('project', '项目'), ('repository', '仓库'), ('space', '空间')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgeentity',
            name='origin',
            field=models.CharField(choices=[('feishu', '飞书'), ('chat', '对话'), ('mcp', 'MCP'), ('workflow', '工作流'), ('artifact', '工件'), ('project', '项目')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='knowledgeentity',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['work_item', 'tech_plan', 'code_change', 'document', 'project', 'repository', 'space'])), name='kentity_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeentity',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['feishu', 'chat', 'mcp', 'workflow', 'artifact', 'project'])), name='kentity_origin_valid'),
        ),
    ]
