# Generated by Django 6.0.1 on 2026-07-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_remove_knowledgeentity_kentity_kind_valid_and_more'),
        ('projects', '0010_rename_project_to_space'),
        ('repositories', '0039_repository_git_instance_credential'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgeentity',
            name='kentity_kind_valid',
        ),
        migrations.AlterField(
            model_name='knowledgeentity',
            name='kind',
            field=models.CharField(choices=[('work_item', '需求/缺陷'), ('tech_plan', '技术方案'), ('code_change', '代码变更'), ('document', '文档'), ('project', '项目'), ('repository', '仓库'), ('space', '空间'), ('learning_case', '经验案例')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='knowledgeentity',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['work_item', 'tech_plan', 'code_change', 'document', 'project', 'repository', 'space', 'learning_case'])), name='kentity_kind_valid'),
        ),
    ]
