# Generated by Django 6.0.1 on 2026-06-18 05:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("link", models.CharField(blank=True, default="", max_length=512)),
                ("status", models.CharField(db_index=True, default="draft", max_length=16)),
                ("notify_mode", models.CharField(default="popup", max_length=16)),
                ("audience", models.CharField(default="all", max_length=16)),
                ("target_user_ids", models.JSONField(blank=True, default=list)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "系统公告",
                "verbose_name_plural": "系统公告",
                "db_table": "announcement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="notifications.announcement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "公告已读记录",
                "verbose_name_plural": "公告已读记录",
                "db_table": "announcement_read",
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "-created_at"], name="announcemen_status_d9f732_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(fields=["starts_at"], name="announcemen_starts__2471c8_idx"),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(fields=["ends_at"], name="announcemen_ends_at_538be7_idx"),
        ),
        migrations.AddIndex(
            model_name="announcementread",
            index=models.Index(
                fields=["user", "announcement"], name="announcemen_user_id_40b4ea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementread",
            constraint=models.UniqueConstraint(
                fields=("announcement", "user"), name="uniq_announcement_user_read"
            ),
        ),
    ]
