# Generated by Django 6.0.1 on 2026-06-18 04:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.CharField(db_index=True, default="other", max_length=16)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("page_url", models.CharField(blank=True, default="", max_length=1024)),
                ("conversation_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("message_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("author_repr", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField()),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="feedback.feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈回复",
                "verbose_name_plural": "反馈回复",
                "db_table": "feedback_reply",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["status", "-created_at"], name="feedback_status_711338_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["category", "-created_at"], name="feedback_categor_c199ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["created_by", "-created_at"], name="feedback_created_01dc06_idx"
            ),
        ),
    ]
