"""MR creation service for CodingTasks with dual-channel failure reporting."""

from typing import Any

import structlog

from repositories.models import Repository
from services.git_credentials import aresolve_git_token
from services.git_platform import MRCreateRequest, MRCreateResult, get_git_platform_client
from workflows.models.coding_task import CodingTask

logger = structlog.get_logger()


async def _resolve_impact_user(execution: Any) -> Any:
    """解析影响面报告所需的触发用户（对齐 AICodingNode._resolve_dispatch_user）。

    - 无 ``triggered_by_id`` → None（stub ``user_missing``，不撞 ACL）
    - Django model：优先 fields_cache，否则按 id 异步反查（避免 ASGI 下 sync lazy FK）
    - 非 ORM fixture（MagicMock 等）：直接读 ``triggered_by`` 属性
    """
    if execution is None:
        return None
    triggered_by_id = getattr(execution, "triggered_by_id", None)
    if not triggered_by_id:
        return None
    state = getattr(execution, "_state", None)
    fields_cache = getattr(state, "fields_cache", None)
    if isinstance(fields_cache, dict):
        cached = fields_cache.get("triggered_by")
        if cached is not None:
            return cached
    from django.db.models import Model

    if isinstance(execution, Model):
        from django.contrib.auth import get_user_model

        return await get_user_model().objects.filter(pk=triggered_by_id).afirst()
    return getattr(execution, "triggered_by", None)


def build_mr_description(
    feishu_url: str | None,
    feishu_title: str | None,
    tech_summary: str | None,
    modified_files: list[str],
) -> str:
    """Build structured MR description per project standards."""
    sections = []

    # Feishu link section
    if feishu_url and feishu_title:
        sections.append(f"## 关联飞书工作项\n\n[{feishu_title}]({feishu_url})")
    elif feishu_url:
        sections.append(f"## 关联飞书工作项\n\n{feishu_url}")

    # Tech summary section
    if tech_summary:
        sections.append(f"## 技术方案摘要\n\n{tech_summary}")

    # Modified files section
    if modified_files:
        files_list = "\n".join(f"- `{f}`" for f in modified_files[:20])
        if len(modified_files) > 20:
            files_list += f"\n- ... and {len(modified_files) - 20} more files"
        sections.append(f"## 修改文件\n\n{files_list}")

    sections.append("---\n*Generated by Friday AI Coding Agent*")

    return "\n\n".join(sections)


def build_mr_title(task_name: str) -> str:
    """Build MR title using Conventional Commits format."""
    # Remove common prefixes and clean up
    name = task_name.strip()
    if name.lower().startswith(("feat:", "fix:", "refactor:", "docs:", "chore:")):
        return name  # Already has prefix
    return f"feat: {name}"


async def report_feishu_failure(
    task: CodingTask,
    error: str,
    branch_name: str,
) -> bool:
    """Report MR creation failure to Feishu work item as a comment.

    This implements the dual-channel reporting requirement from CONTEXT.md:
    '失败信息双通道上报：前端展示详细错误 + 飞书工作项备注回填'

    Args:
        task: The CodingTask that failed MR creation
        error: Error message describing the failure
        branch_name: The branch that was successfully pushed

    Returns:
        True if Feishu comment was posted successfully, False otherwise
    """
    log = logger.bind(task_id=str(task.id))

    # Get Feishu work item info from task metadata
    metadata = task.metadata or {}
    feishu_work_item_id = metadata.get("feishu_work_item_id")
    feishu_project_key = metadata.get("feishu_project_key")
    feishu_work_item_type = metadata.get("feishu_work_item_type", "story")

    if not feishu_work_item_id or not feishu_project_key:
        log.warning("No Feishu work item info, skipping failure notification")
        return False

    try:
        # Import Feishu client (lazy import to avoid circular deps)
        from feishu.client import create_feishu_client_for_project

        # Get the project from the workflow execution
        workflow_execution = task.workflow_execution
        project = workflow_execution.workflow.space

        # Create Feishu client
        client = create_feishu_client_for_project(project)

        # Build failure message for Feishu
        comment = (
            f"⚠️ **MR 创建失败**\n\n"
            f"分支 `{branch_name}` 已成功推送，但 MR 创建失败。\n\n"
            f"**错误信息：**\n{error}\n\n"
            f"请手动创建 MR 或检查 Git 平台配置。"
        )

        # Post comment to Feishu work item
        success = await client.add_comment(
            project_key=feishu_project_key,
            work_item_id=int(feishu_work_item_id),
            work_item_type=feishu_work_item_type,
            content=comment,
        )

        if success:
            log.info("Posted MR failure to Feishu", work_item_id=feishu_work_item_id)
        else:
            log.warning("Failed to post to Feishu", work_item_id=feishu_work_item_id)

        return success

    except Exception as e:
        log.error("Error posting to Feishu", error=str(e))
        return False


async def create_mr_for_task(
    task: CodingTask,
    branch_name: str,
    commit_sha: str,
    modified_files: list[str],
    target_branch: str | None = None,
) -> MRCreateResult:
    """Create MR/PR for a completed coding task."""
    log = logger.bind(task_id=str(task.id), branch=branch_name)

    repository: Repository = task.repository

    # Phase 26 REPO-01：统一经解析器取 token（per-repo 优先 → 同 host 实例凭证池 fallback）
    token = await aresolve_git_token(repository)
    if not token:
        return MRCreateResult(success=False, error="No API token configured for repository")

    # Get platform client
    try:
        client = get_git_platform_client(repository, token)
    except ValueError as e:
        return MRCreateResult(success=False, error=str(e))

    # Extract context from task metadata
    metadata = task.metadata or {}
    feishu_url = metadata.get("feishu_url")
    feishu_title = metadata.get("feishu_title")
    tech_summary = metadata.get("tech_summary")
    reviewers = metadata.get("reviewers", [])

    # Build MR content
    title = build_mr_title(task.name)
    description = build_mr_description(feishu_url, feishu_title, tech_summary, modified_files)
    resolved_target = target_branch or repository.default_branch

    # Phase 124 DIFF-04：与 AICodingNode / MCP 同一 helper；fail-soft 不阻断建 MR（D-06/D-09）
    try:
        from services.code_graph.impact_report import (
            append_impact_report,
            build_impact_report_section,
        )

        execution = getattr(task, "workflow_execution", None)
        user = await _resolve_impact_user(execution)
        section = await build_impact_report_section(
            repository=repository,
            user=user,
            compare=branch_name,
            base_ref=resolved_target,
        )
        description = append_impact_report(description, section)
    except Exception as exc:  # noqa: BLE001 — 最后兜底；helper 内应已吞
        try:
            log.warning(
                "impact_report_shell_failed",
                component="workflows",
                category="caller",
                repository_id=str(getattr(repository, "id", "") or ""),
                error=str(exc)[:200],
            )
        except Exception:  # noqa: BLE001 — 观测永不反噬
            pass

    # Phase 127 TAINT-02：与 AICodingNode / MCP 同一 security helper（D-04/D-06）
    security_user = None
    try:
        from services.code_graph.security_scan_report import (
            append_security_scan,  # noqa: F401 — D-06 dual-link 合同字面量
            attach_security_scan_pending,
        )

        execution = getattr(task, "workflow_execution", None)
        security_user = await _resolve_impact_user(execution)
        description = await attach_security_scan_pending(
            description,
            repository=repository,
            source_branch=branch_name,
            target_branch=resolved_target or "",
            user=security_user,
            enqueue=False,
        )
    except Exception as exc:  # noqa: BLE001 — 最后兜底；helper 内应已吞
        try:
            log.warning(
                "security_scan_shell_failed",
                component="workflows",
                category="caller",
                repository_id=str(getattr(repository, "id", "") or ""),
                error=str(exc)[:200],
            )
        except Exception:  # noqa: BLE001 — 观测永不反噬
            pass

    # Create MR request
    request = MRCreateRequest(
        source_branch=branch_name,
        target_branch=resolved_target,
        title=title,
        description=description,
        reviewer_usernames=reviewers,
    )

    log.info("Creating MR", title=title, reviewers=reviewers)

    # Create MR
    result = await client.create_merge_request(request)

    if result.success:
        log.info("MR created successfully", mr_url=result.mr_url)
        try:
            from services.code_graph.semgrep_enqueue import (
                enqueue_semgrep_scan_for_branches,
            )

            initiated_by = (
                str(security_user.id)
                if security_user is not None and getattr(security_user, "id", None) is not None
                else "system"
            )
            # source 侧直接复用本次推送的 commit_sha（已是完整 sha 时零额外调用）；
            # target 侧经 client 解析 base 分支 HEAD。任一端空则跳过入队。
            await enqueue_semgrep_scan_for_branches(
                str(getattr(repository, "id", "") or ""),
                mr_key=str(result.mr_id or ""),
                source_branch=branch_name,
                target_branch=resolved_target or "",
                client=client,
                source_sha=commit_sha or "",
                initiated_by_user_id=initiated_by,
            )
        except Exception as exc:  # noqa: BLE001 — enqueue 失败不反噬已建 MR
            try:
                log.warning(
                    "security_scan_shell_failed",
                    component="workflows",
                    category="caller",
                    repository_id=str(getattr(repository, "id", "") or ""),
                    error=str(exc)[:200],
                )
            except Exception:  # noqa: BLE001
                pass
    else:
        log.error("MR creation failed", error=result.error)

    return result
