"""MR creation service for CodingTasks with dual-channel failure reporting."""

import structlog

from repositories.models import Repository
from services.git_credentials import aresolve_git_token
from services.git_platform import MRCreateRequest, MRCreateResult, get_git_platform_client
from workflows.models.coding_task import CodingTask

logger = structlog.get_logger()


def build_mr_description(
    feishu_url: str | None,
    feishu_title: str | None,
    tech_summary: str | None,
    modified_files: list[str],
) -> str:
    """Build structured MR description per project standards."""
    sections = []

    # Feishu link section
    if feishu_url and feishu_title:
        sections.append(f"## 关联飞书工作项\n\n[{feishu_title}]({feishu_url})")
    elif feishu_url:
        sections.append(f"## 关联飞书工作项\n\n{feishu_url}")

    # Tech summary section
    if tech_summary:
        sections.append(f"## 技术方案摘要\n\n{tech_summary}")

    # Modified files section
    if modified_files:
        files_list = "\n".join(f"- `{f}`" for f in modified_files[:20])
        if len(modified_files) > 20:
            files_list += f"\n- ... and {len(modified_files) - 20} more files"
        sections.append(f"## 修改文件\n\n{files_list}")

    sections.append("---\n*Generated by Friday AI Coding Agent*")

    return "\n\n".join(sections)


def build_mr_title(task_name: str) -> str:
    """Build MR title using Conventional Commits format."""
    # Remove common prefixes and clean up
    name = task_name.strip()
    if name.lower().startswith(("feat:", "fix:", "refactor:", "docs:", "chore:")):
        return name  # Already has prefix
    return f"feat: {name}"


async def report_feishu_failure(
    task: CodingTask,
    error: str,
    branch_name: str,
) -> bool:
    """Report MR creation failure to Feishu work item as a comment.

    This implements the dual-channel reporting requirement from CONTEXT.md:
    '失败信息双通道上报：前端展示详细错误 + 飞书工作项备注回填'

    Args:
        task: The CodingTask that failed MR creation
        error: Error message describing the failure
        branch_name: The branch that was successfully pushed

    Returns:
        True if Feishu comment was posted successfully, False otherwise
    """
    log = logger.bind(task_id=str(task.id))

    # Get Feishu work item info from task metadata
    metadata = task.metadata or {}
    feishu_work_item_id = metadata.get("feishu_work_item_id")
    feishu_project_key = metadata.get("feishu_project_key")
    feishu_work_item_type = metadata.get("feishu_work_item_type", "story")

    if not feishu_work_item_id or not feishu_project_key:
        log.warning("No Feishu work item info, skipping failure notification")
        return False

    try:
        # Import Feishu client (lazy import to avoid circular deps)
        from feishu.client import create_feishu_client_for_project

        # Get the project from the workflow execution
        workflow_execution = task.workflow_execution
        project = workflow_execution.workflow.space

        # Create Feishu client
        client = create_feishu_client_for_project(project)

        # Build failure message for Feishu
        comment = (
            f"⚠️ **MR 创建失败**\n\n"
            f"分支 `{branch_name}` 已成功推送，但 MR 创建失败。\n\n"
            f"**错误信息：**\n{error}\n\n"
            f"请手动创建 MR 或检查 Git 平台配置。"
        )

        # Post comment to Feishu work item
        success = await client.add_comment(
            project_key=feishu_project_key,
            work_item_id=int(feishu_work_item_id),
            work_item_type=feishu_work_item_type,
            content=comment,
        )

        if success:
            log.info("Posted MR failure to Feishu", work_item_id=feishu_work_item_id)
        else:
            log.warning("Failed to post to Feishu", work_item_id=feishu_work_item_id)

        return success

    except Exception as e:
        log.error("Error posting to Feishu", error=str(e))
        return False


async def create_mr_for_task(
    task: CodingTask,
    branch_name: str,
    commit_sha: str,
    modified_files: list[str],
    target_branch: str | None = None,
) -> MRCreateResult:
    """Create MR/PR for a completed coding task."""
    log = logger.bind(task_id=str(task.id), branch=branch_name)

    repository: Repository = task.repository

    # Phase 26 REPO-01：统一经解析器取 token（per-repo 优先 → 同 host 实例凭证池 fallback）
    token = await aresolve_git_token(repository)
    if not token:
        return MRCreateResult(success=False, error="No API token configured for repository")

    # Get platform client
    try:
        client = get_git_platform_client(repository, token)
    except ValueError as e:
        return MRCreateResult(success=False, error=str(e))

    # Extract context from task metadata
    metadata = task.metadata or {}
    feishu_url = metadata.get("feishu_url")
    feishu_title = metadata.get("feishu_title")
    tech_summary = metadata.get("tech_summary")
    reviewers = metadata.get("reviewers", [])

    # Build MR content
    title = build_mr_title(task.name)
    description = build_mr_description(feishu_url, feishu_title, tech_summary, modified_files)
    resolved_target = target_branch or repository.default_branch

    # Phase 124 DIFF-04：与 AICodingNode / MCP 同一 helper；fail-soft 不阻断建 MR（D-06/D-09）
    try:
        from services.code_graph.impact_report import (
            append_impact_report,
            build_impact_report_section,
        )

        execution = getattr(task, "workflow_execution", None)
        user = getattr(execution, "triggered_by", None) if execution is not None else None
        section = await build_impact_report_section(
            repository=repository,
            user=user,
            compare=branch_name,
            base_ref=resolved_target,
        )
        description = append_impact_report(description, section)
    except Exception:  # noqa: BLE001 — 最后兜底；helper 内应已吞
        pass

    # Create MR request
    request = MRCreateRequest(
        source_branch=branch_name,
        target_branch=resolved_target,
        title=title,
        description=description,
        reviewer_usernames=reviewers,
    )

    log.info("Creating MR", title=title, reviewers=reviewers)

    # Create MR
    result = await client.create_merge_request(request)

    if result.success:
        log.info("MR created successfully", mr_url=result.mr_url)
    else:
        log.error("MR creation failed", error=result.error)

    return result
