# Generated by Django 6.0.1 on 2026-03-14 13:44
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('projects', '0004_project_default_model_project_default_provider_type'),
 migrations.swappable_dependency(settings.AUTH_USER_MODEL),
 ]
 operations = [
 migrations.CreateModel(
 name='ProjectMembership',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('role', models.CharField(choices=[('admin', '管理员'), ('member', '成员'), ('viewer', '观察者')], default='member', max_length=20, verbose_name='角色')),
 ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
 ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
 ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
 ],
 options={
 'verbose_name': '项目成员',
 'verbose_name_plural': '项目成员',
 'db_table': 'project_memberships',
 'indexes': [models.Index(fields=['project', 'role'], name='project_mem_project_ce1662_idx'), models.Index(fields=['user'], name='project_mem_user_id_95343b_idx')],
 'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project')],
 },
 ),
 ]
