# Generated by Django 6.0.1 on 2026-06-04 10:39
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('agents', '0003_nullable_session_project_user'),
 ('orchestration', '0003_alter_orchestrationrun_phase'),
 ]
 operations = [
 migrations.CreateModel(
 name='InteractionRun',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
 ('token_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
 ('source', models.CharField(db_index=True, max_length=50)),
 ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
 ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('error', '错误'), ('denied', '已拒绝')], db_index=True, default='running', max_length=20)),
 ('raw_request', models.JSONField(blank=True, default=dict)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('completed_at', models.DateTimeField(blank=True, null=True)),
 ('agent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agentsession')),
 ('orchestration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orchestration.orchestrationrun')),
 ],
 options={
 'db_table': 'interaction_runs',
 'ordering': ['-created_at'],
 },
 ),
 migrations.CreateModel(
 name='InteractionEvent',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('seq', models.PositiveIntegerField),
 ('event_type', models.CharField(choices=[('user_input', '用户输入'), ('skill_step', 'Skill 步骤'), ('agent_decision', 'Agent 决策'), ('clarification', '澄清'), ('tool_call', '工具调用'), ('tool_result', '工具结果'), ('error', '错误'), ('retry', '重试')], db_index=True, max_length=30)),
 ('payload', models.JSONField(blank=True, default=dict)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='interactions.interactionevent')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interactions.interactionrun')),
 ],
 options={
 'db_table': 'interaction_events',
 'ordering': ['run', 'seq'],
 },
 ),
 migrations.CreateModel(
 name='ModelUsageRecord',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('provider', models.CharField(max_length=64)),
 ('model', models.CharField(max_length=128)),
 ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
 ('system_prompt_version', models.CharField(blank=True, default='', max_length=64)),
 ('prompt_tokens', models.PositiveIntegerField(default=0)),
 ('completion_tokens', models.PositiveIntegerField(default=0)),
 ('total_tokens', models.PositiveIntegerField(default=0)),
 ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
 ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
 ('failure_type', models.CharField(blank=True, default='', max_length=64)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.interactionevent')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_usages', to='interactions.interactionrun')),
 ],
 options={
 'db_table': 'model_usage_records',
 'ordering': ['-created_at'],
 },
 ),
 migrations.CreateModel(
 name='ToolCallRecord',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('tool_name', models.CharField(db_index=True, max_length=128)),
 ('input', models.JSONField(blank=True, default=dict)),
 ('output', models.JSONField(blank=True, default=dict)),
 ('status', models.CharField(max_length=30)),
 ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
 ('error', models.TextField(blank=True, default='')),
 ('retry_index', models.PositiveIntegerField(default=0)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.interactionevent')),
 ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='interactions.interactionrun')),
 ],
 options={
 'db_table': 'tool_call_records',
 'ordering': ['-created_at'],
 },
 ),
 migrations.AddIndex(
 model_name='interactionrun',
 index=models.Index(fields=['token_fingerprint', '-created_at'], name='interaction_token_f_14ae0b_idx'),
 ),
 migrations.AddIndex(
 model_name='interactionrun',
 index=models.Index(fields=['status'], name='interaction_status_8cbc1c_idx'),
 ),
 migrations.AddIndex(
 model_name='interactionevent',
 index=models.Index(fields=['run', 'seq'], name='interaction_run_id_626efa_idx'),
 ),
 migrations.AddIndex(
 model_name='modelusagerecord',
 index=models.Index(fields=['run', '-created_at'], name='model_usage_run_id_2bd3c9_idx'),
 ),
 migrations.AddIndex(
 model_name='modelusagerecord',
 index=models.Index(fields=['provider', 'model'], name='model_usage_provide_ad8110_idx'),
 ),
 migrations.AddIndex(
 model_name='toolcallrecord',
 index=models.Index(fields=['run', '-created_at'], name='tool_call_r_run_id_62cde5_idx'),
 ),
 migrations.AddIndex(
 model_name='toolcallrecord',
 index=models.Index(fields=['tool_name'], name='tool_call_r_tool_na_a4b188_idx'),
 ),
 ]
