# Generated by Django 6.0.1 on 2026-06-04 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('routing', '仓库路由'), ('chunk', 'RAG chunk 命中'), ('edge', 'GraphRAG 邻居边'), ('file', '文件读取')], db_index=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_traces', to='interactions.interactionrun')),
                ('tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.toolcallrecord')),
            ],
            options={
                'db_table': 'retrieval_traces',
                'ordering': ['run', 'seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='retrieval_t_run_id_d50f51_idx'), models.Index(fields=['kind'], name='retrieval_t_kind_3f4e35_idx')],
            },
        ),
    ]
