# Generated by Django 6.0.1 on 2026-06-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_retrievaltrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelusagerecord',
            name='call_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='modelusagerecord',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='modelusagerecord',
            name='ttft_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelusagerecord',
            name='upstream_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelusagerecord',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='system', max_length=64),
        ),
        migrations.AddField(
            model_name='retrievaltrace',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='retrievaltrace',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='retrievaltrace',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='system', max_length=64),
        ),
        migrations.AlterField(
            model_name='modelusagerecord',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_usages', to='interactions.interactionrun'),
        ),
        migrations.AlterField(
            model_name='retrievaltrace',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_traces', to='interactions.interactionrun'),
        ),
        migrations.AddIndex(
            model_name='modelusagerecord',
            index=models.Index(fields=['call_source', '-created_at'], name='model_usage_call_so_f8e415_idx'),
        ),
        migrations.AddIndex(
            model_name='modelusagerecord',
            index=models.Index(fields=['upstream_status_code'], name='model_usage_upstrea_07b284_idx'),
        ),
    ]
