# Generated by Django 6.0.1 on 2026-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='token_suffix',
            field=models.CharField(default='', max_length=8),
        ),
    ]
