# Generated by Django 6.0.1 on 2026-01-21 07:44
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies =
 operations = [
 migrations.CreateModel(
 name='SystemSetting',
 fields=[
 ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
 ('value', models.TextField(blank=True, null=True)),
 ('is_encrypted', models.BooleanField(default=False)),
 ('description', models.TextField(blank=True, null=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ],
 options={
 'verbose_name': '系统设置',
 'verbose_name_plural': '系统设置',
 'db_table': 'system_settings',
 },
 ),
 ]
