# Generated by Django 6.0.1 on 2026-02-16 12:25
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('system', '0001_initial'),
 ]
 operations = [
 migrations.CreateModel(
 name='CacheVolumeTracker',
 fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('volume_name', models.CharField(db_index=True, max_length=255, unique=True)),
 ('volume_type', models.CharField(choices=[('repo', '仓库缓存'), ('deps', '依赖缓存')], max_length=20)),
 ('repo_url', models.CharField(blank=True, default='', max_length=500)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('last_used_at', models.DateTimeField(auto_now_add=True)),
 ('is_expired', models.BooleanField(db_index=True, default=False)),
 ],
 options={
 'verbose_name': '缓存卷跟踪',
 'verbose_name_plural': '缓存卷跟踪',
 'db_table': 'cache_volume_tracker',
 },
 ),
 ]
