# Generated by Django 6.0.1 on 2026-03-08 14:07
from django.db import migrations
def migrate_provider_keys(apps, schema_editor):
 """将旧配置键迁移到 default_provider_type，然后删除旧键。
 - llm_provider_type 的值（实际 Provider 类型如 "anthropic"）迁移到 default_provider_type
 - provider_type（Chat 协议类型如 "openai_chat"）直接删除，不迁移
 """
 SystemSetting = apps.get_model("system", "SystemSetting")
 # 优先使用 llm_provider_type 的值（这是实际的 Provider 类型）
 old_llm = SystemSetting.objects.filter(key="llm_provider_type").first
 if old_llm and old_llm.value:
 SystemSetting.objects.update_or_create(
 key="default_provider_type",
 defaults={"value": old_llm.value, "description": "默认 LLM Provider 类型"},
 )
 # 删除旧键
 SystemSetting.objects.filter(key__in=["llm_provider_type", "provider_type"]).delete
def reverse_migrate(apps, schema_editor):
 """反向迁移：恢复旧键。"""
 SystemSetting = apps.get_model("system", "SystemSetting")
 new_key = SystemSetting.objects.filter(key="default_provider_type").first
 if new_key and new_key.value:
 SystemSetting.objects.update_or_create(
 key="llm_provider_type",
 defaults={"value": new_key.value},
 )
class Migration(migrations.Migration):
 dependencies = [
 ('system', '0002_cachevolumetracker'),
 ]
 operations = [
 migrations.RunPython(migrate_provider_keys, reverse_migrate),
 ]
