# Generated by Django 6.0.1 on 2026-04-19 15:28
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('system', '0003_migrate_provider_setting_keys'),
 ]
 operations = [
 migrations.CreateModel(
 name='ProviderCredential',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('provider_type', models.CharField(db_index=True, help_text="Provider 类型字符串。本 phase 仅 'anthropic'，Phase 扩展为 5 种。", max_length=32)),
 ('name', models.CharField(default='default', help_text="同 Provider 多凭证区分键。例 'openai-prod' / 'openai-dev'。", max_length=64)),
 ('scope', models.CharField(choices=[('system', '系统级'), ('project', '项目级')], default='system', max_length=16)),
 ('scope_id', models.UUIDField(blank=True, help_text='scope=PROJECT 时为 project.id；scope=SYSTEM 时为 NULL。刻意不用 FK，避免 Project 级联删除导致凭证消失。', null=True)),
 ('encrypted_config', models.TextField(help_text='encrypt_value(json.dumps({...})) Fernet 整体加密；service 层显式加解密。')),
 ('base_url', models.CharField(blank=True, default='', max_length=500)),
 ('default_model', models.CharField(blank=True, default='', max_length=128)),
 ('is_active', models.BooleanField(default=True)),
 ('last_health_check_at', models.DateTimeField(blank=True, help_text='Phase 写入；本 phase 仅预留字段。', null=True)),
 ('last_health_check_status', models.CharField(blank=True, default='', help_text='ok/error/untested。Phase 写入；本 phase 仅预留字段。', max_length=16)),
 ('last_health_check_error', models.TextField(blank=True, default='')),
 ('available_models', models.JSONField(blank=True, default=list, help_text='模型清单缓存。Phase/229 写入；本 phase 仅预留字段。')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ],
 options={
 'verbose_name': 'Provider 凭证',
 'verbose_name_plural': 'Provider 凭证',
 'db_table': 'provider_credentials',
 'indexes': [models.Index(fields=['scope', 'scope_id', 'provider_type'], name='provider_cr_scope_dde3c5_idx'), models.Index(fields=['is_active', 'provider_type'], name='provider_cr_is_acti_c5b9fd_idx')],
 'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'system')), fields=('provider_type', 'name'), name='uniq_system_provider_credential'), models.UniqueConstraint(condition=models.Q(('scope', 'project')), fields=('scope_id', 'provider_type', 'name'), name='uniq_project_provider_credential')],
 },
 ),
 ]
