# Generated by Django 6.0.1 on 2026-05-31 04:50
#
# 新增 ProviderCredential.is_default 字段 + 数据回填迁移。
# 把存量 name="default" 凭证回填为 is_default=True，按
# (scope, scope_id, provider_type) 分组去重，避免触发新增的
# uniq_default_provider_per_scope_type 约束（同组取 created_at 最早一行）。
from django.db import migrations, models
def forwards(apps, schema_editor):
 """把 name='default' 的存量凭证回填为 is_default=True（按维度去重）。"""
 ProviderCredential = apps.get_model("system", "ProviderCredential")
 seen: set[tuple[str, str, str]] = set
 qs = ProviderCredential.objects.filter(name="default").order_by("created_at", "id")
 for cred in qs:
 key = (cred.scope, str(cred.scope_id), cred.provider_type)
 if key in seen:
 # 同 (scope, scope_id, provider_type) 已有更早的 default，跳过以免触发唯一约束
 continue
 seen.add(key)
 if not cred.is_default:
 cred.is_default = True
 cred.save(update_fields=["is_default"])
def backwards(apps, schema_editor):
 """回滚：所有 is_default 置回 False。"""
 ProviderCredential = apps.get_model("system", "ProviderCredential")
 ProviderCredential.objects.filter(is_default=True).update(is_default=False)
class Migration(migrations.Migration):
 dependencies = [
 ('system', '0006_remove_v81_legacy_anthropic_settings'),
 ]
 operations = [
 migrations.AddField(
 model_name='providercredential',
 name='is_default',
 field=models.BooleanField(db_index=True, default=False, help_text="该 (scope, scope_id, provider_type) 维度的系统/项目默认凭证。替代 name='default' 魔法约定。"),
 ),
 # 先回填数据再加约束：保证约束校验时数据已去重，不会因同组多个 default 失败
 migrations.RunPython(forwards, backwards),
 migrations.AddConstraint(
 model_name='providercredential',
 constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('scope', 'scope_id', 'provider_type'), name='uniq_default_provider_per_scope_type'),
 ),
 ]
