# Generated by Django 6.0.1 on 2026-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_providercredential_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercredential',
            name='max_concurrency',
            field=models.PositiveIntegerField(default=50, help_text='该凭证的 LLM 并发上限（CONC-02）。0=不限，默认 50。'),
        ),
    ]
