# Generated by Django 6.0.1 on 2026-06-24 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_providercredential_max_concurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('source_ip', models.CharField(blank=True, default='', max_length=64)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('raw_body', models.TextField(blank=True, default='')),
                ('user_id', models.CharField(blank=True, db_index=True, default='system', max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('correlation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '入站 Webhook 事件',
                'verbose_name_plural': '入站 Webhook 事件',
                'db_table': 'inbound_webhook_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['kind', '-received_at'], name='inbound_web_kind_197d5e_idx'), models.Index(fields=['-received_at'], name='inbound_web_receive_098b3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, help_text='事件时间（倒序查看）。')),
                ('level', models.CharField(blank=True, default='info', max_length=10)),
                ('component', models.CharField(blank=True, default='', max_length=40)),
                ('category', models.CharField(blank=True, default='', max_length=10)),
                ('event', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('user_id', models.CharField(blank=True, db_index=True, default='system', max_length=64)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '系统日志条目',
                'verbose_name_plural': '系统日志条目',
                'db_table': 'system_log_entries',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['-ts'], name='system_log__ts_29605d_idx'), models.Index(fields=['component', '-ts'], name='system_log__compone_673ddf_idx'), models.Index(fields=['level', '-ts'], name='system_log__level_83a909_idx'), models.Index(fields=['user_id', '-ts'], name='system_log__user_id_955442_idx'), models.Index(fields=['source', '-ts'], name='system_log__source_27d3fb_idx')],
            },
        ),
    ]
