# Generated by Django 6.0.1 on 2026-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_inboundwebhookevent_systemlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, help_text='事件时间（倒序/聚合）。')),
                ('source', models.CharField(db_index=True, default='', max_length=32)),
                ('route', models.CharField(blank=True, default='', max_length=200)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('error_class', models.CharField(blank=True, default='none', max_length=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ttft_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, default='system', max_length=64)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '请求指标',
                'verbose_name_plural': '请求指标',
                'db_table': 'request_metrics',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts', 'source'], name='request_met_ts_43b8fe_idx'), models.Index(fields=['ts', 'error_class'], name='request_met_ts_4bd61e_idx'), models.Index(fields=['-ts'], name='request_met_ts_04434b_idx')],
            },
        ),
    ]
