# Generated by Django 6.0.1 on 2026-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_requestmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeSample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, help_text='采样时刻（倒序/聚合）。')),
                ('name', models.CharField(db_index=True, default='', max_length=64)),
                ('value', models.FloatField(default=0.0)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '仪表盘采样',
                'verbose_name_plural': '仪表盘采样',
                'db_table': 'gauge_samples',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts', 'name'], name='gauge_sampl_ts_c891bc_idx'), models.Index(fields=['name', '-ts'], name='gauge_sampl_name_b3c9d8_idx')],
            },
        ),
    ]
