# Generated by Django 6.0.1 on 2026-06-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_gaugesample'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlertRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='规则名（中文/英文）。', max_length=64)),
                ('metric', models.CharField(db_index=True, help_text='受控指标枚举。', max_length=32)),
                ('op', models.CharField(help_text='比较操作符 gt/gte/lt/lte。', max_length=4)),
                ('value', models.FloatField(help_text='阈值。')),
                ('window', models.PositiveIntegerField(default=300, help_text='评估窗口秒（快照类忽略）。')),
                ('dimension', models.JSONField(blank=True, default=dict, help_text='受控维度 jsonb（空=overall）。')),
                ('severity', models.CharField(help_text='级别 P0/P1/P2。', max_length=2)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('channels', models.JSONField(blank=True, default=list, help_text='通道子集 email/feishu/webhook；空=仅落事件。')),
                ('cooldown', models.PositiveIntegerField(default=600, help_text='再次通知冷却秒数（防抖）；0=不冷却。')),
                ('title_template', models.CharField(blank=True, default='', help_text='中文标题模板（{metric}/{current}/{value} 占位）；空则默认拼接。', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统告警规则',
                'verbose_name_plural': '系统告警规则',
                'db_table': 'system_alert_rules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enabled', 'metric'], name='system_aler_enabled_7f679a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(db_index=True, help_text='级别 P0/P1/P2（冗余）。', max_length=2)),
                ('title_zh', models.CharField(blank=True, default='', max_length=200)),
                ('rule_info', models.JSONField(blank=True, default=dict, help_text='机器可读规则信息 jsonb。')),
                ('target', models.JSONField(blank=True, default=dict, help_text='对象标识 jsonb（overall={}）。')),
                ('target_key', models.CharField(blank=True, default='', help_text='target 规范化串，仅用于去重唯一约束。', max_length=128)),
                ('status', models.CharField(db_index=True, default='firing', max_length=10)),
                ('started_at', models.DateTimeField(db_index=True, help_text='首次触发时刻。')),
                ('ended_at', models.DateTimeField(blank=True, help_text='恢复时刻（firing 时 null）。', null=True)),
                ('duration_s', models.PositiveIntegerField(blank=True, help_text='持续秒数（恢复时回写）。', null=True)),
                ('current_value', models.FloatField(blank=True, help_text='最近一次评估当前值。', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='最近一次仍超阈评估时刻。', null=True)),
                ('email_sent', models.CharField(default='pending', help_text='邮件状态（74-03 回写）。', max_length=10)),
                ('notified_channels', models.JSONField(blank=True, default=list, help_text='实际成功通知通道（74-03 回写）。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='system.systemalertrule')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'db_table': 'alert_events',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='alert_event_status_902933_idx'), models.Index(fields=['severity', '-started_at'], name='alert_event_severit_5e5f3e_idx'), models.Index(fields=['-started_at'], name='alert_event_started_92940d_idx'), models.Index(fields=['rule', '-started_at'], name='alert_event_rule_id_0ce616_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'firing')), fields=('rule', 'target_key'), name='uniq_firing_alert_per_rule_target')],
            },
        ),
    ]
