# Generated by Django 6.0.1 on 2026-06-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_systemalertrule_alertevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercredential',
            name='scope_id',
            field=models.UUIDField(blank=True, help_text='scope=PROJECT 时为 project.id；scope=SYSTEM 时为 NULL。刻意不用 FK，避免 Space 级联删除导致凭证消失。', null=True),
        ),
    ]
