# Generated by Django 6.0.1 on 2026-01-23 09:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("icon", models.CharField(default="workflow", max_length=50, verbose_name="图标")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动触发"),
                            ("webhook", "Webhook 触发"),
                            ("schedule", "定时触发"),
                            ("event", "事件触发"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="根据触发类型存储不同配置，如 cron 表达式、webhook secret 等",
                        verbose_name="触发配置",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="模板可被其他项目复制", verbose_name="是否为模板"
                    ),
                ),
                (
                    "max_concurrent_executions",
                    models.PositiveIntegerField(
                        default=1, help_text="0 表示不限制", verbose_name="最大并发执行数"
                    ),
                ),
                (
                    "default_timeout",
                    models.PositiveIntegerField(default=3600, verbose_name="默认超时(秒)"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储画布位置、缩放等 UI 状态",
                        verbose_name="元数据",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流",
                "verbose_name_plural": "工作流",
                "db_table": "workflows",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "path",
                    models.CharField(
                        help_text="Webhook URL 的路径部分",
                        max_length=100,
                        unique=True,
                        verbose_name="路径",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="签名密钥"
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(blank=True, default=list, verbose_name="允许的 IP"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_configs",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook 配置",
                "verbose_name_plural": "Webhook 配置",
                "db_table": "workflow_webhook_configs",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("paused", "已暂停"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                            ("timeout", "超时"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trigger_type", models.CharField(max_length=20, verbose_name="触发类型")),
                (
                    "trigger_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="如 webhook payload、定时任务信息等",
                        verbose_name="触发数据",
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict, verbose_name="执行上下文")),
                ("input_data", models.JSONField(blank=True, default=dict, verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(blank=True, default=dict, verbose_name="输出数据"),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_node_id", models.UUIDField(blank=True, null=True)),
                ("total_nodes", models.PositiveIntegerField(default=0)),
                ("completed_nodes", models.PositiveIntegerField(default=0)),
                ("failed_nodes", models.PositiveIntegerField(default=0)),
                ("skipped_nodes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("timeout_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发者",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流执行",
                "verbose_name_plural": "工作流执行",
                "db_table": "workflow_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("request_method", models.CharField(max_length=10)),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body", models.TextField(blank=True, default="")),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, default="")),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workflows.webhookconfig",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="workflows.workflowexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook 日志",
                "verbose_name_plural": "Webhook 日志",
                "db_table": "workflow_webhook_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        help_text="如: manual_trigger, create_branch, code_implement",
                        max_length=100,
                        verbose_name="节点类型",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="节点名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("position_x", models.FloatField(default=0, verbose_name="X 坐标")),
                ("position_y", models.FloatField(default=0, verbose_name="Y 坐标")),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="节点特定的配置参数",
                        verbose_name="节点配置",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="覆盖工作流默认超时",
                        null=True,
                        verbose_name="超时(秒)",
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0, verbose_name="重试次数")),
                (
                    "retry_delay",
                    models.PositiveIntegerField(default=60, verbose_name="重试间隔(秒)"),
                ),
                (
                    "run_condition",
                    models.JSONField(
                        blank=True,
                        help_text="JSON 格式的条件表达式，为 null 时始终执行",
                        null=True,
                        verbose_name="执行条件",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储 UI 状态、注释等",
                        verbose_name="元数据",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流节点",
                "verbose_name_plural": "工作流节点",
                "db_table": "workflow_nodes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_handle",
                    models.CharField(
                        default="default",
                        help_text="如: default, true, false, branch_1",
                        max_length=50,
                        verbose_name="源连接点",
                    ),
                ),
                (
                    "target_handle",
                    models.CharField(default="default", max_length=50, verbose_name="目标连接点"),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True,
                        help_text="JSON 格式的条件表达式",
                        null=True,
                        verbose_name="通过条件",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("style", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="workflows.workflownode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="workflows.workflownode",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流边",
                "verbose_name_plural": "工作流边",
                "db_table": "workflow_edges",
            },
        ),
        migrations.CreateModel(
            name="NodeExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("queued", "排队中"),
                            ("running", "执行中"),
                            ("waiting_approval", "等待审批"),
                            ("waiting_input", "等待输入"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("skipped", "已跳过"),
                            ("cancelled", "已取消"),
                            ("timeout", "超时"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_traceback", models.TextField(blank=True, default="")),
                ("attempt", models.PositiveIntegerField(default=1, verbose_name="当前尝试次数")),
                (
                    "approval_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储审批请求、审批人、审批意见等",
                        verbose_name="审批数据",
                    ),
                ),
                ("container_id", models.CharField(blank=True, default="", max_length=100)),
                ("container_logs", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_executions",
                        to="workflows.workflowexecution",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflownode",
                    ),
                ),
            ],
            options={
                "verbose_name": "节点执行",
                "verbose_name_plural": "节点执行",
                "db_table": "node_executions",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["project", "is_active"], name="workflows_project_570176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["trigger_type"], name="workflows_trigger_43beb3_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="workflow_ex_workflo_05fdb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "created_at"], name="workflow_ex_status_741304_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowedge",
            unique_together={("source_node", "target_node", "source_handle", "target_handle")},
        ),
        migrations.AddIndex(
            model_name="nodeexecution",
            index=models.Index(
                fields=["workflow_execution", "status"], name="node_execut_workflo_46f6a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeexecution",
            index=models.Index(fields=["node", "status"], name="node_execut_node_id_070382_idx"),
        ),
    ]
