# Generated by Django 6.0.1 on 2026-01-28 07:52
import uuid
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ("feishu", "0001_initial"),
 ("repositories", "0004_repository_proxy_url"),
 ("workflows", "0001_initial"),
 ]
 operations = [
 migrations.AddField(
 model_name="workflowexecution",
 name="global_params",
 field=models.JSONField(
 blank=True,
 default=dict,
 help_text="节点间共享的全局参数，可通过 {{global.key}} 引用",
 verbose_name="全局参数",
 ),
 ),
 migrations.AddField(
 model_name="workflowexecution",
 name="is_manual_trigger",
 field=models.BooleanField(
 default=False, help_text="手动触发时模拟事件数据", verbose_name="是否手动触发"
 ),
 ),
 migrations.AddField(
 model_name="workflowexecution",
 name="trigger_log",
 field=models.ForeignKey(
 blank=True,
 help_text="关联的飞书 Webhook 触发日志",
 null=True,
 on_delete=django.db.models.deletion.SET_NULL,
 related_name="workflow_executions",
 to="feishu.triggerlog",
 verbose_name="触发日志",
 ),
 ),
 migrations.CreateModel(
 name="CodingTask",
 fields=[
 (
 "id",
 models.UUIDField(
 default=uuid.uuid4, editable=False, primary_key=True, serialize=False
 ),
 ),
 ("name", models.CharField(max_length=200, verbose_name="任务名称")),
 (
 "prompt",
 models.TextField(
 help_text="发送给 AI 的编码指令", verbose_name="AI 编码 Prompt"
 ),
 ),
 ("description", models.TextField(blank=True, default="", verbose_name="任务描述")),
 (
 "status",
 models.CharField(
 choices=[
 ("pending", "待执行"),
 ("planning", "规划中"),
 ("plan_review", "方案评审"),
 ("executing", "执行中"),
 ("code_review", "代码评审"),
 ("merged", "已合并"),
 ("failed", "失败"),
 ("cancelled", "已取消"),
 ],
 default="pending",
 max_length=20,
 verbose_name="状态",
 ),
 ),
 (
 "session_id",
 models.CharField(
 blank=True, default="", max_length=100, verbose_name="Claude Code 会话 ID"
 ),
 ),
 (
 "plan_output",
 models.TextField(
 blank=True,
 default="",
 help_text="AI 规划阶段的输出内容",
 verbose_name="规划输出",
 ),
 ),
 (
 "human_feedback",
 models.TextField(
 blank=True,
 default="",
 help_text="人工评审时的反馈意见",
 verbose_name="人工反馈",
 ),
 ),
 (
 "branch_name",
 models.CharField(
 blank=True, default="", max_length=200, verbose_name="Git 分支名"
 ),
 ),
 (
 "commit_sha",
 models.CharField(
 blank=True, default="", max_length=40, verbose_name="提交哈希"
 ),
 ),
 ("pr_url", models.URLField(blank=True, default="", verbose_name="PR 链接")),
 (
 "error_message",
 models.TextField(blank=True, default="", verbose_name="错误信息"),
 ),
 ("retry_count", models.PositiveIntegerField(default=0, verbose_name="重试次数")),
 (
 "metadata",
 models.JSONField(
 blank=True,
 default=dict,
 help_text="存储额外信息，如分析结果、关联的需求字段等",
 verbose_name="元数据",
 ),
 ),
 ("created_at", models.DateTimeField(auto_now_add=True)),
 ("updated_at", models.DateTimeField(auto_now=True)),
 (
 "started_at",
 models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
 ),
 (
 "completed_at",
 models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
 ),
 (
 "repository",
 models.ForeignKey(
 on_delete=django.db.models.deletion.CASCADE,
 related_name="coding_tasks",
 to="repositories.repository",
 verbose_name="代码仓库",
 ),
 ),
 (
 "workflow_execution",
 models.ForeignKey(
 on_delete=django.db.models.deletion.CASCADE,
 related_name="coding_tasks",
 to="workflows.workflowexecution",
 verbose_name="工作流执行",
 ),
 ),
 ],
 options={
 "verbose_name": "编码任务",
 "verbose_name_plural": "编码任务",
 "db_table": "coding_tasks",
 "ordering": ["-created_at"],
 "indexes": [
 models.Index(
 fields=["workflow_execution", "status"],
 name="coding_task_workflo_74c17c_idx",
 ),
 models.Index(
 fields=["repository", "status"], name="coding_task_reposit_e87bf0_idx"
 ),
 models.Index(
 fields=["status", "created_at"], name="coding_task_status_eec44a_idx"
 ),
 ],
 },
 ),
 migrations.CreateModel(
 name="WorkflowTrigger",
 fields=[
 (
 "id",
 models.UUIDField(
 default=uuid.uuid4, editable=False, primary_key=True, serialize=False
 ),
 ),
 (
 "event_type",
 models.CharField(
 choices=[
 ("WorkitemCreateEvent", "工作项创建"),
 ("WorkitemStatusEvent", "状态变更"),
 ("WorkitemCommentEvent", "评论事件"),
 ("WorkitemUpdateEvent", "字段更新"),
 ("WorkFlowNodeStatusEvent", "节点流转"),
 ("WorkitemFinishEvent", "工作项完成"),
 ("WorkitemDeleteEvent", "工作项删除"),
 ("WorkitemAbortedEvent", "工作项终止"),
 ("WorkitemRestoreEvent", "工作项恢复"),
 ("TaskCreateEvent", "任务创建"),
 ("TaskStatusEvent", "任务状态变更"),
 ("TaskUpdateEvent", "任务修改"),
 ],
 help_text="监听的飞书 Webhook 事件类型",
 max_length=50,
 verbose_name="事件类型",
 ),
 ),
 (
 "filter_config",
 models.JSONField(
 blank=True,
 default=dict,
 help_text="JSON 格式的过滤条件，如 project_key, work_item_type, status 等",
 verbose_name="过滤条件",
 ),
 ),
 (
 "input_schema",
 models.JSONField(
 blank=True,
 default=dict,
 help_text="JSON Schema 格式，用于校验触发器输入数据",
 verbose_name="输入参数 Schema",
 ),
 ),
 ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
 (
 "name",
 models.CharField(
 blank=True, default="", max_length=200, verbose_name="触发器名称"
 ),
 ),
 ("description", models.TextField(blank=True, default="", verbose_name="描述")),
 ("created_at", models.DateTimeField(auto_now_add=True)),
 ("updated_at", models.DateTimeField(auto_now=True)),
 (
 "workflow",
 models.ForeignKey(
 on_delete=django.db.models.deletion.CASCADE,
 related_name="triggers",
 to="workflows.workflow",
 verbose_name="工作流",
 ),
 ),
 ],
 options={
 "verbose_name": "工作流触发器",
 "verbose_name_plural": "工作流触发器",
 "db_table": "workflow_triggers",
 "ordering": ["-created_at"],
 "indexes": [
 models.Index(
 fields=["workflow", "is_active"], name="workflow_tr_workflo_0e079f_idx"
 ),
 models.Index(
 fields=["event_type", "is_active"], name="workflow_tr_event_t_030ef9_idx"
 ),
 ],
 },
 ),
 ]
