# Generated by Django 6.0.1 on 2026-02-03 04:30
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('workflows', '0002_workflowexecution_global_params_and_more'),
 ]
 operations = [
 migrations.AlterField(
 model_name='nodeexecution',
 name='status',
 field=models.CharField(choices=[('pending', '待执行'), ('queued', '排队中'), ('running', '执行中'), ('waiting_approval', '等待审批'), ('waiting_input', '等待输入'), ('waiting_event', '等待事件'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过'), ('cancelled', '已取消'), ('timeout', '超时')], default='pending', max_length=20),
 ),
 migrations.AlterField(
 model_name='workflowexecution',
 name='status',
 field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('paused', '已暂停'), ('suspended', '挂起中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('timeout', '超时')], default='pending', max_length=20),
 ),
 migrations.CreateModel(
 name='WorkflowEventSubscription',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('event_type', models.CharField(help_text='如 WorkitemUpdateEvent, WorkitemStatusEvent', max_length=50, verbose_name='事件类型')),
 ('project_key', models.CharField(max_length=100, verbose_name='项目标识')),
 ('work_item_id', models.CharField(blank=True, default='', help_text='为空表示匹配该项目的所有工作项', max_length=100, verbose_name='工作项 ID')),
 ('work_item_type', models.CharField(default='story', max_length=50, verbose_name='工作项类型')),
 ('condition_expression', models.JSONField(default=dict, help_text='JSON 格式的条件表达式，支持 logic:and/or + conditions 数组', verbose_name='条件表达式')),
 ('timeout_at', models.DateTimeField(blank=True, null=True, verbose_name='超时时间')),
 ('timeout_action', models.CharField(choices=[('fail', '失败终止'), ('skip', '跳过继续'), ('retry', '重试')], default='fail', max_length=20, verbose_name='超时动作')),
 ('is_active', models.BooleanField(default=True, help_text='工作流完成/取消后设为 False', verbose_name='是否活跃')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='匹配时间')),
 ('matched_payload', models.JSONField(blank=True, default=dict, verbose_name='匹配的事件数据')),
 ('node_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='workflows.nodeexecution', verbose_name='节点执行')),
 ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='workflows.workflowexecution', verbose_name='工作流执行')),
 ],
 options={
 'verbose_name': '工作流事件订阅',
 'verbose_name_plural': '工作流事件订阅',
 'db_table': 'workflow_event_subscriptions',
 'ordering': ['-created_at'],
 'indexes': [models.Index(fields=['is_active', 'project_key', 'work_item_id'], name='workflow_ev_is_acti_6db9e0_idx'), models.Index(fields=['is_active', 'event_type'], name='workflow_ev_is_acti_65e4ca_idx'), models.Index(fields=['timeout_at'], name='workflow_ev_timeout_92ccc0_idx')],
 },
 ),
 ]
