# Generated by Django 6.0.1 on 2026-02-03 09:08
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('workflows', '0003_suspended_status'),
 ]
 operations = [
 migrations.AddField(
 model_name='codingtask',
 name='execution_log',
 field=models.TextField(blank=True, default='', help_text='完整的 AI 编码执行日志', verbose_name='执行日志'),
 ),
 migrations.AddField(
 model_name='codingtask',
 name='execution_plan_ids',
 field=models.JSONField(blank=True, default=list, help_text='从技术方案 execution_plan 合并的任务 ID 列表', verbose_name='关联的执行计划项 ID'),
 ),
 migrations.AddField(
 model_name='codingtask',
 name='global_context_snapshot',
 field=models.TextField(blank=True, default='', help_text='任务创建时的 global_context，用于重试', verbose_name='全局上下文快照'),
 ),
 ]
