# Generated by Django 6.0.1 on 2026-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_add_execution_plan_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('planning', '规划中'), ('plan_review', '方案评审'), ('executing', '执行中'), ('code_review', '代码评审'), ('partial_success', '部分成功'), ('merged', '已合并'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
