# Generated by Django 6.0.1 on 2026-02-07 19:07

from django.db import migrations, models

import common.short_id


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_codingtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='short_id',
            field=models.CharField(default=common.short_id.generate_short_id, help_text='用于模板变量引用，如 {{nodes.abc.field}}', max_length=12, verbose_name='短 ID'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'short_id'], name='workflow_no_workflo_68abc5_idx'),
        ),
    ]
