# Generated by Django 6.0.1 on 2026-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_migrate_ai_agent_to_ai_plan_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(help_text='如: manual_trigger, create_branch, ai_coding', max_length=100, verbose_name='节点类型'),
        ),
    ]
