# Generated by Django 6.0.1 on 2026-03-03 07:38
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('workflows', '0011_migrate_technical_plan_to_plan_generation'),
 ]
 operations = [
 migrations.AddField(
 model_name='workflowexecution',
 name='workflow_definition',
 field=models.JSONField(blank=True, default=dict, help_text='执行创建时保存的精简 DAG 数据（节点位置、连接关系、类型和名称），确保历史执行始终反映当时的 DAG', verbose_name='工作流定义快照'),
 ),
 ]
