# Generated by Django 6.0.1 on 2026-03-04 13:01
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('workflows', '0012_workflowexecution_workflow_definition'),
 ]
 operations = [
 migrations.AddField(
 model_name='workflowexecution',
 name='resumed_from',
 field=models.ForeignKey(blank=True, help_text='从失败节点继续时，指向原失败执行实例', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumed_executions', to='workflows.workflowexecution', verbose_name='继续自'),
 ),
 ]
