# Generated by Django 6.0.1 on 2026-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_workflowexecution_resumed_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeexecution',
            name='provider_type',
            field=models.CharField(blank=True, help_text='节点实际使用的 Provider，执行时写入', max_length=50, null=True, verbose_name='Provider 类型'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='provider_type',
            field=models.CharField(blank=True, help_text='执行时使用的主 Provider，用于成本归因', max_length=50, null=True, verbose_name='Provider 类型'),
        ),
    ]
