# Generated by Django 6.0.1 on 2026-03-08 18:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_nodeexecution_provider_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSubStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='步骤名称')),
                ('step_type', models.CharField(help_text='子步骤类型标识，如 tool_call、thinking、code_generation', max_length=50, verbose_name='步骤类型')),
                ('step_order', models.IntegerField(verbose_name='步骤顺序')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='输出数据')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('node_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_steps', to='workflows.nodeexecution', verbose_name='节点执行')),
            ],
            options={
                'verbose_name': '节点子步骤',
                'verbose_name_plural': '节点子步骤',
                'db_table': 'node_sub_steps',
                'ordering': ['step_order'],
                'indexes': [models.Index(fields=['node_execution', 'step_order'], name='node_sub_st_node_ex_4a2a4b_idx')],
            },
        ),
    ]
