# Generated by Django 6.0.1 on 2026-03-09 10:07
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('workflows', '0015_nodesubstep'),
 ]
 operations = [
 migrations.AddField(
 model_name='nodeexecution',
 name='sub_step_completed_count',
 field=models.IntegerField(default=0, verbose_name='已完成子步骤数'),
 ),
 migrations.AddField(
 model_name='nodeexecution',
 name='sub_step_total_count',
 field=models.IntegerField(default=0, verbose_name='子步骤总数'),
 ),
 ]
