# Generated by Django 6.0.1 on 2026-03-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_workflowexecution_project_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='debug_paused_at_node',
            field=models.UUIDField(blank=True, help_text='记录当前暂停在哪个节点 ID，用于前端展示调试状态', null=True, verbose_name='调试暂停节点'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='is_debug',
            field=models.BooleanField(db_index=True, default=False, help_text='调试执行不计入正式记录，不触发通知，不受并发限制', verbose_name='调试执行'),
        ),
    ]
