# Generated by Django 6.0.1 on 2026-03-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0020_add_debug_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="feishu_message_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="最近一次工作流通知的飞书消息 ID",
                max_length=128,
                verbose_name="飞书消息 ID",
            ),
        ),
    ]
