# Generated by Django 6.0.1 on 2026-04-29 06:14

from django.db import migrations, models


def migrate_old_fields_forward(apps, schema_editor):
    """Copy retry_count -> retry_times, timeout -> node_timeout_seconds before removing old fields."""
    WorkflowNode = apps.get_model("workflows", "WorkflowNode")
    for node in WorkflowNode.objects.all():
        changed = False
        # retry_count -> retry_times (only if non-zero)
        old_retry = getattr(node, "retry_count", 0)
        if old_retry and old_retry > 0:
            node.retry_times = old_retry
            node.on_error = "retry"
            changed = True
        # timeout -> node_timeout_seconds (only if set)
        old_timeout = getattr(node, "timeout", None)
        if old_timeout:
            node.node_timeout_seconds = old_timeout
            changed = True
        if changed:
            node.save(update_fields=["retry_times", "on_error", "node_timeout_seconds"])


def migrate_old_fields_backward(apps, schema_editor):
    """Reverse: copy retry_times -> retry_count, node_timeout_seconds -> timeout."""
    WorkflowNode = apps.get_model("workflows", "WorkflowNode")
    for node in WorkflowNode.objects.all():
        changed = False
        if node.retry_times and node.retry_times > 0:
            node.retry_count = node.retry_times
            changed = True
        if node.node_timeout_seconds:
            node.timeout = node.node_timeout_seconds
            changed = True
        if changed:
            node.save(update_fields=["retry_count", "timeout"])


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_remove_cancelled_status'),
    ]

    operations = [
        # Step 1: Add new fields (with defaults, safe to add)
        migrations.AddField(
            model_name='workflownode',
            name='on_error',
            field=models.CharField(
                choices=[('abort', '中止'), ('retry', '重试'), ('ignore', '忽略')],
                default='abort',
                help_text='节点执行失败时的处理策略',
                max_length=10,
                verbose_name='错误策略',
            ),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='retry_times',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='on_error=retry 时的重试次数',
                verbose_name='重试次数',
            ),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='node_timeout_seconds',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='节点执行超时时间，超时后触发 on_error 策略',
                null=True,
                verbose_name='节点超时(秒)',
            ),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='fallback_values',
            field=models.JSONField(
                blank=True,
                help_text='on_error=ignore 时传递给下游节点的默认输出',
                null=True,
                verbose_name='容错默认值',
            ),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='retry_delay',
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text='重试基础间隔，实际间隔按指数退避计算',
                verbose_name='重试间隔(秒)',
            ),
        ),
        # Step 2: Data migration — copy old field values to new fields
        migrations.RunPython(migrate_old_fields_forward, migrate_old_fields_backward),
        # Step 3: Remove old fields (after data is safely copied)
        migrations.RemoveField(
            model_name='workflownode',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='workflownode',
            name='timeout',
        ),
    ]
