# Generated by Django 6.0.1 on 2026-04-30 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_v81_legacy_claude_fields'),
        ('workflows', '0024_debug_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('condition_type', models.CharField(choices=[('execution_failed', '执行失败'), ('execution_timeout', '执行超时'), ('cost_threshold', '成本超阈值'), ('node_error_code', '节点错误码')], max_length=30, verbose_name='条件类型')),
                ('condition_config', models.JSONField(blank=True, default=dict, verbose_name='条件配置')),
                ('action_type', models.CharField(choices=[('feishu_notification', '飞书通知'), ('webhook', 'Webhook')], max_length=30, verbose_name='动作类型')),
                ('action_config', models.JSONField(blank=True, default=dict, verbose_name='动作配置')),
                ('cooldown_seconds', models.PositiveIntegerField(default=0, verbose_name='冷却时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='projects.project', verbose_name='所属项目')),
                ('workflow', models.ForeignKey(blank=True, help_text='null 表示全局规则（所有工作流）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='workflows.workflow', verbose_name='关联工作流')),
            ],
            options={
                'db_table': 'workflow_alert_rules',
            },
        ),
        migrations.CreateModel(
            name='AlertRuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('status', models.CharField(choices=[('triggered', '已触发'), ('delivered', '已送达'), ('failed', '发送失败')], default='triggered', max_length=20, verbose_name='状态')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误消息')),
                ('triggered_event', models.CharField(blank=True, default='', max_length=50, verbose_name='触发事件')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.alertrule', verbose_name='告警规则')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rule_executions', to='workflows.workflowexecution', verbose_name='工作流执行')),
            ],
            options={
                'verbose_name': '告警规则执行记录',
                'verbose_name_plural': '告警规则执行记录',
                'db_table': 'workflow_alert_rule_executions',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['project', 'enabled'], name='workflow_al_project_85785c_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['workflow', 'enabled'], name='workflow_al_workflo_0a95a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertruleexecution',
            unique_together={('alert_rule', 'workflow_execution')},
        ),
    ]
