# Generated by Django 6.0.1 on 2026-06-28 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0031_rename_project_to_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_name', models.CharField(help_text='如 node.completed / node.failed / artifact.produced', max_length=64, verbose_name='订阅信号')),
                ('target_type', models.CharField(help_text='notify_feishu_im / feishu_doc_create / writeback / webhook / alert', max_length=40, verbose_name='目标类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='目标配置')),
                ('blocking_mode', models.CharField(choices=[('non_blocking', '非阻塞'), ('gate', '闸门'), ('compensation', '补偿')], default='non_blocking', max_length=20, verbose_name='阻塞模式')),
                ('retry_policy', models.JSONField(blank=True, default=dict, verbose_name='重试策略')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_node', models.ForeignKey(blank=True, help_text='null 表示订阅工作流内任意节点的该信号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='workflows.workflownode', verbose_name='宿主节点')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='workflows.workflow', verbose_name='所属工作流')),
            ],
            options={
                'verbose_name': '工作流反应',
                'verbose_name_plural': '工作流反应',
                'db_table': 'workflow_reactions',
            },
        ),
        migrations.CreateModel(
            name='ReactionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, verbose_name='幂等键')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('delivered', '已送达'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('triggered_signal', models.CharField(blank=True, default='', max_length=64, verbose_name='触发信号')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_executions', to='workflows.workflowexecution', verbose_name='工作流执行')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflowreaction', verbose_name='反应配置')),
            ],
            options={
                'verbose_name': '反应执行记录',
                'verbose_name_plural': '反应执行记录',
                'db_table': 'workflow_reaction_executions',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowreaction',
            index=models.Index(fields=['workflow', 'signal_name', 'enabled'], name='workflow_re_workflo_7afce1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowreaction',
            index=models.Index(fields=['host_node', 'signal_name'], name='workflow_re_host_no_939d82_idx'),
        ),
        migrations.AddIndex(
            model_name='reactionexecution',
            index=models.Index(fields=['workflow_execution', 'status'], name='workflow_re_workflo_b673b7_idx'),
        ),
        migrations.AddIndex(
            model_name='reactionexecution',
            index=models.Index(fields=['status', 'triggered_at'], name='workflow_re_status_ab57aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='reactionexecution',
            constraint=models.UniqueConstraint(fields=('reaction', 'workflow_execution', 'idempotency_key'), name='uniq_reaction_execution_idempotency'),
        ),
    ]
