# Generated by Django 6.0.1 on 2026-06-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_workflowreaction_reactionexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON Schema 格式，声明工作流对外暴露的稳定输出结构（供工具/端点返回投影）', verbose_name='输出参数 Schema'),
        ),
    ]
