# Generated by Django 6.0.1 on 2026-06-15 04:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0009_remove_v81_legacy_claude_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("feishu_project_key", models.CharField(max_length=64)),
                ("work_item_type", models.CharField(max_length=32)),
                ("work_item_id", models.BigIntegerField()),
                (
                    "feishu_project_simple_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("feishu_webhook", "飞书 webhook"),
                            ("manual", "手动按 ID"),
                            ("bitable_import", "Bitable 历史导入"),
                            ("mr_reverse", "MR 反查"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("status_state_key", models.CharField(blank=True, default="", max_length=64)),
                ("status_sub_stage", models.CharField(blank=True, default="", max_length=64)),
                ("status_display_name", models.CharField(blank=True, default="", max_length=128)),
                ("is_archived_state", models.BooleanField(default=False)),
                ("is_init_state", models.BooleanField(default=False)),
                ("feishu_fields", models.JSONField(default=list)),
                ("prd_url", models.URLField(blank=True, default="", max_length=1000)),
                ("tech_doc_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "business_line_normalized",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("module_normalized", models.CharField(blank=True, default="", max_length=128)),
                ("internal_note", models.TextField(blank=True, default="")),
                ("feishu_chat_id", models.CharField(blank=True, default="", max_length=128)),
                ("field_provenance", models.JSONField(default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_items",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作项",
                "verbose_name_plural": "工作项",
                "db_table": "delivery_work_item",
            },
        ),
        migrations.CreateModel(
            name="WorkItemRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_external_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("belongs_to_project", "所属项目"),
                            ("sprint", "所属迭代"),
                            ("version", "规划/上车版本"),
                            ("related", "关联"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_field_key", models.CharField(max_length=64)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("feishu_field", "飞书关联字段"),
                            ("feishu_relation_api", "飞书关系端点"),
                            ("friday", "Friday 本地"),
                        ],
                        default="feishu_field",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_relations",
                        to="delivery.workitem",
                    ),
                ),
                (
                    "target_work_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_relations",
                        to="delivery.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作项关系",
                "verbose_name_plural": "工作项关系",
                "db_table": "delivery_work_item_relation",
            },
        ),
        migrations.CreateModel(
            name="WorkItemStatusEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pre_state_key", models.CharField(blank=True, default="", max_length=64)),
                ("cur_state_key", models.CharField(blank=True, default="", max_length=64)),
                ("pre_sub_stage", models.CharField(blank=True, default="", max_length=64)),
                ("cur_sub_stage", models.CharField(blank=True, default="", max_length=64)),
                ("operator", models.CharField(blank=True, default="", max_length=128)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="delivery.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作项状态事件",
                "verbose_name_plural": "工作项状态事件",
                "db_table": "delivery_work_item_status_event",
            },
        ),
        migrations.CreateModel(
            name="WorkItemSyncState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "facet",
                    models.CharField(
                        choices=[
                            ("basic_fields", "基础字段"),
                            ("prd_body", "PRD 正文"),
                            ("tech_doc", "技术方案正文"),
                            ("comments", "评论"),
                            ("relations", "关联关系"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "完整"),
                            ("partial", "部分"),
                            ("missing", "缺失"),
                            ("stale", "过期"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("feishu_webhook", "飞书 webhook"),
                            ("manual", "手动按 ID"),
                            ("bitable_import", "Bitable 历史导入"),
                            ("mr_reverse", "MR 反查"),
                        ],
                        max_length=32,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_states",
                        to="delivery.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作项同步状态",
                "verbose_name_plural": "工作项同步状态",
                "db_table": "delivery_work_item_sync_state",
            },
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["project", "work_item_type"], name="delivery_wo_project_823ff4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(fields=["status_state_key"], name="delivery_wo_status__9444e5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="workitem",
            unique_together={("feishu_project_key", "work_item_type", "work_item_id")},
        ),
        migrations.AlterUniqueTogether(
            name="workitemrelation",
            unique_together={
                ("source_work_item", "relation_type", "target_external_id", "source_field_key")
            },
        ),
        migrations.AddIndex(
            model_name="workitemstatusevent",
            index=models.Index(
                fields=["work_item", "event_time"], name="delivery_wo_work_it_3d603d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workitemsyncstate",
            unique_together={("work_item", "facet")},
        ),
    ]
