# Generated by Django 6.0.1 on 2026-06-15 05:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItemCommentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("feishu_comment_id", models.CharField(max_length=128)),
                ("thread_parent_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "根评论创建"),
                            ("replied", "回复"),
                            ("edited", "编辑"),
                            ("deleted", "删除"),
                            ("approval", "审批"),
                        ],
                        max_length=16,
                    ),
                ),
                ("author", models.CharField(blank=True, default="", max_length=128)),
                ("body", models.TextField(blank=True, default="")),
                ("attachments", models.JSONField(default=list)),
                (
                    "approval_semantic",
                    models.CharField(
                        choices=[("none", "无"), ("approve", "通过"), ("reject", "驳回")],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_events",
                        to="delivery.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作项评论事件",
                "verbose_name_plural": "工作项评论事件",
                "db_table": "delivery_work_item_comment_event",
                "indexes": [
                    models.Index(
                        fields=["work_item", "event_time"], name="delivery_wo_work_it_937c2e_idx"
                    )
                ],
            },
        ),
    ]
