# Generated by Django 6.0.1 on 2026-06-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_workitemcommentevent"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workitemcommentevent",
            constraint=models.UniqueConstraint(
                fields=("work_item", "feishu_comment_id", "event_type", "event_time"),
                name="uniq_comment_event_anchor",
            ),
        ),
    ]
