# Generated by Django 6.0.1 on 2026-06-15 07:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0003_workitemcommentevent_uniq_comment_event_anchor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("prd", "PRD"),
                            ("tech_plan", "技术方案"),
                            ("release_note", "上线说明"),
                            ("sdd_spec", "SDD spec"),
                            ("other", "其他"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("external_feishu", "外部飞书"),
                            ("internal_generated", "内部生成"),
                        ],
                        max_length=32,
                    ),
                ),
                ("external_ref", models.CharField(blank=True, default="", max_length=255)),
                ("canonical_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "content_storage",
                    models.CharField(
                        choices=[
                            ("snapshot", "快照"),
                            ("reference", "引用"),
                            ("both", "快照+引用"),
                        ],
                        default="both",
                        max_length=16,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("writeback_allowed", models.BooleanField(default=False)),
                ("feishu_tenant", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="delivery.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "db_table": "delivery_document",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("content", models.TextField(blank=True, default="")),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="delivery.document",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="delivery.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档版本",
                "verbose_name_plural": "文档版本",
                "db_table": "delivery_document_version",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="delivery.documentversion",
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["document", "-version"], name="delivery_do_documen_3c5f55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("document", "version")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["work_item", "document_type"], name="delivery_do_work_it_e0f45a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["feishu_tenant", "external_ref"], name="delivery_do_feishu__f3f635_idx"
            ),
        ),
    ]
