# Generated by Django 6.0.1 on 2026-06-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_document_documentversion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('feishu_tenant', 'external_ref'), name='uniq_document_feishu_tenant_external_ref'),
        ),
    ]
