# Generated by Django 6.0.1 on 2026-06-15 09:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_document_uniq_document_feishu_tenant_external_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('bitable', '多维表格'), ('manual', '手动')], max_length=16)),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('raw_row', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '上线批次',
                'verbose_name_plural': '上线批次',
                'db_table': 'delivery_release_batch',
            },
        ),
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_item_external_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('bitable_record_key', models.CharField(blank=True, default='', max_length=255)),
                ('raw_row', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='delivery.releasebatch')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_records', to='delivery.workitem')),
            ],
            options={
                'verbose_name': '上线记录',
                'verbose_name_plural': '上线记录',
                'db_table': 'delivery_release_record',
            },
        ),
        migrations.CreateModel(
            name='ReleaseArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('mr', '合并请求'), ('branch', '分支'), ('commit', '提交'), ('diff', '差异'), ('release_note', '上线说明'), ('doc', '文档')], max_length=16)),
                ('ref', models.CharField(blank=True, default='', max_length=1000)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='delivery.releaserecord')),
            ],
            options={
                'verbose_name': '上线证据',
                'verbose_name_plural': '上线证据',
                'db_table': 'delivery_release_artifact',
            },
        ),
        migrations.AddIndex(
            model_name='releaserecord',
            index=models.Index(fields=['work_item'], name='delivery_re_work_it_47938a_idx'),
        ),
        migrations.AddIndex(
            model_name='releaserecord',
            index=models.Index(fields=['work_item_external_id'], name='delivery_re_work_it_e254ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='releaserecord',
            constraint=models.UniqueConstraint(condition=models.Q(('bitable_record_key', ''), _negated=True), fields=('bitable_record_key',), name='uniq_release_record_bitable_key'),
        ),
    ]
