# Generated by Django 6.0.1 on 2026-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_releasebatch_releaserecord_releaseartifact'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='releasebatch',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('external_ref',), name='uniq_release_batch_external_ref'),
        ),
    ]
