# Generated by Django 6.0.1 on 2026-06-15 10:59

import uuid

import django.db.models.deletion
from django.db import migrations, models

import delivery.models.ingest_run


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_releasebatch_uniq_release_batch_external_ref'),
        ('projects', '0009_remove_v81_legacy_claude_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_url', models.TextField(blank=True)),
                ('mr_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='running', max_length=16)),
                ('steps', models.JSONField(blank=True, default=delivery.models.ingest_run.default_steps)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_runs', to='projects.project')),
            ],
            options={
                'verbose_name': '一键摄取运行记录',
                'verbose_name_plural': '一键摄取运行记录',
                'db_table': 'delivery_ingest_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='idx_ingest_run_started')],
            },
        ),
    ]
