# Generated by Django 6.0.1 on 2026-06-15 23:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_ingestrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entrypoint', models.CharField(choices=[('workflow', '工作流'), ('chat', '对话')], max_length=16)),
                ('status', models.CharField(choices=[('decomposing', '拆分中'), ('routing', '路由中'), ('recalling', '召回中'), ('clarifying', '澄清中'), ('researching', '并行调研中'), ('merging', '融合中'), ('done', '已完成'), ('failed', '失败')], default='decomposing', max_length=16)),
                ('current_plan_version', models.UUIDField(blank=True, null=True)),
                ('decomposition', models.JSONField(default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_sessions', to='delivery.workitem')),
            ],
            options={
                'verbose_name': '方案编排会话',
                'verbose_name_plural': '方案编排会话',
                'db_table': 'delivery_plan_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='delivery_pl_status_d0e415_idx'), models.Index(fields=['work_item', 'status'], name='delivery_pl_work_it_6bd268_idx')],
            },
        ),
    ]
