# Generated by Django 6.0.1 on 2026-06-16 00:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_plansession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('content', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='delivery.planversion')),
            ],
            options={
                'verbose_name': '方案版本',
                'verbose_name_plural': '方案版本',
                'db_table': 'delivery_plan_version',
            },
        ),
        migrations.CreateModel(
            name='TechnicalPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('chat', '对话'), ('mcp', 'MCP'), ('workflow', '工作流'), ('orchestration', '编排')], max_length=16)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('under_review', '评审中'), ('approved', '已批准'), ('superseded', '已替换'), ('archived', '已归档')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.planversion')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_plans', to='delivery.workitem')),
            ],
            options={
                'verbose_name': '技术方案',
                'verbose_name_plural': '技术方案',
                'db_table': 'delivery_technical_plan',
            },
        ),
        migrations.AddField(
            model_name='planversion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='delivery.technicalplan'),
        ),
        migrations.CreateModel(
            name='PlanExternalRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_ref', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_refs', to='delivery.technicalplan')),
            ],
            options={
                'verbose_name': '方案外部软链',
                'verbose_name_plural': '方案外部软链',
                'db_table': 'delivery_plan_external_ref',
            },
        ),
        migrations.AddIndex(
            model_name='technicalplan',
            index=models.Index(fields=['work_item'], name='delivery_te_work_it_b2c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalplan',
            index=models.Index(fields=['origin', 'status'], name='delivery_te_origin_87ec2e_idx'),
        ),
        migrations.AddIndex(
            model_name='planversion',
            index=models.Index(fields=['plan', '-version'], name='delivery_pl_plan_id_a21b79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together={('plan', 'version')},
        ),
    ]
