# Generated by Django 6.0.1 on 2026-06-16 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_technicalplan_planversion_planexternalref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plansession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plansession',
            name='recall_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plansession',
            name='routing',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
