# Generated by Django 6.0.1 on 2026-06-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_plansession_routing_recall_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansession',
            name='recall_context',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
