# Generated by Django 6.0.1 on 2026-06-16 01:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_plansession_recall_context'),
        ('repositories', '0036_git_instance_credential'),
        ('subagent', '0013_alter_tokenusage_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoResearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待派发'), ('running', '调研中'), ('done', '已完成'), ('failed', '失败'), ('stale', '已过期')], default='pending', max_length=16)),
                ('routed_confidence', models.CharField(blank=True, default='', max_length=16)),
                ('attempt', models.IntegerField(default=0)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repositories.repository')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_tasks', to='delivery.plansession')),
                ('subagent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subagent.subagentsession')),
            ],
            options={
                'verbose_name': '仓库调研子任务',
                'verbose_name_plural': '仓库调研子任务',
                'db_table': 'delivery_repo_research_task',
            },
        ),
        migrations.CreateModel(
            name='PartialPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('valid', models.BooleanField(default=True)),
                ('invalidated_reason', models.CharField(blank=True, default='', max_length=64)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_plans', to='delivery.reporesearchtask')),
            ],
            options={
                'verbose_name': '单仓调研产物',
                'verbose_name_plural': '单仓调研产物',
                'db_table': 'delivery_partial_plan',
            },
        ),
        migrations.AddIndex(
            model_name='reporesearchtask',
            index=models.Index(fields=['session', 'status'], name='delivery_re_session_28590a_idx'),
        ),
        migrations.AddIndex(
            model_name='reporesearchtask',
            index=models.Index(fields=['repository'], name='delivery_re_reposit_d8e6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='partialplan',
            index=models.Index(fields=['research_task', 'valid'], name='delivery_pa_researc_10d6a8_idx'),
        ),
    ]
