# Generated by Django 6.0.1 on 2026-06-16 03:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_reporesearchtask_partialplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merged_plan_version', models.UUIDField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('passed', '通过'), ('failed', '失败')], default='failed', max_length=16)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('attempt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect_merges', to='delivery.plansession')),
            ],
            options={
                'verbose_name': '架构师融合',
                'verbose_name_plural': '架构师融合',
                'db_table': 'delivery_architect_merge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'validation_status'], name='delivery_ar_session_c955d6_idx')],
            },
        ),
    ]
