# Generated by Django 6.0.1 on 2026-06-16 04:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_architectmerge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSessionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('work_item', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.plansession')),
            ],
            options={
                'verbose_name': '方案编排事件',
                'verbose_name_plural': '方案编排事件',
                'db_table': 'delivery_plan_session_event',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'ts'], name='delivery_pl_session_d0609a_idx'), models.Index(fields=['event'], name='delivery_pl_event_e5d47d_idx')],
            },
        ),
    ]
