# Generated by Django 6.0.1 on 2026-06-16 04:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_plansessionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_partials', models.ManyToManyField(blank=True, related_name='+', to='delivery.reporesearchtask')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='delivery.plansession')),
            ],
            options={
                'verbose_name': '澄清问答',
                'verbose_name_plural': '澄清问答',
                'db_table': 'delivery_clarification',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session'], name='delivery_cl_session_29b666_idx')],
            },
        ),
    ]
