# Generated by Django 6.0.1 on 2026-06-16 12:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_clarification'),
        ('repositories', '0036_git_instance_credential'),
        ('subagent', '0013_alter_tokenusage_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoCodingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wave', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '待派发'), ('running', '编码中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('produced_artifacts', models.JSONField(blank=True, default=dict)),
                ('follow_openspec', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=0)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='delivery.repocodingtask')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_tasks', to='delivery.planversion')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repositories.repository')),
                ('subagent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subagent.subagentsession')),
            ],
            options={
                'verbose_name': '仓库编码子任务',
                'verbose_name_plural': '仓库编码子任务',
                'db_table': 'delivery_repo_coding_task',
                'indexes': [models.Index(fields=['plan_version', 'wave', 'status'], name='delivery_re_plan_ve_8b356c_idx'), models.Index(fields=['repository'], name='delivery_re_reposit_45569a_idx')],
            },
        ),
    ]
