# Generated by Django 6.0.1 on 2026-06-17 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_repocodingtask'),
        ('repositories', '0036_git_instance_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='SddSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_review', '评审中'), ('approved', '已批准'), ('implemented', '已落地'), ('archived', '已归档')], default='draft', max_length=16)),
                ('change_kind', models.CharField(choices=[('proposal', '变更提案'), ('delta', '规格增量')], default='proposal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdd_specs', to='delivery.document')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdd_specs', to='delivery.planversion')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repositories.repository')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdd_specs', to='delivery.workitem')),
            ],
            options={
                'verbose_name': 'SDD 规格',
                'verbose_name_plural': 'SDD 规格',
                'db_table': 'delivery_sdd_spec',
                'indexes': [models.Index(fields=['repository'], name='delivery_sd_reposit_dee6de_idx'), models.Index(fields=['work_item'], name='delivery_sd_work_it_0b4244_idx')],
                'unique_together': {('plan_version', 'repository')},
            },
        ),
    ]
