# Generated by Django 6.0.1 on 2026-06-17 02:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_sddspec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SddSpecReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approve', '批准'), ('reject', '驳回')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='delivery.sddspec')),
            ],
            options={
                'verbose_name': 'SDD 规格评审',
                'verbose_name_plural': 'SDD 规格评审',
                'db_table': 'delivery_sdd_spec_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spec', 'created_at'], name='delivery_sd_spec_id_161916_idx')],
            },
        ),
    ]
