# Generated by Django 6.0.1 on 2026-06-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_sddspecreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sddspec',
            name='implementation_prs',
            field=models.JSONField(default=list),
        ),
    ]
