# Generated by Django 6.0.1 on 2026-06-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_ingestrun_batch_id'),
        ('delivery', '0020_sddspec_implementation_prs'),
    ]

    operations = [
    ]
