# Generated by Django 6.0.1 on 2026-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_merge_20260617_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansession',
            name='conversation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
