# Generated by Django 6.0.1 on 2026-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_plansession_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaserecord',
            name='release_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='releaserecord',
            index=models.Index(fields=['batch', '-release_date'], name='delivery_re_batch_i_b70816_idx'),
        ),
    ]
