# Generated by Django 6.0.1 on 2026-06-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_releaserecord_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='durable_job_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ingestrun',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='ingestrun',
            name='status',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='running', max_length=16),
        ),
    ]
