# Generated by Django 6.0.1 on 2026-06-27 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_rename_project_to_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='clarification',
            name='container_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='clarification',
            name='origin_repo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clarification',
            name='plan_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clarification',
            name='round_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClarificationQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('qtype', models.CharField(default='single', max_length=8)),
                ('options', models.JSONField(default=list)),
                ('recommended', models.JSONField(default=list)),
                ('origin_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('selected', models.JSONField(blank=True, null=True)),
                ('freeform_text', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_adopted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='delivery.clarification')),
            ],
            options={
                'verbose_name': '澄清问题',
                'verbose_name_plural': '澄清问题',
                'db_table': 'delivery_clarification_question',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['clarification', 'order'], name='delivery_cl_clarifi_7f5882_idx')],
            },
        ),
    ]
