# Generated by Django 6.0.1 on 2026-06-28 06:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_clarification_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(max_length=40, verbose_name='交付物类型')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('under_review', '评审中'), ('approved', '已批准'), ('superseded', '已替换'), ('archived', '已归档')], default='draft', max_length=16)),
                ('created_by_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='delivery.workitem')),
            ],
            options={
                'verbose_name': '交付物',
                'verbose_name_plural': '交付物',
                'db_table': 'delivery_artifact',
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('content', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('produced_by_session_id', models.CharField(blank=True, default='', max_length=64)),
                ('produced_by_ref', models.CharField(blank=True, default='', max_length=255)),
                ('approval_status', models.CharField(choices=[('none', '无'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='delivery.artifact')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='delivery.artifactversion')),
            ],
            options={
                'verbose_name': '交付物版本',
                'verbose_name_plural': '交付物版本',
                'db_table': 'delivery_artifact_version',
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.artifactversion'),
        ),
        migrations.AddIndex(
            model_name='artifactversion',
            index=models.Index(fields=['artifact', '-version_no'], name='delivery_ar_artifac_8ca364_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactversion',
            index=models.Index(fields=['content_hash'], name='delivery_ar_content_0b3d2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactversion',
            unique_together={('artifact', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['artifact_type', 'status'], name='delivery_ar_artifac_a29281_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['work_item'], name='delivery_ar_work_it_fbadbf_idx'),
        ),
    ]
