# Generated by Django 6.0.1 on 2026-06-28 07:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_artifact_artifactversion_artifact_current_version_and_more'),
        ('repositories', '0039_repository_git_instance_credential'),
        ('subagent', '0014_alter_subagentsession_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvergenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_type', models.CharField(max_length=40, verbose_name='流程类型')),
                ('entrypoint', models.CharField(choices=[('workflow', '工作流'), ('chat', '对话'), ('mcp', 'MCP'), ('webhook', 'Webhook'), ('tool_invoke', '工具调用')], max_length=16)),
                ('status', models.CharField(choices=[('created', '已创建'), ('running', '运行中'), ('waiting_clarification', '等待澄清'), ('waiting_event', '等待事件'), ('done', '已完成'), ('failed', '失败')], default='created', max_length=24)),
                ('current_stage', models.CharField(blank=True, default='', max_length=40)),
                ('stage_state', models.JSONField(blank=True, default=dict)),
                ('conversation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('node_execution_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('initiated_by_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '收敛会话',
                'verbose_name_plural': '收敛会话',
                'db_table': 'delivery_convergence_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConvergenceSessionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('work_item', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收敛会话事件',
                'verbose_name_plural': '收敛会话事件',
                'db_table': 'delivery_convergence_session_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='architectmerge',
            name='merged_artifact_version',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repocodingtask',
            name='artifact_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_tasks', to='delivery.artifactversion'),
        ),
        migrations.AddField(
            model_name='sddspec',
            name='artifact_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdd_specs', to='delivery.artifactversion'),
        ),
        migrations.RemoveField(
            model_name='planexternalref',
            name='canonical',
        ),
        migrations.RemoveIndex(
            model_name='plansession',
            name='delivery_pl_status_d0e415_idx',
        ),
        migrations.RemoveIndex(
            model_name='plansession',
            name='delivery_pl_work_it_6bd268_idx',
        ),
        migrations.RemoveIndex(
            model_name='plansessionevent',
            name='delivery_pl_session_d0609a_idx',
        ),
        migrations.RemoveIndex(
            model_name='plansessionevent',
            name='delivery_pl_event_e5d47d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='planversion',
            name='delivery_pl_plan_id_a21b79_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicalplan',
            name='delivery_te_work_it_b2c02f_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicalplan',
            name='delivery_te_origin_87ec2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='repocodingtask',
            name='delivery_re_plan_ve_8b356c_idx',
        ),
        migrations.RemoveField(
            model_name='architectmerge',
            name='merged_plan_version',
        ),
        migrations.AlterUniqueTogether(
            name='sddspec',
            unique_together={('artifact_version', 'repository')},
        ),
        migrations.AddIndex(
            model_name='repocodingtask',
            index=models.Index(fields=['artifact_version', 'wave', 'status'], name='delivery_re_artifac_b4e797_idx'),
        ),
        migrations.AddField(
            model_name='convergencesession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convergencesession',
            name='current_artifact_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.artifactversion'),
        ),
        migrations.AddField(
            model_name='convergencesession',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convergence_sessions', to='delivery.workitem'),
        ),
        migrations.AlterField(
            model_name='architectmerge',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect_merges', to='delivery.convergencesession'),
        ),
        migrations.AlterField(
            model_name='clarification',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='delivery.convergencesession'),
        ),
        migrations.AlterField(
            model_name='reporesearchtask',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_tasks', to='delivery.convergencesession'),
        ),
        migrations.AddField(
            model_name='convergencesessionevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.convergencesession'),
        ),
        migrations.DeleteModel(
            name='PlanExternalRef',
        ),
        migrations.RemoveField(
            model_name='plansession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='plansession',
            name='work_item',
        ),
        migrations.RemoveField(
            model_name='plansessionevent',
            name='session',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='supersedes',
        ),
        migrations.RemoveField(
            model_name='technicalplan',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='technicalplan',
            name='work_item',
        ),
        migrations.RemoveField(
            model_name='repocodingtask',
            name='plan_version',
        ),
        migrations.RemoveField(
            model_name='sddspec',
            name='plan_version',
        ),
        migrations.AddIndex(
            model_name='convergencesession',
            index=models.Index(fields=['status'], name='delivery_co_status_49086a_idx'),
        ),
        migrations.AddIndex(
            model_name='convergencesession',
            index=models.Index(fields=['process_type', 'status'], name='delivery_co_process_6690bf_idx'),
        ),
        migrations.AddIndex(
            model_name='convergencesession',
            index=models.Index(fields=['work_item', 'status'], name='delivery_co_work_it_4c132d_idx'),
        ),
        migrations.AddIndex(
            model_name='convergencesessionevent',
            index=models.Index(fields=['session', 'ts'], name='delivery_co_session_c55a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='convergencesessionevent',
            index=models.Index(fields=['event'], name='delivery_co_event_29c3e0_idx'),
        ),
        migrations.DeleteModel(
            name='PlanSession',
        ),
        migrations.DeleteModel(
            name='PlanSessionEvent',
        ),
        migrations.DeleteModel(
            name='TechnicalPlan',
        ),
        migrations.DeleteModel(
            name='PlanVersion',
        ),
    ]
