# Generated by Django 6.0.1 on 2026-06-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_convergencesession_convergencesessionevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clarification',
            name='affected_partials',
        ),
    ]
