# Generated by Django 6.0.1 on 2026-06-28 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0029_remove_clarification_affected_partials'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('clarification', '待答澄清'), ('approval', '待审批'), ('risk_ack', '风险确认'), ('takeover', '可接管'), ('reaction_retry', '失败反应重试')], max_length=20, verbose_name='待办类型')),
                ('scope', models.CharField(choices=[('workflow_execution', '工作流执行'), ('process_session', '收敛会话'), ('artifact', '交付物')], max_length=24, verbose_name='作用域')),
                ('subject_id', models.CharField(max_length=64, verbose_name='主体 id')),
                ('assignee_user_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='指派用户 id')),
                ('assignee_role', models.CharField(blank=True, max_length=64, null=True, verbose_name='指派角色')),
                ('status', models.CharField(choices=[('open', '待处理'), ('done', '已处理'), ('skipped', '已跳过'), ('expired', '已超时')], default='open', max_length=12, verbose_name='状态')),
                ('resolution', models.JSONField(blank=True, default=dict, verbose_name='处理结果')),
                ('source_signal', models.CharField(blank=True, default='', max_length=64, verbose_name='来源信号')),
                ('dedup_key', models.CharField(blank=True, default='', max_length=128, verbose_name='物化幂等键')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('artifact_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_tasks', to='delivery.artifactversion', verbose_name='关联产物版本')),
            ],
            options={
                'verbose_name': '人类待办',
                'verbose_name_plural': '人类待办',
                'db_table': 'delivery_human_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'task_type'], name='delivery_hu_status_1589a0_idx'), models.Index(fields=['assignee_user_id', 'status'], name='delivery_hu_assigne_64c944_idx'), models.Index(fields=['scope', 'subject_id'], name='delivery_hu_scope_449475_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedup_key__gt', '')), fields=('dedup_key',), name='uniq_human_task_dedup_key')],
            },
        ),
    ]
