# Generated by Django 6.0.1 on 2026-07-29 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0030_humantask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintReviewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_action', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '蓝图评审人',
                'verbose_name_plural': '蓝图评审人',
                'db_table': 'delivery_blueprint_reviewer',
            },
        ),
        migrations.CreateModel(
            name='BlueprintThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor', models.JSONField(blank=True, null=True)),
                ('anchor_status', models.CharField(choices=[('anchored', '已锚定'), ('orphaned', '已失锚')], default='anchored', max_length=16)),
                ('kind', models.CharField(choices=[('ai_clarification', 'AI 澄清提问'), ('ai_review_finding', 'AI 审查发现'), ('human_comment', '人工评论'), ('repo_confirmation', '仓库确认门')], max_length=24)),
                ('severity', models.CharField(blank=True, choices=[('blocker', '阻塞'), ('warning', '警告'), ('info', '提示')], default='', max_length=16)),
                ('blocking', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', '待处理'), ('answered', '已回答'), ('resolved', '已解决'), ('dismissed', '已忽略')], default='open', max_length=16)),
                ('return_stage', models.CharField(blank=True, default='', max_length=16)),
                ('initiated_by_user_id', models.CharField(default='system', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '蓝图澄清线程',
                'verbose_name_plural': '蓝图澄清线程',
                'db_table': 'delivery_blueprint_thread',
            },
        ),
        migrations.CreateModel(
            name='BlueprintThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_type', models.CharField(choices=[('ai', 'AI'), ('human', '人类')], max_length=8)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '蓝图线程消息',
                'verbose_name_plural': '蓝图线程消息',
                'db_table': 'delivery_blueprint_thread_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='blueprint_status',
            field=models.CharField(blank=True, choices=[('researching', '调研中'), ('drafting', '产出中'), ('ai_reviewing', 'AI 审查中'), ('needs_clarification', '需要澄清'), ('pending_review', '待人类审查'), ('confirmed', '已确认'), ('implementing', '实施中'), ('implemented', '实施完成'), ('archived', '已归档'), ('failed', '已失败'), ('superseded', '已废弃')], default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['artifact_type', 'blueprint_status'], name='delivery_ar_artifac_3c2419_idx'),
        ),
        migrations.AddField(
            model_name='blueprintreviewer',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_reviewers', to='delivery.artifact'),
        ),
        migrations.AddField(
            model_name='blueprintreviewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blueprintthread',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_threads', to='delivery.artifact'),
        ),
        migrations.AddField(
            model_name='blueprintthread',
            name='created_on_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.artifactversion'),
        ),
        migrations.AddField(
            model_name='blueprintthreadmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blueprintthreadmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='delivery.blueprintthread'),
        ),
        migrations.AddConstraint(
            model_name='blueprintreviewer',
            constraint=models.UniqueConstraint(fields=('artifact', 'user'), name='uq_blueprint_reviewer_artifact_user'),
        ),
        migrations.AddIndex(
            model_name='blueprintthread',
            index=models.Index(fields=['artifact', 'status', 'blocking'], name='delivery_bl_artifac_8b8c7e_idx'),
        ),
    ]
