# Generated by Django 6.0.1 on 2026-07-29 23:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0031_blueprint_models"),
        ("initiatives", "0014_project_context_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintContextEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("finding", "调研发现"),
                            ("api_surface", "接口面"),
                            ("contract", "跨仓契约"),
                            ("decision", "决策"),
                            ("dependency_claim", "依赖等待声明"),
                            ("question", "待澄清问题"),
                        ],
                        max_length=24,
                    ),
                ),
                ("repository_id", models.CharField(blank=True, default="", max_length=64)),
                ("content", models.JSONField(default=dict)),
                ("produced_by", models.CharField(default="system", max_length=64)),
                ("seq", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "生效中"), ("superseded", "已废弃")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("initiated_by_user_id", models.CharField(default="system", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "convergence_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_context_entries",
                        to="delivery.convergencesession",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_context_entries",
                        to="initiatives.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "蓝图上下文总线条目",
                "verbose_name_plural": "蓝图上下文总线条目",
                "db_table": "delivery_blueprint_context_entry",
                "ordering": ["seq"],
                "indexes": [
                    models.Index(
                        fields=["convergence_session", "seq"], name="delivery_bl_converg_fccf3b_idx"
                    ),
                    models.Index(
                        fields=["convergence_session", "key"], name="delivery_bl_converg_f65b9b_idx"
                    ),
                    models.Index(
                        fields=["convergence_session", "kind", "status"],
                        name="delivery_bl_converg_21642a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("convergence_session", "seq"),
                        name="uq_blueprint_context_session_seq",
                    )
                ],
            },
        ),
    ]
