# Generated by Django 6.0.1 on 2026-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0032_blueprint_context_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintthread',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
