# Generated by Django 6.0.1 on 2026-08-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0034_blueprintthread_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convergencesession',
            name='drive_lease_owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='convergencesession',
            name='drive_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='convergencesession',
            index=models.Index(fields=['drive_lease_until'], name='delivery_co_drive_l_a41a0a_idx'),
        ),
    ]
