# Generated by Django 6.0.1 on 2026-06-25 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_rename_project_to_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('status', models.CharField(choices=[('developing', '开发中'), ('archived', '归档'), ('terminated', '终止')], default='developing', max_length=20, verbose_name='状态')),
                ('feishu_project_key', models.CharField(blank=True, default='', help_text="飞书'项目跟踪'看板的 project_key；非空时与 space 构成幂等键", max_length=100, verbose_name='飞书项目 Key')),
                ('feishu_board_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='飞书看板链接')),
                ('feishu_board_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书看板 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.space', verbose_name='所属空间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'initiative_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='关联备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='initiatives.project', verbose_name='源项目')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='initiatives.project', verbose_name='目标项目')),
            ],
            options={
                'verbose_name': '项目关联',
                'verbose_name_plural': '项目关联',
                'db_table': 'initiative_project_relations',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='initiatives.ProjectRelation', to='initiatives.project'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '主R'), ('pm', '产品经理'), ('frontend', '前端'), ('backend', '后端'), ('qa', '测试')], default='backend', max_length=20, verbose_name='身份角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='initiatives.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'db_table': 'initiative_project_members',
                'indexes': [models.Index(fields=['project', 'role'], name='initiative__project_f2ae40_idx'), models.Index(fields=['user'], name='initiative__user_id_b56c62_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member_user'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('project',), name='uniq_project_single_owner')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='uniq_project_relation_pair'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['space', 'status'], name='initiative__space_i_c9c7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['feishu_project_key'], name='initiative__feishu__207d14_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('feishu_project_key', ''), _negated=True), fields=('space', 'feishu_project_key'), name='uniq_project_space_feishu_key'),
        ),
    ]
