# Generated by Django 6.0.1 on 2026-06-25 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_rename_project_to_space'),
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkItemLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provenance', models.CharField(choices=[('board_derived', '看板派生'), ('manual', '手动并入')], default='manual', max_length=20, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_links', to='initiatives.project', verbose_name='项目')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='delivery.workitem', verbose_name='工作项')),
            ],
            options={
                'verbose_name': '项目工作项关联',
                'verbose_name_plural': '项目工作项关联',
                'db_table': 'initiative_project_work_item_links',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='work_items',
            field=models.ManyToManyField(blank=True, related_name='projects', through='initiatives.ProjectWorkItemLink', to='delivery.workitem'),
        ),
        migrations.AddIndex(
            model_name='projectworkitemlink',
            index=models.Index(fields=['project', 'provenance'], name='initiative__project_a9e9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectworkitemlink',
            index=models.Index(fields=['work_item'], name='initiative__work_it_67ba93_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectworkitemlink',
            constraint=models.UniqueConstraint(fields=('project', 'work_item'), name='uniq_project_work_item_link'),
        ),
    ]
