# Generated by Django 6.0.1 on 2026-06-25 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_projectworkitemlink_project_work_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True, verbose_name='类型标识')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('carrier', models.CharField(choices=[('feishu_doc', '飞书文档'), ('feishu_bitable', '飞书多维表格'), ('external_link', '外部链接'), ('markdown', 'Markdown'), ('repo_file', '仓库文件')], default='external_link', max_length=20, verbose_name='默认载体')),
                ('ragable', models.BooleanField(default=False, verbose_name='可全文 RAG')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('builtin', models.BooleanField(default=False, verbose_name='内置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工件类型',
                'verbose_name_plural': '工件类型',
                'db_table': 'initiative_artifact_types',
                'ordering': ['-builtin', 'key'],
                'indexes': [models.Index(fields=['enabled'], name='initiative__enabled_5cc3e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(choices=[('feishu_doc', '飞书文档'), ('feishu_bitable', '飞书多维表格'), ('external_link', '外部链接'), ('markdown', 'Markdown'), ('repo_file', '仓库文件')], max_length=20, verbose_name='载体')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('url', models.CharField(blank=True, default='', help_text='外链 / 飞书文档·表格链接', max_length=1000, verbose_name='链接')),
                ('content_ref', models.TextField(blank=True, default='', help_text='md/内部工件正文，或仓库文件路径引用', verbose_name='内容引用')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_artifacts', to=settings.AUTH_USER_MODEL, verbose_name='贡献者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='initiatives.project', verbose_name='项目')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='initiatives.artifacttype', verbose_name='类型')),
            ],
            options={
                'verbose_name': '工件',
                'verbose_name_plural': '工件',
                'db_table': 'initiative_artifacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'type'], name='initiative__project_965efc_idx'), models.Index(fields=['carrier'], name='initiative__carrier_5f2aab_idx')],
            },
        ),
    ]
