# Generated by Django 6.0.1 on 2026-06-25 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_rename_project_to_space'),
        ('initiatives', '0004_seed_artifact_types'),
        ('repositories', '0039_repository_git_instance_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=20, verbose_name='平台')),
                ('external_id', models.CharField(blank=True, default='', max_length=100, verbose_name='平台外部 id（PR/MR 编号）')),
                ('url', models.URLField(blank=True, default='', max_length=1000, verbose_name='MR/PR 链接')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='标题')),
                ('source_branch', models.CharField(blank=True, default='', max_length=255, verbose_name='源分支')),
                ('target_branch', models.CharField(blank=True, default='', max_length=255, verbose_name='目标分支')),
                ('status', models.CharField(choices=[('open', '打开'), ('merged', '已合并'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('review_status', models.CharField(blank=True, default='', help_text='如 approved/changes_requested/commented（平台原值归一）', max_length=40, verbose_name='review 状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='initiatives.project', verbose_name='项目')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='repositories.repository', verbose_name='仓库')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='delivery.workitem', verbose_name='工作项')),
            ],
            options={
                'verbose_name': 'Merge Request',
                'verbose_name_plural': 'Merge Requests',
                'db_table': 'initiative_merge_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MergeRequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64, verbose_name='事件类型')),
                ('dedup_key', models.CharField(max_length=255, unique=True, verbose_name='幂等去重键')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='脱敏原始 payload')),
                ('initiated_by_user_id', models.CharField(blank=True, default='system', max_length=64, verbose_name='触发用户')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='initiatives.mergerequest', verbose_name='MR 实体')),
            ],
            options={
                'verbose_name': 'MR 事件',
                'verbose_name_plural': 'MR 事件',
                'db_table': 'initiative_merge_request_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='记忆内容')),
                ('status', models.CharField(choices=[('active', '生效'), ('superseded', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_memories', to=settings.AUTH_USER_MODEL, verbose_name='贡献者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='initiatives.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目记忆',
                'verbose_name_plural': '项目记忆',
                'db_table': 'initiative_project_memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMemoryDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='草稿内容（已脱敏）')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认入库'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('source_conversation_id', models.UUIDField(blank=True, null=True, verbose_name='来源会话（软引用）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_drafts', to='initiatives.projectmemory', verbose_name='确认入库后的记忆')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_drafts', to='initiatives.project', verbose_name='项目')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_memory_drafts', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '项目记忆草稿',
                'verbose_name_plural': '项目记忆草稿',
                'db_table': 'initiative_project_memory_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMemoryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容快照')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_memory_revisions', to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='initiatives.projectmemory', verbose_name='记忆条目')),
            ],
            options={
                'verbose_name': '项目记忆修订',
                'verbose_name_plural': '项目记忆修订',
                'db_table': 'initiative_project_memory_revisions',
                'ordering': ['memory', 'edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mergerequest',
            index=models.Index(fields=['project', 'status'], name='initiative__project_265840_idx'),
        ),
        migrations.AddIndex(
            model_name='mergerequest',
            index=models.Index(fields=['platform', 'external_id'], name='initiative__platfor_a03c64_idx'),
        ),
        migrations.AddConstraint(
            model_name='mergerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('platform', 'repository', 'external_id'), name='uniq_mr_platform_repo_external'),
        ),
        migrations.AddIndex(
            model_name='mergerequestevent',
            index=models.Index(fields=['merge_request', '-created_at'], name='initiative__merge_r_66a58e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemory',
            index=models.Index(fields=['project', 'status'], name='initiative__project_20f2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemorydraft',
            index=models.Index(fields=['project', 'status'], name='initiative__project_56a6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmemoryrevision',
            index=models.Index(fields=['memory', 'edited_at'], name='initiative__memory__afa884_idx'),
        ),
    ]
