# Generated by Django 6.0.1 on 2026-06-26 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_mergerequest_mergerequestevent_projectmemory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feishu_folder_token',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='飞书工作区文件夹 token'),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public_org', '全员可读'), ('members_only', '仅成员')], default='public_org', max_length=20, verbose_name='可见性'),
        ),
        migrations.CreateModel(
            name='ProjectDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('memory', '记忆'), ('state', '状态'), ('milestones', '里程碑'), ('research', '调研'), ('preflight', '预检')], max_length=20, verbose_name='文件类型')),
                ('feishu_document_id', models.CharField(blank=True, default='', max_length=200, verbose_name='飞书文档 ID')),
                ('feishu_doc_token', models.CharField(blank=True, default='', max_length=200, verbose_name='飞书文档 token')),
                ('last_synced_revision', models.BigIntegerField(default=0, verbose_name='最近同步 revision')),
                ('last_synced_snapshot', models.TextField(blank=True, default='', verbose_name='最近同步快照')),
                ('sync_status', models.CharField(choices=[('pending', '待创建'), ('ready', '已就绪'), ('broken', '失效待重建')], default='pending', max_length=20, verbose_name='同步状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='initiatives.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件',
                'db_table': 'initiative_project_docs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocBlockMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feishu_block_id', models.CharField(max_length=200, verbose_name='飞书 block id')),
                ('db_ref', models.CharField(blank=True, default='', max_length=200, verbose_name='库内引用')),
                ('section', models.CharField(choices=[('system', '系统区'), ('human', '人工区')], default='system', max_length=20, verbose_name='区段')),
                ('content_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='内容指纹')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_maps', to='initiatives.projectdoc', verbose_name='所属文件')),
            ],
            options={
                'verbose_name': '项目文件 block 映射',
                'verbose_name_plural': '项目文件 block 映射',
                'db_table': 'initiative_project_doc_block_maps',
            },
        ),
        migrations.CreateModel(
            name='ProjectStateApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10, verbose_name='HTTP 方法')),
                ('path', models.CharField(max_length=500, verbose_name='路径')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('status', models.CharField(choices=[('planned', '待开发'), ('implemented', '已完成'), ('deprecated', '已废弃')], default='planned', max_length=20, verbose_name='状态')),
                ('source', models.CharField(choices=[('manual', '手动'), ('agent', 'Agent'), ('hook', 'IDE 回写')], default='manual', max_length=20, verbose_name='贡献来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_apis', to='initiatives.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目 API 清单',
                'verbose_name_plural': '项目 API 清单',
                'db_table': 'initiative_project_state_apis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectdoc',
            index=models.Index(fields=['project', 'doc_type'], name='initiative__project_b1b4ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectdoc',
            constraint=models.UniqueConstraint(fields=('project', 'doc_type'), name='uniq_project_doc_type'),
        ),
        migrations.AddIndex(
            model_name='projectdocblockmap',
            index=models.Index(fields=['doc', 'section'], name='initiative__doc_id_fcbd57_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectdocblockmap',
            constraint=models.UniqueConstraint(fields=('doc', 'feishu_block_id'), name='uniq_doc_block'),
        ),
        migrations.AddIndex(
            model_name='projectstateapi',
            index=models.Index(fields=['project', 'status'], name='initiative__project_246ad7_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectstateapi',
            constraint=models.UniqueConstraint(fields=('project', 'method', 'path'), name='uniq_project_state_api'),
        ),
    ]
