# Generated by Django 6.0.1 on 2026-06-26 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_project_workspace_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdoc',
            name='last_feishu_edit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近飞书编辑时间'),
        ),
        migrations.AddField(
            model_name='projectdoc',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='已订阅飞书编辑事件'),
        ),
        migrations.CreateModel(
            name='ProjectDocBlockRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feishu_block_id', models.CharField(max_length=200, verbose_name='飞书 block id')),
                ('db_ref', models.CharField(blank=True, default='', max_length=200, verbose_name='库内引用')),
                ('content', models.TextField(verbose_name='留痕内容')),
                ('source', models.CharField(default='system', max_length=20, verbose_name='来源')),
                ('reason', models.CharField(blank=True, default='', max_length=40, verbose_name='留痕原因')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='捕获时间')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_revisions', to='initiatives.projectdoc', verbose_name='所属文件')),
            ],
            options={
                'verbose_name': '项目文件 block 留痕',
                'verbose_name_plural': '项目文件 block 留痕',
                'db_table': 'initiative_project_doc_block_revisions',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['doc', 'feishu_block_id'], name='initiative__doc_id_0c31cd_idx')],
            },
        ),
    ]
