# Generated by Django 6.0.1 on 2026-06-26 18:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("initiatives", "0007_doc_sync_engine"),
        ("repositories", "0039_repository_git_instance_credential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("branch_name", models.CharField(max_length=255, verbose_name="分支名")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "手动绑定"),
                            ("plan", "方案流水线"),
                            ("coding", "编码自动"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="绑定来源",
                    ),
                ),
                (
                    "feishu_board_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="冗余项目看板 id，便于 branch↔board 反查（绑定时按需携带）",
                        max_length=100,
                        verbose_name="飞书看板 ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_branches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="绑定者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_bindings",
                        to="initiatives.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_branch_bindings",
                        to="repositories.repository",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目分支绑定",
                "verbose_name_plural": "项目分支绑定",
                "db_table": "initiative_project_branches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["branch_name"], name="initiative__branch__540c5b_idx"),
                    models.Index(
                        fields=["repository", "branch_name"], name="initiative__reposit_0708b6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "repository", "branch_name"),
                        name="uniq_project_repo_branch",
                    )
                ],
            },
        ),
    ]
