# Generated by Django 6.0.1 on 2026-06-26 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_rename_project_to_space'),
        ('initiatives', '0009_project_feishu_chat_id'),
        ('repositories', '0039_repository_git_instance_credential'),
        ('subagent', '0014_alter_subagentsession_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('proposed', '已提案'), ('confirmed', '已确认'), ('verifying', '校验中'), ('verified', '已验证'), ('rejected', '已拒绝')], default='proposed', max_length=16)),
                ('score', models.FloatField(default=0.0)),
                ('confidence', models.CharField(blank=True, default='', max_length=16)),
                ('routed_reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='router_v2', max_length=32)),
                ('matched_node_paths', models.JSONField(blank=True, default=list)),
                ('initiated_by_user_id', models.CharField(blank=True, default='system', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_associations', to='initiatives.project')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repositories.repository')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.workitem')),
            ],
            options={
                'verbose_name': '项目仓库关联',
                'verbose_name_plural': '项目仓库关联',
                'db_table': 'initiative_repo_association',
            },
        ),
        migrations.CreateModel(
            name='RepoVerifyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待派发'), ('running', '校验中'), ('done', '已完成'), ('failed', '失败'), ('stale', '已过期')], default='pending', max_length=16)),
                ('attempt', models.IntegerField(default=0)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('verdict', models.JSONField(blank=True, default=dict)),
                ('initiated_by_user_id', models.CharField(blank=True, default='system', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_tasks', to='initiatives.repoassociation')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repositories.repository')),
                ('subagent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subagent.subagentsession')),
            ],
            options={
                'verbose_name': '仓库校验子任务',
                'verbose_name_plural': '仓库校验子任务',
                'db_table': 'initiative_repo_verify_task',
            },
        ),
        migrations.AddIndex(
            model_name='repoassociation',
            index=models.Index(fields=['project', 'status'], name='initiative__project_79818f_idx'),
        ),
        migrations.AddIndex(
            model_name='repoassociation',
            index=models.Index(fields=['repository'], name='initiative__reposit_73b484_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repoassociation',
            unique_together={('project', 'repository')},
        ),
        migrations.AddIndex(
            model_name='repoverifytask',
            index=models.Index(fields=['association', 'status'], name='initiative__associa_b6422c_idx'),
        ),
        migrations.AddIndex(
            model_name='repoverifytask',
            index=models.Index(fields=['repository'], name='initiative__reposit_5c946a_idx'),
        ),
    ]
