# Generated by Django 6.0.1 on 2026-07-03 04:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0013_feature_detail_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContextLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_kind', models.CharField(choices=[('knowledge', '知识实体'), ('artifact', '外部工件'), ('merge_request', 'MR/PR'), ('external', '外部链接')], max_length=20, verbose_name='目标类型')),
                ('target_id', models.UUIDField(blank=True, null=True, verbose_name='目标 id')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='标题快照')),
                ('url', models.CharField(blank=True, default='', max_length=1000, verbose_name='链接')),
                ('score', models.FloatField(default=0.0, verbose_name='相关性分')),
                ('reason', models.TextField(blank=True, default='', verbose_name='关联理由')),
                ('origin', models.CharField(choices=[('ai', 'AI 生成'), ('manual', '人工添加')], default='ai', max_length=10, verbose_name='来源')),
                ('status', models.CharField(choices=[('proposed', '待确认'), ('accepted', '已关联'), ('rejected', '已拒绝')], default='proposed', max_length=10, verbose_name='状态')),
                ('initiated_by_user_id', models.CharField(blank=True, default='system', max_length=64, verbose_name='触发用户')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_links', to='initiatives.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目上下文关联',
                'verbose_name_plural': '项目上下文关联',
                'db_table': 'initiative_context_links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='initiative__project_1c2aa2_idx'), models.Index(fields=['project', 'target_kind'], name='initiative__project_ba1b5b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('target_id__isnull', False)), fields=('project', 'target_kind', 'target_id'), name='uniq_context_link_project_kind_target')],
            },
        ),
    ]
