# Generated by Django 6.0.1 on 2026-08-28 07:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("initiatives", "0014_project_context_link"),
        ("repositories", "0042_repo_charter_append_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionCapture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.TextField(verbose_name="问题（已脱敏）")),
                ("answer", models.TextField(verbose_name="可见答案精华（已脱敏）")),
                (
                    "response_model",
                    models.CharField(default="unknown", max_length=128, verbose_name="响应模型"),
                ),
                (
                    "provider",
                    models.CharField(default="unknown", max_length=64, verbose_name="模型供应商"),
                ),
                (
                    "input_tokens",
                    models.CharField(default="unknown", max_length=64, verbose_name="输入 token"),
                ),
                (
                    "output_tokens",
                    models.CharField(default="unknown", max_length=64, verbose_name="输出 token"),
                ),
                ("session_id", models.CharField(max_length=255, verbose_name="会话标识")),
                ("question_hash", models.CharField(max_length=64, verbose_name="规范化问题哈希")),
                ("link_reason", models.CharField(max_length=64, verbose_name="挂钩结果")),
                (
                    "branch_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="分支"),
                ),
                (
                    "initiated_by_user_id",
                    models.CharField(
                        blank=True, default="system", max_length=64, verbose_name="触发用户"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_eval", "待评估"),
                            ("eval_failed", "评估失败"),
                            ("ingest_pending", "待入图"),
                            ("evaluated", "已评估"),
                        ],
                        default="pending_eval",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_captures",
                        to="initiatives.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_captures",
                        to="repositories.repository",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "会话 Capture",
                "verbose_name_plural": "会话 Captures",
                "db_table": "initiative_session_captures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["initiated_by_user_id", "session_id"],
                        name="initiative__initiat_a7c986_idx",
                    ),
                    models.Index(
                        fields=["repository", "status"], name="initiative__reposit_465d44_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="initiative__status_dbfbff_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("initiated_by_user_id", "session_id", "question_hash"),
                        name="uniq_session_capture_user_session_question",
                    )
                ],
            },
        ),
    ]
