# Generated by Django 6.0.1 on 2026-03-06 06:56
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('projects', '0003_add_claude_default_model'),
 ]
 operations = [
 migrations.CreateModel(
 name='Conversation',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('title', models.CharField(default='新对话', max_length=200)),
 ('is_deleted', models.BooleanField(db_index=True, default=False)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project')),
 ],
 options={
 'verbose_name': '对话',
 'verbose_name_plural': '对话',
 'db_table': 'conversations',
 'ordering': ['-updated_at'],
 },
 ),
 migrations.CreateModel(
 name='Message',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统'), ('tool', '工具')], max_length=20)),
 ('content', models.TextField(blank=True, default='')),
 ('tool_calls', models.JSONField(blank=True, null=True)),
 ('tool_call_id', models.CharField(blank=True, default='', max_length=64)),
 ('metadata', models.JSONField(blank=True, default=dict)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
 ],
 options={
 'verbose_name': '消息',
 'verbose_name_plural': '消息',
 'db_table': 'messages',
 'ordering': ['created_at'],
 'indexes': [models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx')],
 },
 ),
 ]
