# Generated by Django 6.0.1 on 2026-03-06 10:25
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('chat', '0001_initial'),
 ]
 operations = [
 migrations.AddField(
 model_name='conversation',
 name='model',
 field=models.CharField(blank=True, default='', help_text='LLM 模型 ID，为空时使用系统默认模型', max_length=100),
 ),
 ]
