# Generated by Django 6.0.1 on 2026-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='provider_type',
            field=models.CharField(blank=True, help_text='LLM Provider 类型，为空时继承上层配置', max_length=50, null=True, verbose_name='Provider 类型'),
        ),
    ]
