# Generated by Django 6.0.1 on 2026-04-08 07:43
import uuid
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('chat', '0004_chatpushsubscription'),
 ('repositories', '0011_add_file_index_model'),
 ('subagent', '0011_tokenusage_provider_type'),
 ]
 operations = [
 migrations.CreateModel(
 name='CodingSession',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('status', models.CharField(choices=[('draft', '方案草稿'), ('confirmed', '已确认'), ('running', '执行中'), ('completed', '已完成'), ('failed', '已失败')], default='draft', max_length=20)),
 ('tech_plan', models.TextField(verbose_name='技术方案 (Markdown)')),
 ('affected_files', models.JSONField(default=list, verbose_name='影响文件列表')),
 ('revision_count', models.IntegerField(default=0, verbose_name='修订次数')),
 ('branch_name', models.CharField(blank=True, default='', max_length=255)),
 ('pr_url', models.URLField(blank=True, default='')),
 ('error_message', models.TextField(blank=True, default='')),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_sessions', to='chat.conversation')),
 ('message', models.ForeignKey(blank=True, help_text='创建该方案的 AI 消息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_sessions', to='chat.message')),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_sessions', to='repositories.repository')),
 ('subagent_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_session', to='subagent.subagentsession')),
 ],
 options={
 'verbose_name': '编码会话',
 'verbose_name_plural': '编码会话',
 'db_table': 'coding_sessions',
 'ordering': ['-created_at'],
 'indexes': [models.Index(fields=['conversation', 'status'], name='coding_sess_convers_288c56_idx')],
 },
 ),
 ]
