# Generated by Django 6.0.1 on 2026-04-09 12:09
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('chat', '0005_add_coding_session'),
 ]
 operations = [
 migrations.AddField(
 model_name='codingsession',
 name='confirmation_step',
 field=models.CharField(blank=True, default='', help_text='awaiting_confirmation 状态下标识具体确认类型: commit_message, pr_review', max_length=50, verbose_name='当前确认步骤'),
 ),
 migrations.AddField(
 model_name='codingsession',
 name='suggested_commit_message',
 field=models.TextField(blank=True, default='', help_text='Phase 容器回传，支持页面刷新后恢复', verbose_name='AI 建议的 commit message'),
 ),
 migrations.AlterField(
 model_name='codingsession',
 name='status',
 field=models.CharField(choices=[('draft', '方案草稿'), ('confirmed', '已确认'), ('running', '执行中'), ('awaiting_confirmation', '等待确认'), ('completed', '已完成'), ('failed', '已失败')], default='draft', max_length=30),
 ),
 ]
