# Generated by Django 6.0.1 on 2026-04-09 15:21
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('chat', '0006_codingsession_confirmation_step_and_more'),
 ]
 operations = [
 migrations.AddField(
 model_name='codingsession',
 name='suggested_pr_description',
 field=models.TextField(blank=True, default='', help_text='generate_pr_draft 节点生成，支持页面刷新后恢复', verbose_name='AI 建议的 PR 描述'),
 ),
 migrations.AddField(
 model_name='codingsession',
 name='suggested_pr_title',
 field=models.CharField(blank=True, default='', help_text='generate_pr_draft 节点生成，支持页面刷新后恢复', max_length=200, verbose_name='AI 建议的 PR 标题'),
 ),
 ]
