# Generated by Django 6.0.1 on 2026-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_codingsession_conflict_check_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='provider_type',
            field=models.CharField(blank=True, help_text='LLM Provider 类型，为空时继承上层配置 [v21.0 deprecated, will be removed after initial implementation UI cuts over to ProviderCredential]', max_length=50, null=True, verbose_name='Provider 类型'),
        ),
    ]
