# Generated by Django 6.0.1 on 2026-05-20 10:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_v81_legacy_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingsession',
            name='affected_files',
            field=models.JSONField(default=list, help_text='initial implementation 起 deprecated：优先使用 coding_plan.affected_files；本字段保留至 v26.1 清理', verbose_name='影响文件列表'),
        ),
        migrations.AlterField(
            model_name='codingsession',
            name='tech_plan',
            field=models.TextField(help_text='initial implementation 起 deprecated：优先使用 coding_plan.tech_plan；本字段保留至 v26.1 清理', verbose_name='技术方案 (Markdown)'),
        ),
        migrations.CreateModel(
            name='CodingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='方案标题')),
                ('tech_plan', models.TextField(verbose_name='技术方案 (Markdown)')),
                ('affected_files', models.JSONField(default=list, help_text='schema: [{"file_path": str, "change_type": str}]', verbose_name='影响文件列表')),
                ('feishu_doc_token', models.CharField(blank=True, default='', max_length=64, verbose_name='飞书文档 token')),
                ('feishu_doc_url', models.CharField(blank=True, default='', max_length=500, verbose_name='飞书文档 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_plans', to='chat.conversation')),
            ],
            options={
                'verbose_name': '编码方案',
                'verbose_name_plural': '编码方案',
                'db_table': 'coding_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='codingsession',
            name='coding_plan',
            field=models.ForeignKey(blank=True, help_text='initial implementation：tech_plan / affected_files 拆出 CodingPlan 后的关联；过渡期为空，由 migrate_coding_sessions_to_plans 命令回填', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_sessions', to='chat.codingplan'),
        ),
        migrations.AddIndex(
            model_name='codingplan',
            index=models.Index(fields=['conversation', '-created_at'], name='coding_plan_convers_3d1c87_idx'),
        ),
    ]
