# Generated by Django 6.0.1 on 2026-05-20 14:09
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('chat', '0012_codingplan_and_session_fk'),
 ('repositories', '0026_repository_graph_build_progress'),
 ('subagent', '0013_alter_tokenusage_provider_type'),
 ]
 operations = [
 migrations.AddIndex(
 model_name='codingsession',
 index=models.Index(fields=['coding_plan', 'status'], name='idx_codingsession_plan_status'),
 ),
 migrations.AddConstraint(
 model_name='codingsession',
 constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'confirmed', 'running', 'awaiting_confirmation'])), fields=('coding_plan', 'repository'), name='unique_active_plan_repo'),
 ),
 ]
