# Generated by Django 6.0.1 on 2026-05-20 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_nullable_session_project_user'),
        ('chat', '0013_codingsession_unique_active_plan_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryRoutingTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text='触发本次路由的用户 query')),
                ('candidates', models.JSONField(default=list, help_text='[{repository_id, repository_name, score, level, evidence, selected_by_ai, selected_by_user_final}]')),
                ('threshold', models.FloatField(default=0.5, help_text='本次决策用的截断阈值（≥ 阈值自动 selected_by_ai=True）')),
                ('triggered_by', models.CharField(choices=[('chat_tool', 'Chat 工具调用'), ('deep_analysis_completion', '深度分析完成'), ('manual_override', '用户手动微调')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_session', models.ForeignKey(blank=True, help_text='关联 deep_analysis AgentSession；chat_tool / manual_override 路径为 None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_traces', to='agents.agentsession')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_traces', to='chat.conversation')),
            ],
            options={
                'verbose_name': '跨仓路由决策 trace',
                'verbose_name_plural': '跨仓路由决策 traces',
                'db_table': 'repository_routing_traces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='routing_trace_conv_idx'), models.Index(fields=['agent_session'], name='routing_trace_session_idx'), models.Index(fields=['triggered_by', 'created_at'], name='routing_trace_trigger_idx')],
            },
        ),
    ]
