# Generated by Django 6.0.1 on 2026-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_repository_routing_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingplan',
            name='recommended_repository_ids',
            field=models.JSONField(blank=True, default=list, help_text='[str(UUID), ...] —— AI 识别的相关仓库 UUID 列表；不传则 Server 自动从 conversation 最近一条 RepositoryRoutingTrace 取 selected_by_user_final=True 的仓库（initial implementation）。', verbose_name='推荐仓库 ID 列表'),
        ),
    ]
