# Generated by Django 6.0.1 on 2026-06-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_backfill_conversation_created_by'),
        ('projects', '0009_remove_v81_legacy_claude_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project'),
        ),
    ]
