# Generated by Django 6.0.1 on 2026-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_conversation_project_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryroutingtrace',
            name='router_version',
            field=models.CharField(default='legacy_hybrid', help_text='路由实现版本，供 v1/v2 相关度对照分析', max_length=20),
        ),
    ]
