# Generated by Django 6.0.1 on 2026-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_conversation_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsession',
            name='sdk_session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='容器 ResultMessage.session_id，用于 re-dispatch 时 resume 续跑', max_length=128, verbose_name='Claude Code SDK 会话 ID'),
        ),
        migrations.AddField(
            model_name='codingsession',
            name='sdk_session_saved_at',
            field=models.DateTimeField(blank=True, help_text='transcript 落库时间；7 天定时清理以此为准', null=True, verbose_name='SDK 会话保存时间'),
        ),
        migrations.AddField(
            model_name='codingsession',
            name='sdk_transcript',
            field=models.TextField(blank=True, default='', help_text='Claude Code SDK 对话 transcript（jsonl 文本）。resume 时容器拉回还原到 ~/.claude 后 ClaudeAgentOptions(resume=...) 续跑；超大小上限则置空走语义重建回退。', verbose_name='SDK 会话 transcript'),
        ),
    ]
