# Generated by Django 6.0.1 on 2026-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_codingsession_sdk_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsession',
            name='target_branch',
            field=models.CharField(blank=True, default='', help_text='用户在启动编码时选定的合并目标分支，PR 创建时使用；为空时回退到仓库默认分支', max_length=255, verbose_name='PR 目标分支'),
        ),
    ]
