# Generated by Django 6.0.1 on 2026-06-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_rename_project_to_space'),
        ('projects', '0010_rename_project_to_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.space'),
        ),
    ]
