# Generated by Django 6.0.1 on 2026-06-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_alter_conversation_space'),
        ('initiatives', '0005_mergerequest_mergerequestevent_projectmemory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='bound_project',
            field=models.ForeignKey(blank=True, help_text='绑定的项目聚合根（RECALL-02，区别于 space 组织单元）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_conversations', to='initiatives.project'),
        ),
    ]
