# Generated by Django 6.0.1 on 2026-06-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_conversation_bound_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsession',
            name='parked_at',
            field=models.DateTimeField(blank=True, help_text='5min 无回复挂起停容器的时间戳（PLAN-03，审计/恢复诊断用）', null=True, verbose_name='容器挂起时间'),
        ),
        migrations.AlterField(
            model_name='codingsession',
            name='status',
            field=models.CharField(choices=[('draft', '方案草稿'), ('confirmed', '已确认'), ('running', '执行中'), ('awaiting_confirmation', '等待确认'), ('completed', '已完成'), ('failed', '已失败'), ('suspended', '已挂起')], default='draft', max_length=30),
        ),
    ]
