# Generated by Django 6.0.1 on 2026-06-27 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_codingsession_parked_at_alter_codingsession_status'),
        ('initiatives', '0010_repo_association'),
        ('projects', '0010_rename_project_to_space'),
        ('system', '0013_alter_providercredential_scope_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='visibility',
            field=models.CharField(choices=[('personal', '个人'), ('shared', '项目共享')], db_index=True, default='personal', help_text='会话可见性（personal=仅创建者 / shared=项目共享只读）', max_length=16),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bound_project', 'visibility', 'is_deleted', 'is_archived'], name='conversatio_bound_p_c1a81c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bound_project', 'created_by'], name='conversatio_bound_p_1fc9bb_idx'),
        ),
    ]
