# Generated by Django 6.0.1 on 2026-06-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_conversation_visibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingplan',
            name='canonical_plan_id',
        ),
    ]
