# Generated by Django 6.0.1 on 2026-07-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_remove_codingplan_canonical_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryroutingtrace',
            name='block_order',
            field=models.JSONField(blank=True, default=list, help_text='呈现层区顺序，如 ["in_project", "global"]；长度 2 表示有项目上下文'),
        ),
        migrations.AddField(
            model_name='repositoryroutingtrace',
            name='degrade_reason',
            field=models.CharField(blank=True, default='', help_text='用户可见降级原因（6 值闭集 ∪ 空串），供降级原因分布聚合', max_length=32),
        ),
    ]
