# Generated by Django 6.0.1 on 2026-07-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_repositoryroutingtrace_degrade_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingplan',
            name='provenance',
            field=models.CharField(choices=[('orchestrated', '编排产出'), ('draft', '未经代码调研的草稿')], db_index=True, default='draft', max_length=16, verbose_name='方案来源'),
        ),
        migrations.AddField(
            model_name='codingplan',
            name='source_artifact_version_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='delivery.ArtifactVersion.id 的软引用，兼作编排方案投影的幂等键。与已删除的 canonical_plan_id（迁移 0022 加、0031 删）不同：那一列是 chat↔delivery 双向耦合的 canonical 软链，本列只记「这份编码方案是从哪个方案版本投影来的」留痕，chat 侧不因此反向依赖 delivery。草稿路径不填（NULL）。', null=True, verbose_name='来源方案版本'),
        ),
        migrations.AddConstraint(
            model_name='codingplan',
            constraint=models.UniqueConstraint(fields=('source_artifact_version_id',), name='uniq_codingplan_source_artifact_version'),
        ),
    ]
