# Generated by Django 6.0.1 on 2026-05-09 06:27
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('repositories', '0015_alter_repositorybranchindex_status_upgrading'),
 ]
 operations = [
 migrations.CreateModel(
 name='Symbol',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('name', models.CharField(db_index=True, max_length=255)),
 ('symbol_type', models.CharField(choices=[('FUNCTION', '函数'), ('CLASS', '类'), ('METHOD', '方法'), ('VARIABLE', '变量')], db_index=True, max_length=16)),
 ('file_path', models.CharField(db_index=True, max_length=512)),
 ('start_line', models.IntegerField),
 ('end_line', models.IntegerField),
 ('signature', models.TextField(blank=True)),
 ('is_async', models.BooleanField(default=False)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('updated_at', models.DateTimeField(auto_now=True)),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='repositories.repository')),
 ],
 options={
 'verbose_name': '符号',
 'verbose_name_plural': '符号',
 },
 ),
 migrations.CreateModel(
 name='CallEdge',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('callee_name', models.CharField(db_index=True, max_length=255)),
 ('call_type', models.CharField(choices=[('DIRECT', '直接调用'), ('METHOD', '方法调用'), ('ATTRIBUTE', '属性访问')], max_length=16)),
 ('line_number', models.IntegerField),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_edges', to='repositories.repository')),
 ('caller_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to='codegraph.symbol')),
 ],
 options={
 'verbose_name': '调用边',
 'verbose_name_plural': '调用边',
 },
 ),
 migrations.CreateModel(
 name='Endpoint',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('http_method', models.CharField(max_length=16)),
 ('url_path', models.CharField(db_index=True, max_length=512)),
 ('handler_name', models.CharField(max_length=255)),
 ('view_type', models.CharField(choices=[('FUNCTION_VIEW', '函数视图'), ('CLASS_VIEW', '类视图'), ('VIEWSET', 'ViewSet')], max_length=32)),
 ('file_path', models.CharField(max_length=512)),
 ('line_number', models.IntegerField),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='repositories.repository')),
 ],
 options={
 'verbose_name': '端点',
 'verbose_name_plural': '端点',
 'indexes': [models.Index(fields=['repository', 'url_path'], name='codegraph_e_reposit_0b030e_idx'), models.Index(fields=['repository', 'handler_name'], name='codegraph_e_reposit_bb6ed2_idx')],
 },
 ),
 migrations.CreateModel(
 name='ImportEdge',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('source_file', models.CharField(db_index=True, max_length=512)),
 ('target_module', models.CharField(db_index=True, max_length=512)),
 ('imported_names', models.JSONField(default=list)),
 ('is_relative', models.BooleanField(default=False)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_edges', to='repositories.repository')),
 ],
 options={
 'verbose_name': '导入边',
 'verbose_name_plural': '导入边',
 'indexes': [models.Index(fields=['repository', 'source_file'], name='codegraph_i_reposit_2ed67c_idx'), models.Index(fields=['repository', 'target_module'], name='codegraph_i_reposit_73cec2_idx')],
 },
 ),
 migrations.AddIndex(
 model_name='symbol',
 index=models.Index(fields=['repository', 'file_path'], name='codegraph_s_reposit_f44d3d_idx'),
 ),
 migrations.AddIndex(
 model_name='symbol',
 index=models.Index(fields=['repository', 'name'], name='codegraph_s_reposit_d68d0a_idx'),
 ),
 migrations.AlterUniqueTogether(
 name='symbol',
 unique_together={('repository', 'file_path', 'name', 'start_line')},
 ),
 migrations.AddIndex(
 model_name='calledge',
 index=models.Index(fields=['repository', 'caller_symbol'], name='codegraph_c_reposit_57650d_idx'),
 ),
 migrations.AddIndex(
 model_name='calledge',
 index=models.Index(fields=['repository', 'callee_name'], name='codegraph_c_reposit_bf97f3_idx'),
 ),
 ]
