# Generated by Django 6.0.1 on 2026-05-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegraph', '0004_add_cross_repo_api_call'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apicallsite',
            new_name='codegraph_a_reposit_233b01_idx',
            old_name='codegraph_a_reposito_cfile_idx',
        ),
        migrations.RenameIndex(
            model_name='apicallsite',
            new_name='codegraph_a_api_wra_775ef2_idx',
            old_name='codegraph_a_wrapper_idx',
        ),
        migrations.RenameIndex(
            model_name='apiwrapper',
            new_name='codegraph_a_reposit_ab42bf_idx',
            old_name='codegraph_a_reposito_url_idx',
        ),
        migrations.RenameIndex(
            model_name='apiwrapper',
            new_name='codegraph_a_reposit_3e8f4b_idx',
            old_name='codegraph_a_reposito_sym_idx',
        ),
        migrations.AlterField(
            model_name='apiwrapper',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
