# Generated by Django 6.0.1 on 2026-05-29 10:14
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('codegraph', '0005_rename_codegraph_a_reposito_cfile_idx_codegraph_a_reposit_233b01_idx_and_more'),
 ]
 operations = [
 migrations.AddField(
 model_name='symbol',
 name='chunk_id',
 field=models.UUIDField(blank=True, db_index=True, null=True),
 ),
 ]
