# Generated by Django 6.0.1 on 2026-05-29 12:33

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def backfill_caller_file(apps: Any, schema_editor: Any) -> None:
    """仅回填 caller 侧 caller_file —— 修复存量边重新索引后孤儿/翻倍（work item）。

    caller_symbol 由 CASCADE 改 SET_NULL 后，per-file 幂等删除完全转移到
    ``caller_file=file_path`` 显式删除。但本迁移给存量行 caller_file 填了默认
    空串 ""，导致：含存量 CallEdge 的库 migrate 后重新索引时，存量边
    caller_symbol 被 SET_NULL（不删除）、且 caller_file=="" 永不被
    caller_file==file_path 命中删除 → 孤儿 + 翻倍。

    修复：对存量行（caller_symbol 非空且 caller_file=="" ）从其 caller_symbol
    关联 Symbol 的 file_path 回填 caller_file，使后续 per-file 删除能命中。

    边界（RESEARCH 硬约束）：**绝不**回填 callee_symbol / callee_file /
    is_cross_file —— 这三者必须留 NULL/False 给 288+ 跨文件解析层回填。
    新装库（test DB 全新建表无存量行）此步为 no-op。
    """
    CallEdge = apps.get_model("codegraph", "CallEdge")
    qs = (
        CallEdge.objects.filter(caller_symbol__isnull=False, caller_file="")
        .select_related("caller_symbol")
    )
    batch: list[Any] = []
    for edge in qs.iterator(chunk_size=2000):
        edge.caller_file = edge.caller_symbol.file_path
        batch.append(edge)
        if len(batch) >= 2000:
            CallEdge.objects.bulk_update(batch, ["caller_file"])
            batch.clear()
    if batch:
        CallEdge.objects.bulk_update(batch, ["caller_file"])


class Migration(migrations.Migration):

    dependencies = [
        ('codegraph', '0006_symbol_chunk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calledge',
            name='callee_file',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='calledge',
            name='callee_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_calls', to='codegraph.symbol'),
        ),
        migrations.AddField(
            model_name='calledge',
            name='caller_file',
            field=models.CharField(db_index=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='calledge',
            name='is_cross_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calledge',
            name='call_type',
            field=models.CharField(choices=[('DIRECT', '直接调用'), ('METHOD', '方法调用'), ('ATTRIBUTE', '属性访问'), ('JSX', 'JSX 组件引用'), ('TEMPLATE_REF', '模板组件引用')], max_length=16),
        ),
        migrations.AlterField(
            model_name='calledge',
            name='caller_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_calls', to='codegraph.symbol'),
        ),
        migrations.AddIndex(
            model_name='calledge',
            index=models.Index(fields=['repository', 'caller_file'], name='codegraph_c_reposit_cb0980_idx'),
        ),
        migrations.AddIndex(
            model_name='calledge',
            index=models.Index(fields=['repository', 'callee_file'], name='codegraph_c_reposit_e3e9ae_idx'),
        ),
        # work item：caller_file 列加好后回填存量边 caller 侧文件路径，保证 per-file
        # 删除幂等。reverse 为 noop（caller_file 列本身的 reverse 由 AddField 负责）。
        migrations.RunPython(backfill_caller_file, migrations.RunPython.noop),
    ]
