# Generated by Django 6.0.1 on 2026-05-29 12:33
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('codegraph', '0006_symbol_chunk_id'),
 ]
 operations = [
 migrations.AddField(
 model_name='calledge',
 name='callee_file',
 field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
 ),
 migrations.AddField(
 model_name='calledge',
 name='callee_symbol',
 field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_calls', to='codegraph.symbol'),
 ),
 migrations.AddField(
 model_name='calledge',
 name='caller_file',
 field=models.CharField(db_index=True, default='', max_length=512),
 ),
 migrations.AddField(
 model_name='calledge',
 name='is_cross_file',
 field=models.BooleanField(default=False),
 ),
 migrations.AlterField(
 model_name='calledge',
 name='call_type',
 field=models.CharField(choices=[('DIRECT', '直接调用'), ('METHOD', '方法调用'), ('ATTRIBUTE', '属性访问'), ('JSX', 'JSX 组件引用'), ('TEMPLATE_REF', '模板组件引用')], max_length=16),
 ),
 migrations.AlterField(
 model_name='calledge',
 name='caller_symbol',
 field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_calls', to='codegraph.symbol'),
 ),
 migrations.AddIndex(
 model_name='calledge',
 index=models.Index(fields=['repository', 'caller_file'], name='codegraph_c_reposit_cb0980_idx'),
 ),
 migrations.AddIndex(
 model_name='calledge',
 index=models.Index(fields=['repository', 'callee_file'], name='codegraph_c_reposit_e3e9ae_idx'),
 ),
 ]
