# Generated by Django 6.0.1 on 2026-05-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegraph', '0007_calledge_cross_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='calledge',
            name='callee_qualifier',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
