# Generated by Django 6.0.1 on 2026-05-31 14:26
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('codegraph', '0008_calledge_callee_qualifier'),
 ]
 operations = [
 migrations.AddField(
 model_name='apiwrapper',
 name='branch_name',
 field=models.CharField(default='', max_length=200),
 ),
 migrations.AddField(
 model_name='calledge',
 name='branch_name',
 field=models.CharField(default='', max_length=200),
 ),
 migrations.AddField(
 model_name='endpoint',
 name='branch_name',
 field=models.CharField(default='', max_length=200),
 ),
 migrations.AddField(
 model_name='importedge',
 name='branch_name',
 field=models.CharField(default='', max_length=200),
 ),
 migrations.AddField(
 model_name='symbol',
 name='branch_name',
 field=models.CharField(default='', max_length=200),
 ),
 ]
