# Generated by Django 6.0.1 on 2026-05-31 16:12
from django.db import migrations, models
class Migration(migrations.Migration):
 dependencies = [
 ('codegraph', '0009_add_branch_name'),
 ('repositories', '0026_repository_graph_build_progress'),
 ]
 operations = [
 migrations.AlterUniqueTogether(
 name='apiwrapper',
 unique_together={('repository', 'branch_name', 'file_path', 'function_symbol')},
 ),
 migrations.AlterUniqueTogether(
 name='symbol',
 unique_together={('repository', 'branch_name', 'file_path', 'name', 'start_line')},
 ),
 migrations.AddIndex(
 model_name='apiwrapper',
 index=models.Index(fields=['repository', 'branch_name', 'file_path'], name='codegraph_a_reposit_d806ba_idx'),
 ),
 migrations.AddIndex(
 model_name='calledge',
 index=models.Index(fields=['repository', 'branch_name', 'caller_file'], name='codegraph_c_reposit_e583db_idx'),
 ),
 migrations.AddIndex(
 model_name='endpoint',
 index=models.Index(fields=['repository', 'branch_name', 'file_path'], name='codegraph_e_reposit_917abd_idx'),
 ),
 migrations.AddIndex(
 model_name='importedge',
 index=models.Index(fields=['repository', 'branch_name', 'source_file'], name='codegraph_i_reposit_627db8_idx'),
 ),
 migrations.AddIndex(
 model_name='symbol',
 index=models.Index(fields=['repository', 'branch_name', 'file_path'], name='codegraph_s_reposit_f2a540_idx'),
 ),
 ]
