/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.
declare module 'vue-router/auto-resolver' {
 export type ParamParserCustom = never
}
declare module 'vue-router/auto-routes' {
 import type {
 RouteRecordInfo,
 ParamValue,
 ParamValueOneOrMore,
 ParamValueZeroOrMore,
 ParamValueZeroOrOne,
 } from 'vue-router'
 /**
 * Route name map generated by unplugin-vue-router
 */
 export interface RouteNamedMap {
 '/': RouteRecordInfo<
 '/',
 '/',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/logs/': RouteRecordInfo<
 '/logs/',
 '/logs',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/logs/webhooks/[id]': RouteRecordInfo<
 '/logs/webhooks/[id]',
 '/logs/webhooks/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/logs/work-items/[id]': RouteRecordInfo<
 '/logs/work-items/[id]',
 '/logs/work-items/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/': RouteRecordInfo<
 '/projects/',
 '/projects',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/projects/[id]/': RouteRecordInfo<
 '/projects/[id]/',
 '/projects/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/edit': RouteRecordInfo<
 '/projects/[id]/edit',
 '/projects/:id/edit',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/feishu': RouteRecordInfo<
 '/projects/[id]/feishu',
 '/projects/:id/feishu',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/new': RouteRecordInfo<
 '/projects/new',
 '/projects/new',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/repositories/': RouteRecordInfo<
 '/repositories/',
 '/repositories',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/repositories/[id]/': RouteRecordInfo<
 '/repositories/[id]/',
 '/repositories/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/repositories/[id]/credential': RouteRecordInfo<
 '/repositories/[id]/credential',
 '/repositories/:id/credential',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/repositories/new': RouteRecordInfo<
 '/repositories/new',
 '/repositories/new',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/tasks/': RouteRecordInfo<
 '/tasks/',
 '/tasks',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/tasks/[id]': RouteRecordInfo<
 '/tasks/[id]',
 '/tasks/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 }
 /**
 * Route file to route info map by unplugin-vue-router.
 * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute\`.
 *
 * Each key is a file path relative to the project root with 2 properties:
 * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>)
 * - views: names of nested views (can be passed to <RouterView name="...">)
 *
 * @internal
 */
 export interface _RouteFileInfoMap {
 'src/pages/index.vue': {
 routes:
 | '/'
 views:
 | never
 }
 'src/pages/logs/index.vue': {
 routes:
 | '/logs/'
 views:
 | never
 }
 'src/pages/logs/webhooks/[id].vue': {
 routes:
 | '/logs/webhooks/[id]'
 views:
 | never
 }
 'src/pages/logs/work-items/[id].vue': {
 routes:
 | '/logs/work-items/[id]'
 views:
 | never
 }
 'src/pages/projects/index.vue': {
 routes:
 | '/projects/'
 views:
 | never
 }
 'src/pages/projects/[id]/index.vue': {
 routes:
 | '/projects/[id]/'
 views:
 | never
 }
 'src/pages/projects/[id]/edit.vue': {
 routes:
 | '/projects/[id]/edit'
 views:
 | never
 }
 'src/pages/projects/[id]/feishu.vue': {
 routes:
 | '/projects/[id]/feishu'
 views:
 | never
 }
 'src/pages/projects/new.vue': {
 routes:
 | '/projects/new'
 views:
 | never
 }
 'src/pages/repositories/index.vue': {
 routes:
 | '/repositories/'
 views:
 | never
 }
 'src/pages/repositories/[id]/index.vue': {
 routes:
 | '/repositories/[id]/'
 views:
 | never
 }
 'src/pages/repositories/[id]/credential.vue': {
 routes:
 | '/repositories/[id]/credential'
 views:
 | never
 }
 'src/pages/repositories/new.vue': {
 routes:
 | '/repositories/new'
 views:
 | never
 }
 'src/pages/tasks/index.vue': {
 routes:
 | '/tasks/'
 views:
 | never
 }
 'src/pages/tasks/[id].vue': {
 routes:
 | '/tasks/[id]'
 views:
 | never
 }
 }
 /**
 * Get a union of possible route names in a certain route component file.
 * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute\`.
 *
 * @internal
 */
 export type _RouteNamesForFilePath<FilePath extends string> =
 _RouteFileInfoMap extends Record<FilePath, infer Info>
 ? Info['routes']: keyof RouteNamedMap
}
