/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.
declare module 'vue-router/auto-resolver' {
 export type ParamParserCustom = never
}
declare module 'vue-router/auto-routes' {
 import type {
 RouteRecordInfo,
 ParamValue,
 ParamValueOneOrMore,
 ParamValueZeroOrMore,
 ParamValueZeroOrOne,
 } from 'vue-router'
 /**
 * Route name map generated by unplugin-vue-router
 */
 export interface RouteNamedMap {
 '/': RouteRecordInfo<
 '/',
 '/',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/403': RouteRecordInfo<
 '/403',
 '/403',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/': RouteRecordInfo<
 '/admin/',
 '/admin',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/components/ClaudeConfigSection': RouteRecordInfo<
 '/admin/components/ClaudeConfigSection',
 '/admin/components/ClaudeConfigSection',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/components/FeishuIMConfigSection': RouteRecordInfo<
 '/admin/components/FeishuIMConfigSection',
 '/admin/components/FeishuIMConfigSection',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/components/FeishuTestPanel': RouteRecordInfo<
 '/admin/components/FeishuTestPanel',
 '/admin/components/FeishuTestPanel',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/components/SettingsInfoCard': RouteRecordInfo<
 '/admin/components/SettingsInfoCard',
 '/admin/components/SettingsInfoCard',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/oidc': RouteRecordInfo<
 '/admin/oidc',
 '/admin/oidc',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/prompts/': RouteRecordInfo<
 '/admin/prompts/',
 '/admin/prompts',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/providers/': RouteRecordInfo<
 '/admin/providers/',
 '/admin/providers',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/admin/users': RouteRecordInfo<
 '/admin/users',
 '/admin/users',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/analytics/': RouteRecordInfo<
 '/analytics/',
 '/analytics',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/chat': RouteRecordInfo<
 '/chat',
 '/chat',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/executions/': RouteRecordInfo<
 '/executions/',
 '/executions',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/executions/[id]': RouteRecordInfo<
 '/executions/[id]',
 '/executions/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/executions/components/ExecutionContent': RouteRecordInfo<
 '/executions/components/ExecutionContent',
 '/executions/components/ExecutionContent',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/executions/components/ExecutionDialogs': RouteRecordInfo<
 '/executions/components/ExecutionDialogs',
 '/executions/components/ExecutionDialogs',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/executions/components/ExecutionHeader': RouteRecordInfo<
 '/executions/components/ExecutionHeader',
 '/executions/components/ExecutionHeader',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/executions/components/ExecutionStatusBanners': RouteRecordInfo<
 '/executions/components/ExecutionStatusBanners',
 '/executions/components/ExecutionStatusBanners',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/force-change-password': RouteRecordInfo<
 '/force-change-password',
 '/force-change-password',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/invite/[token]': RouteRecordInfo<
 '/invite/[token]',
 '/invite/:token',
 { token: ParamValue<true> },
 { token: ParamValue<false> },
 | never
 >,
 '/login': RouteRecordInfo<
 '/login',
 '/login',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/logs/': RouteRecordInfo<
 '/logs/',
 '/logs',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/logs/triggers/[id]': RouteRecordInfo<
 '/logs/triggers/[id]',
 '/logs/triggers/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/logs/webhooks/[id]': RouteRecordInfo<
 '/logs/webhooks/[id]',
 '/logs/webhooks/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/logs/work-items/[id]': RouteRecordInfo<
 '/logs/work-items/[id]',
 '/logs/work-items/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/oidc/callback': RouteRecordInfo<
 '/oidc/callback',
 '/oidc/callback',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/profile': RouteRecordInfo<
 '/profile',
 '/profile',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/projects/': RouteRecordInfo<
 '/projects/',
 '/projects',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/projects/[id]/': RouteRecordInfo<
 '/projects/[id]/',
 '/projects/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/claude': RouteRecordInfo<
 '/projects/[id]/claude',
 '/projects/:id/claude',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/edit': RouteRecordInfo<
 '/projects/[id]/edit',
 '/projects/:id/edit',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/feishu': RouteRecordInfo<
 '/projects/[id]/feishu',
 '/projects/:id/feishu',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/members': RouteRecordInfo<
 '/projects/[id]/members',
 '/projects/:id/members',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/prompts': RouteRecordInfo<
 '/projects/[id]/prompts',
 '/projects/:id/prompts',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/providers': RouteRecordInfo<
 '/projects/[id]/providers',
 '/projects/:id/providers',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/projects/[id]/repositories': RouteRecordInfo<
 '/projects/[id]/repositories',
 '/projects/:id/repositories',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/repositories/': RouteRecordInfo<
 '/repositories/',
 '/repositories',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/repositories/[id]/': RouteRecordInfo<
 '/repositories/[id]/',
 '/repositories/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/repositories/[id]/credential': RouteRecordInfo<
 '/repositories/[id]/credential',
 '/repositories/:id/credential',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/runners/': RouteRecordInfo<
 '/runners/',
 '/runners',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/runners/[id]': RouteRecordInfo<
 '/runners/[id]',
 '/runners/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/runners/new': RouteRecordInfo<
 '/runners/new',
 '/runners/new',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/workflows/': RouteRecordInfo<
 '/workflows/',
 '/workflows',
 Record<never, never>,
 Record<never, never>,
 | never
 >,
 '/workflows/[id]': RouteRecordInfo<
 '/workflows/[id]',
 '/workflows/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 '/workflows/executions/[id]': RouteRecordInfo<
 '/workflows/executions/[id]',
 '/workflows/executions/:id',
 { id: ParamValue<true> },
 { id: ParamValue<false> },
 | never
 >,
 }
 /**
 * Route file to route info map by unplugin-vue-router.
 * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute\`.
 *
 * Each key is a file path relative to the project root with 2 properties:
 * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>)
 * - views: names of nested views (can be passed to <RouterView name="...">)
 *
 * @internal
 */
 export interface _RouteFileInfoMap {
 'src/pages/index.vue': {
 routes:
 | '/'
 views:
 | never
 }
 'src/pages/403.vue': {
 routes:
 | '/403'
 views:
 | never
 }
 'src/pages/admin/index.vue': {
 routes:
 | '/admin/'
 views:
 | never
 }
 'src/pages/admin/components/ClaudeConfigSection.vue': {
 routes:
 | '/admin/components/ClaudeConfigSection'
 views:
 | never
 }
 'src/pages/admin/components/FeishuIMConfigSection.vue': {
 routes:
 | '/admin/components/FeishuIMConfigSection'
 views:
 | never
 }
 'src/pages/admin/components/FeishuTestPanel.vue': {
 routes:
 | '/admin/components/FeishuTestPanel'
 views:
 | never
 }
 'src/pages/admin/components/SettingsInfoCard.vue': {
 routes:
 | '/admin/components/SettingsInfoCard'
 views:
 | never
 }
 'src/pages/admin/oidc.vue': {
 routes:
 | '/admin/oidc'
 views:
 | never
 }
 'src/pages/admin/prompts/index.vue': {
 routes:
 | '/admin/prompts/'
 views:
 | never
 }
 'src/pages/admin/providers/index.vue': {
 routes:
 | '/admin/providers/'
 views:
 | never
 }
 'src/pages/admin/users.vue': {
 routes:
 | '/admin/users'
 views:
 | never
 }
 'src/pages/analytics/index.vue': {
 routes:
 | '/analytics/'
 views:
 | never
 }
 'src/pages/chat.vue': {
 routes:
 | '/chat'
 views:
 | never
 }
 'src/pages/executions/index.vue': {
 routes:
 | '/executions/'
 views:
 | never
 }
 'src/pages/executions/[id].vue': {
 routes:
 | '/executions/[id]'
 views:
 | never
 }
 'src/pages/executions/components/ExecutionContent.vue': {
 routes:
 | '/executions/components/ExecutionContent'
 views:
 | never
 }
 'src/pages/executions/components/ExecutionDialogs.vue': {
 routes:
 | '/executions/components/ExecutionDialogs'
 views:
 | never
 }
 'src/pages/executions/components/ExecutionHeader.vue': {
 routes:
 | '/executions/components/ExecutionHeader'
 views:
 | never
 }
 'src/pages/executions/components/ExecutionStatusBanners.vue': {
 routes:
 | '/executions/components/ExecutionStatusBanners'
 views:
 | never
 }
 'src/pages/force-change-password.vue': {
 routes:
 | '/force-change-password'
 views:
 | never
 }
 'src/pages/invite/[token].vue': {
 routes:
 | '/invite/[token]'
 views:
 | never
 }
 'src/pages/login.vue': {
 routes:
 | '/login'
 views:
 | never
 }
 'src/pages/logs/index.vue': {
 routes:
 | '/logs/'
 views:
 | never
 }
 'src/pages/logs/triggers/[id].vue': {
 routes:
 | '/logs/triggers/[id]'
 views:
 | never
 }
 'src/pages/logs/webhooks/[id].vue': {
 routes:
 | '/logs/webhooks/[id]'
 views:
 | never
 }
 'src/pages/logs/work-items/[id].vue': {
 routes:
 | '/logs/work-items/[id]'
 views:
 | never
 }
 'src/pages/oidc/callback.vue': {
 routes:
 | '/oidc/callback'
 views:
 | never
 }
 'src/pages/profile.vue': {
 routes:
 | '/profile'
 views:
 | never
 }
 'src/pages/projects/index.vue': {
 routes:
 | '/projects/'
 views:
 | never
 }
 'src/pages/projects/[id]/index.vue': {
 routes:
 | '/projects/[id]/'
 views:
 | never
 }
 'src/pages/projects/[id]/claude.vue': {
 routes:
 | '/projects/[id]/claude'
 views:
 | never
 }
 'src/pages/projects/[id]/edit.vue': {
 routes:
 | '/projects/[id]/edit'
 views:
 | never
 }
 'src/pages/projects/[id]/feishu.vue': {
 routes:
 | '/projects/[id]/feishu'
 views:
 | never
 }
 'src/pages/projects/[id]/members.vue': {
 routes:
 | '/projects/[id]/members'
 views:
 | never
 }
 'src/pages/projects/[id]/prompts.vue': {
 routes:
 | '/projects/[id]/prompts'
 views:
 | never
 }
 'src/pages/projects/[id]/providers.vue': {
 routes:
 | '/projects/[id]/providers'
 views:
 | never
 }
 'src/pages/projects/[id]/repositories.vue': {
 routes:
 | '/projects/[id]/repositories'
 views:
 | never
 }
 'src/pages/repositories/index.vue': {
 routes:
 | '/repositories/'
 views:
 | never
 }
 'src/pages/repositories/[id]/index.vue': {
 routes:
 | '/repositories/[id]/'
 views:
 | never
 }
 'src/pages/repositories/[id]/credential.vue': {
 routes:
 | '/repositories/[id]/credential'
 views:
 | never
 }
 'src/pages/runners/index.vue': {
 routes:
 | '/runners/'
 views:
 | never
 }
 'src/pages/runners/[id].vue': {
 routes:
 | '/runners/[id]'
 views:
 | never
 }
 'src/pages/runners/new.vue': {
 routes:
 | '/runners/new'
 views:
 | never
 }
 'src/pages/workflows/index.vue': {
 routes:
 | '/workflows/'
 views:
 | never
 }
 'src/pages/workflows/[id].vue': {
 routes:
 | '/workflows/[id]'
 views:
 | never
 }
 'src/pages/workflows/executions/[id].vue': {
 routes:
 | '/workflows/executions/[id]'
 views:
 | never
 }
 }
 /**
 * Get a union of possible route names in a certain route component file.
 * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute\`.
 *
 * @internal
 */
 export type _RouteNamesForFilePath<FilePath extends string> =
 _RouteFileInfoMap extends Record<FilePath, infer Info>
 ? Info['routes']: keyof RouteNamedMap
}
