"""add_system_settings_table
Revision ID: ac3fc11fc99a
Revises: 2a1513587840
Create Date: 2026-01-17 15:49:57.398835
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'ac3fc11fc99a'
down_revision: Union[str, None] = '2a1513587840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade -> None:
 """执行升级迁移。"""
 # ### commands auto generated by Alembic - please adjust! ###
 op.create_table('system_settings',
 sa.Column('key', sqlmodel.sql.sqltypes.AutoString, nullable=False),
 sa.Column('value', sqlmodel.sql.sqltypes.AutoString, nullable=True),
 sa.Column('is_encrypted', sa.Boolean, nullable=False),
 sa.Column('description', sqlmodel.sql.sqltypes.AutoString, nullable=True),
 sa.Column('updated_at', sa.DateTime, nullable=False),
 sa.PrimaryKeyConstraint('key')
 )
 # ### end Alembic commands ###
def downgrade -> None:
 """执行降级回滚。"""
 # ### commands auto generated by Alembic - please adjust! ###
 op.drop_table('system_settings')
 # ### end Alembic commands ###
