"""add_claude_config_to_projects
Revision ID: ef3fc1fb8927
Revises: ac3fc11fc99a
Create Date: 2026-01-17 16:07:25.171733
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'ef3fc1fb8927'
down_revision: Union[str, None] = 'ac3fc11fc99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade -> None:
 """执行升级迁移。"""
 # ### commands auto generated by Alembic - please adjust! ###
 with op.batch_alter_table('projects', schema=None) as batch_op:
 batch_op.add_column(sa.Column('claude_api_key_encrypted', sqlmodel.sql.sqltypes.AutoString, nullable=True))
 batch_op.add_column(sa.Column('claude_base_url', sqlmodel.sql.sqltypes.AutoString, nullable=True))
 # ### end Alembic commands ###
def downgrade -> None:
 """执行降级回滚。"""
 # ### commands auto generated by Alembic - please adjust! ###
 with op.batch_alter_table('projects', schema=None) as batch_op:
 batch_op.drop_column('claude_base_url')
 batch_op.drop_column('claude_api_key_encrypted')
 # ### end Alembic commands ###
