"""add feishu_user_key to projects
Revision ID: 2a1513587840
Revises: 001_initial
Create Date: 2026-01-17 01:10:18.281138
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '2a1513587840'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade -> None:
 """执行升级迁移。"""
 # ### commands auto generated by Alembic - please adjust! ###
 with op.batch_alter_table('projects', schema=None) as batch_op:
 batch_op.add_column(sa.Column('feishu_user_key', sqlmodel.sql.sqltypes.AutoString, nullable=True))
 # ### end Alembic commands ###
def downgrade -> None:
 """执行降级回滚。"""
 # ### commands auto generated by Alembic - please adjust! ###
 with op.batch_alter_table('projects', schema=None) as batch_op:
 batch_op.drop_column('feishu_user_key')
 # ### end Alembic commands ###
