{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
 name: {{ include "friday.fullname" . }}-secret
 labels:
 {{- include "friday.labels" . | nindent 4 }}
type: Opaque
data:
 SECRET_KEY: {{ .Values.server.secretKey | b64enc | quote }}
 FRIDAY_ENCRYPTION_KEY: {{ .Values.server.encryptionKey | b64enc | quote }}
 DATABASE_URL: {{ if .Values.postgresql.enabled }}{{ printf "postgres://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "friday.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}{{ else }}{{ .Values.externalDatabase.url | b64enc | quote }}{{ end }}
 RUNNER_REGISTRATION_TOKEN: {{ .Values.runner.registrationToken | b64enc | quote }}
 FRIDAY_ADMIN_PASSWORD: {{ .Values.server.adminPassword | b64enc | quote }}
 QDRANT_API_KEY: {{ .Values.qdrant.apiKey | b64enc | quote }}
{{- end }}
