# Generated by Django 6.0.1 on 2026-03-14 13:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('issuer_url', models.URLField(max_length=500, verbose_name='Issuer URL')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret_encrypted', models.TextField(blank=True, null=True, verbose_name='Client Secret (加密)')),
                ('authorization_endpoint', models.URLField(max_length=500, verbose_name='授权端点')),
                ('token_endpoint', models.URLField(max_length=500, verbose_name='Token 端点')),
                ('userinfo_endpoint', models.URLField(blank=True, default='', max_length=500, verbose_name='UserInfo 端点')),
                ('scopes', models.CharField(default='openid profile email', max_length=500, verbose_name='Scopes')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OIDC 提供商',
                'verbose_name_plural': 'OIDC 提供商',
                'db_table': 'oidc_providers',
            },
        ),
        migrations.CreateModel(
            name='OIDCIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=255, verbose_name='Subject 标识')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('raw_claims', models.JSONField(blank=True, default=dict, verbose_name='原始 Claims')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_identities', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='identity.oidcprovider')),
            ],
            options={
                'verbose_name': 'OIDC 身份',
                'verbose_name_plural': 'OIDC 身份',
                'db_table': 'oidc_identities',
                'indexes': [models.Index(fields=['user', 'provider'], name='oidc_identi_user_id_9be3ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'sub'), name='unique_provider_sub')],
            },
        ),
    ]
