# Generated by Django 6.0.1 on 2026-01-20 11:19
import django.db.models.deletion
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
 initial = True
 dependencies = [
 ('projects', '0001_initial'),
 ('tasks', '0001_initial'),
 ]
 operations = [
 migrations.CreateModel(
 name='WebhookLog',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('event_uuid', models.CharField(blank=True, max_length=100, null=True)),
 ('event_type', models.CharField(blank=True, default='', max_length=100)),
 ('project_key', models.CharField(blank=True, max_length=100, null=True)),
 ('raw_request', models.TextField),
 ('status', models.CharField(choices=[('accepted', '已接受'), ('ignored', '已忽略'), ('error', '错误'), ('duplicate', '重复')], default='accepted', max_length=20)),
 ('error_message', models.TextField(blank=True, null=True)),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='projects.project')),
 ],
 options={
 'verbose_name': 'Webhook 日志',
 'verbose_name_plural': 'Webhook 日志',
 'db_table': 'webhook_logs',
 'ordering': ['-created_at'],
 },
 ),
 migrations.CreateModel(
 name='WorkItemLog',
 fields=[
 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
 ('work_item_id', models.CharField(max_length=100)),
 ('work_item_type', models.CharField(blank=True, default='', max_length=50)),
 ('project_key', models.CharField(blank=True, max_length=100, null=True)),
 ('raw_response', models.TextField),
 ('created_at', models.DateTimeField(auto_now_add=True)),
 ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_logs', to='projects.project')),
 ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_logs', to='tasks.task')),
 ],
 options={
 'verbose_name': '工作项日志',
 'verbose_name_plural': '工作项日志',
 'db_table': 'work_item_logs',
 'ordering': ['-created_at'],
 },
 ),
 ]
