"""Wave stub — PromptVersion append-only + 幂等 + activate pointer flip 测试。"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 6 待实现（待 services.append_version 就位）")
class TestPromptVersioning:
 def test_append_version_increments_version_number(self) -> None: ...
 def test_append_version_idempotent_on_byte_equal_body(self) -> None: ...
 def test_append_version_atomic_transaction(self) -> None: ...
 def test_activate_version_switches_pointer_only(self) -> None: ...
 def test_activate_to_earlier_version_rollback(self) -> None: ...
 def test_compute_version_diff_unified_format(self) -> None: ...
