"""Wave stub — PROMPT_CENTER_DISABLED_KEYS 灰度开关测试。"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 6 待实现（待 services._get_disabled_keys 就位）")
class TestPromptCenterDisabledKeys:
 def test_env_var_hit_bypasses_db(self) -> None: ...
 def test_empty_env_var_allows_db_path(self) -> None: ...
 def test_disabled_key_still_runs_declared_var_check(self) -> None: ...
 def test_multiple_comma_separated_keys(self) -> None: ...
