"""Prompt Preview API 测试（Plan Task 3 填实）。
Wave stub 在 Task 1 落地，真实断言在 Task 3 填充。
"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 3 待实现（待 views.py 就位）")
@pytest.mark.django_db
class TestPromptPreviewAPI:
 """Preview 5 用例（Task 3 填充）。"""
 def test_preview_happy_path(self) -> None: ...
 def test_preview_missing_variables_returns_422(self) -> None: ...
 def test_preview_extra_variables_ok(self) -> None: ...
 def test_preview_unauthenticated_401(self) -> None: ...
 def test_preview_project_scope_requires_member_role(self) -> None: ...
