"""Wave stub — Prompt + PromptVersion ORM 测试，由 Wave Task 3 填充。"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 3 待实现（待 Prompt 模型就位）")
class TestPromptModel:
 def test_prompt_uses_uuid_primary_key(self) -> None: ...
 def test_system_slug_unique_constraint_enforced(self) -> None: ...
 def test_project_slug_unique_per_project(self) -> None: ...
 def test_same_slug_can_coexist_system_and_project(self) -> None: ...
 def test_prompt_version_ordering_desc(self) -> None: ...
 def test_active_version_fk_set_null_on_delete(self) -> None: ...
