"""Prompt API RBAC 权限矩阵测试（Plan Task 5 填实）。
Wave stub 在 Task 1 落地，真实断言在 Task 5 填充。
"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 5 待实现（待 views.py + permissions.py 就位）")
@pytest.mark.django_db
class TestPromptAPIPermissions:
 """12 条 RBAC 测试（Task 5 填充）。
 矩阵：
 - 系统级：IsSuperUser 可写 / IsAuthenticated 可读
 - 项目级：IsProjectAdmin 可写 / VIEWER+ 可读
 - 双分支拆分：非 superuser ADMIN 正面 + 非 superuser MEMBER 负面
 - superuser bypass 路径专用测试
 """
 def test_viewer_can_read_system_prompts(self) -> None: ...
 def test_regular_user_cannot_create_system_prompt_403(self) -> None: ...
 def test_superuser_can_create_system_prompt(self) -> None: ...
 def test_non_superuser_project_admin_can_edit_project_prompt(self) -> None: ...
 def test_non_superuser_project_member_cannot_edit_project_prompt(self) -> None: ...
 def test_project_viewer_cannot_edit_project_prompt_403(self) -> None: ...
 def test_non_member_cannot_read_project_prompt_403(self) -> None: ...
 def test_superuser_bypasses_project_admin_check(self) -> None: ...
 def test_cross_project_leak_prevention(self) -> None: ...
 def test_delete_project_prompt_requires_admin_role(self) -> None: ...
 def test_regular_user_cannot_delete_system_prompt(self) -> None: ...
 def test_project_member_cannot_delete_project_prompt(self) -> None: ...
