"""Prompt Versions API 测试（Plan Task 4 填实）。
Wave stub 在 Task 1 落地，真实断言在 Task 4 填充。
"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 4 待实现（待 views.py 就位）")
@pytest.mark.django_db
class TestPromptVersionsAPI:
 """Versions 7 用例（Task 4 填充）。"""
 def test_versions_list_returns_desc_order(self) -> None: ...
 def test_version_diff_unified_format(self) -> None: ...
 def test_version_diff_non_existent_version_404(self) -> None: ...
 def test_activate_version_switches_pointer(self) -> None: ...
 def test_activate_does_not_create_new_version(self) -> None: ...
 def test_activate_to_earlier_version_rollback(self) -> None: ...
 def test_activate_system_prompt_non_superuser_forbidden(self) -> None: ...
