"""Wave stub — Jinja2 ImmutableSandboxedEnvironment 单例与沙箱行为测试。"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 5 待实现（待 engine.py 就位）")
class TestJinjaEngine:
 def test_env_singleton_returns_same_instance(self) -> None: ...
 def test_env_is_immutable_sandboxed(self) -> None: ...
 def test_env_uses_strict_undefined(self) -> None: ...
 def test_env_autoescape_is_false(self) -> None: ...
 def test_env_strict_undefined_raises_on_missing_var(self) -> None: ...
 def test_immutable_sandbox_blocks_mutator_call(self) -> None: ...
 def test_sandbox_blocks_dunder_access(self) -> None: ...
