"""Wave stub — post_save signal handler 测试（ Phase 仅打日志）。"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 7 待实现（待 signals.py 就位）")
class TestPromptSignals:
 def test_post_save_handler_fires_on_create(self) -> None: ...
 def test_post_save_handler_fires_on_update(self) -> None: ...
 def test_post_save_handler_only_logs_no_cache_delete(self) -> None: ...
