"""Wave stub — render_prompt / get_active_prompt / append_version 测试。"""
from __future__ import annotations
import pytest
@pytest.mark.skip(reason="Wave Task 6 待实现（待 services.py 就位）")
class TestGetDeclaredVariables:
 def test_extracts_ordered_unique_vars(self) -> None: ...
 def test_ignores_attribute_access(self) -> None: ...
@pytest.mark.skip(reason="Wave Task 6 待实现（待 services.py 就位）")
class TestRenderPrompt:
 def test_happy_path_with_db_record(self) -> None: ...
 def test_fallback_when_db_empty(self) -> None: ...
 def test_fallback_path_skips_sanitization(self) -> None: ...
 def test_variable_missing_raises_typed_error(self) -> None: ...
 def test_truncates_variable_over_max_length(self) -> None: ...
 def test_escapes_double_brace_to_entity(self) -> None: ...
 def test_wraps_variables_in_xml_tags(self) -> None: ...
 def test_project_override_precedence(self) -> None: ...
